refactor: step3 기능 우선 패키지 구성하기
next-step/ddd-strategic-design pull request #107
Opened 2021-09-10 08:52 UTC by anjaemin

tobe.kitchenpos 패키지 하위에 패키지들을 구성해봤습니다

2021-09-11 14:01 UTC, liquidjoo requested changes
기능 우선 패키지 구성하기 미션 잘해주셨어요 👍 
몇가지 생각해보면 좋을 것 같은 코멘트 남겼어요~ 확인하고 다시 요청주세요 🙇

2021-09-14 02:25 UTC, anjaemin commented on src/main/java/tobe/kitchenpos/menu/application/MenuGroupService.java
> +public class MenuGroupService {
Menu가 aggregate root가 되고 MenuGroup은 Menu의 child인 형태로 생각이 되는데요 이렇게되면 MenuGroupService를 따로 두지 않고 MenuService에 MenuGroupService를 합치는 형태로 바뀌면 맞을까요?

2021-09-14 02:26 UTC, anjaemin commented on src/main/java/tobe/kitchenpos/menu/ui/MenuGroupRestController.java
> +public class MenuGroupRestController {
위 내용과 같이 MenuRestController에 MenuGroupRestController를 합치면 맞을까요?

2021-09-14 02:28 UTC, anjaemin commented on src/main/java/tobe/kitchenpos/order/application/OrderTableService.java
> +    private final OrderRepository orderRepository;
OrderTable은 매장주문시에만 필요한 내용인데 Order를 EatInOrder, DeliveryOrder, TakeoutOrder로 나누는것을 생각해보긴 했는데 주문형식에 따라 패키지를 나누는게 좋을까요?

2021-09-22 15:53 UTC, liquidjoo approved these changes
피드백 반영 너무 좋았습니다 👍 
저의 무리한 요구사항일 수도 있지만 계속해서 반영해 주시고 끝까지 해주셔서 감사합니다 🙇 
너무 수고하셨습니다~ 😎

2021-09-22 15:54 UTC, merged