🚀 2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #143
Opened 2022-03-25 14:52 UTC by dacapolife87

안녕하세요 리뷰어님

모델링하기 미션 진행하였습니다.
처음 모델링하기라는것을 이해하는데 좀 오래걸렸습니다.
지금도 사실 이해를 하였다고는 말하지 못할거 같습니다..
일단 혼자 고민을 하다가 일단 리뷰를 통해서 잘못된점을 꺠닫는것도 학습하는 방법이라고 생각하여
제가 생각한 모델링으로 진행을 해보았습니다.

요구사항을 기준으로 각각의 Domain이 생성이 되면 그안에 주요한 변수들과 메소드가 존재하게 될텐데
그걸 생각하여 속성과 행위를 나누어 보았습니다.
모델링을 이렇게 하는것인지... 자신감이 좀 없네요

이번에 잘못된 부분 많은 지적 부탁드립니다.
감사합니다.

2022-03-27 06:17 UTC, serverwizard requested changes
모델링 잘 해주셨네요 👍
몇 가지 간단한 코멘트 남겼으니 확인 한 번 부탁드릴게요.

궁금하신점은 DM 남겨주세요~ 😄

2022-03-27 06:17 UTC, serverwizard commented on README.md
>  ## 모델링
아래는 모델링하기 미션에서 가장 많이 나왔던 질문 중 하나인데요! 
- Step2를 진행하면서 많이 의아했던 점이 있습니다! 요구사항정리, 모델링, 용어사전의 내용이 많이 중복되는것 같습니다.
   특히 ‘상품가격은 0원 이상이어야 한다. ’와 같은 validation 부류들은 요구사항정리, 모델링, 용어사전 중복해서 들어가도 되는것인지.. 아니면 요구사항정리에만 들어가야 하는것인지 많이 헷갈렸습니다. 명확한 경계라는것은 없다는것을 알면서 라도 
요구사항정리, 모델링, 용어사전이 꼭 담아야 하는 필수 내용들은 숙지하고 싶다는 생각이 들었습니다

이에 대한 제 개인적인 생각을 공유드려요~ 정답은 아니니 참고만 하세요 :) 
```
제 개인적인 생각은 요구사항 정리는 개발할 때 참고하는 기획서라는 느낌을 받아서 디테일한 부분(validation 포함)까지 
들어가는 걸 선호해요.(필수) 그리고 해결하고자 하는 문제의 요구사항을 바탕으로 모델링도 진행할 수 있다고 생각해서 
요구사항과 모델링은 표현하는 방법의 차이일 뿐이지 많이 유사할 수도 있다는 생각이 들더라구요.
용어 사전은 함께 일하는 분들과 커뮤니케이션 할 때 싱크를 맞추기 위해 필요한 거라는 생각이 들어서, 
함께 일하는 사람들이 이러한 validation 부분도 포함하자고 한다면 포함해도 된다는 생각이예요 (옵셔널)
```

2022-03-27 06:17 UTC, serverwizard commented on README.md
> +  - 상품(Product)의 목록을 조회(findAll)할수 있다.
모델의 속성과 기능을 분리해서 잘 정리해주셨네요. 👍 👍 
사실 이 방법도 정답이라고 할 순 없겠지만, 개인적으로 저는 이 방법을 선호하는 편이에요~

아래 가이드도 정답은 아니니 참고만 부탁드려요~
```
Product
- Product는 이름과 가격을 가진다. 

- Product을 추가한다.
   - Product의 가격은 0원 이상이어야 등록할 수 있다.
- Product 목록을 조회한다.
```

2022-03-27 06:17 UTC, serverwizard commented on README.md
> +  - 메뉴(Menu)의 목록을 조회(findAll)할 수 있다.
아래와 같이 모델링한 것과 비교해보는 것도 좋을 것 같아요.
```
Menu
- Menu는 이름, 가격을 가진다.
- Menu는 하나 이상의 MenuProduct를 가진다.
- Menu는 하나의 Menu Group에 속한다.

- Menu를 추가한다.
   - Menu의 가격은 0원 이상이어야 추가할 수 있다.
   - Menu의 가격이 MenuProduct들 가격의 합보다 작아야 추가할 수 있다.
   - 추가할 Menu Group이 존재하지 않는다면 추가할 수 없다.
```

2022-04-01 01:12 UTC, dacapolife87 commented on README.md
> +  - 상품(Product)의 목록을 조회(findAll)할수 있다.
기존에 제가 작성한 방법에서 좀더 부드러운 느낌입니다
딱딱한 느낌보다는 읽기가 편해서 모르는사람이봐도 편하게읽고 이해할수있을거 같다는 생각이 드네요

2022-04-01 01:13 UTC, dacapolife87 commented on README.md
> +  - 메뉴(Menu)의 목록을 조회(findAll)할 수 있다.
이번에 모델링하는것을 전체적으로 수정해보았습니다.

2022-04-01 01:14 UTC, dacapolife87 commented
안녕하세요
요즘 회사일때문에 과제가 많이 늦었네요...
다시 달려보도록하겠습니다.
이번에도 좋은 리뷰 부탁드리겠습니다.

2022-04-03 02:18 UTC, serverwizard approved these changes
모델링 잘해주셨네요. 👍 

간단한 코멘트 한 개 남겨뒀으니 다음 미션 진행하실 때 참고만 부탁드릴게요
그럼 남아있는 미션들도 화이팅입니다. 😄

2022-04-03 02:18 UTC, serverwizard commented on README.md
> +  - 상품(Product)의 가격(price)이 변경될때 메뉴(Menu)의 가격(price)이 메뉴에 속한 상품(MenuProduct) 금액의 합(sum)보다 크면 메뉴가 숨겨진다.(hide)
잘 정리해주셨네요 👍 👍

2022-04-03 02:18 UTC, serverwizard commented on README.md
> +  - 주문테이블(OrderTable)의 모든 주문(Order)이 완료(complete)되면 빈테이블(empty)로 정리(clear)한다.
현재 주문 같은 경우에는 `매장주문`/`포장주문`/`배달주문` 컨텍스트 중 어디에 속하냐에 따라 의미가 조금씩 달라지는데요.
- 매장주문 같은 경우에는 메뉴 취소 또는 환불을 할 수 있기 때문에 수량이 음수가 가능 (취소 개념)

따라서, 바운디드컨텍스트(`매장주문`/`포장주문`/`배달주문`)에 따라, 용어사전 및 모델링을 할 수도 있을 것 같아요. :)

2022-04-03 02:18 UTC, merged