크게 소리 내어 모델링 하기 [STEP 2] - 모델링 하기
next-step/ddd-strategic-design pull request #144
Opened 2022-03-25 14:57 UTC by parkeeseul

안녕하세요 리뷰어님 모델링 하기 미션 제출합니다!
이번 주차 미션은 1단계 부터 @seok-2-o  님 과 함께 진행중입니다. 😄 

연습도 해볼겸 다양한 방식으로 진행을 해보았는데요, 모델링이 참 어렵네요 😢 
전체 진행 과정에 대한 [문서](https://www.notion.so/seok2/2-53f726fad40f47e5b8842bfc3492d216)도 함께 공유 드립니다!
즐거운 주말 되세요! 😄

2022-03-26 14:42 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-03-26 14:42 UTC, kyucumber commented on README.md
>  ## 모델링
공유해주신 문서를 봤는데 꼼꼼하게 작성해주신 부분이 인상적이네요! 👍 👍

2022-03-26 14:42 UTC, kyucumber commented on README.md
> +- `상품(Product)` 은 가격을 변경할 수 있다.
모델링에 정답이 있는 것은 아니지만, 저는 모델링을 기반으로 개발을 진행하는 경우가 많을거라고 생각합니다.
이름, 가격 속성에 대한 제약이나 가격 변경이라는 행동 자체에 대한 제약이 모델링에 포함되면 어떨까요?

지금 모델링 된 내용만으로 개발을 진행한다면 아래와 같은 제약에 대해 개발 단계에서 빠트리는 부분이 많을 거라고 생각해요. 

- 주문을 접수한다.
  - 접수를 위해서는 대기중 상태여야 한다
- 주문을 서빙한다.
  - 서빙을 위해 접수 상태여야 한다.
- 주문을 배달한다.
  - 배달 주문이어야 하며, 서빙 상태여야 한다.

등등..

도메인을 잘 이해한 사람이 개발을 진행한다면 위와 같은 제약을 빠트리진 않겠지만요.

팀 모두가 도메인 내부에 존재하는 모든 부분에 대해 전문가가 되기 어려운 상황도 많을 거라고 생각해서 저는 제약 부분도 모델링에 정의되면 좋을 것 같아요.

요건 개인적인 의견이니 생각하는 바가 다르시다면 현재와 같은 구조도 괜찮을 것 같습니다~

2022-03-26 14:42 UTC, kyucumber commented on README.md
> +```
복잡한 주문 프로세스가 mermaid로 표현되니 한눈에 들어오고 깔끔하네요. 👍

2022-03-26 14:42 UTC, kyucumber commented on README.md
> +- 주문이 완료된 `매장 주문(table order)`은 테이블을 `정리(clean)` 한다.
주문과 관련된 도메인을 잘 아는 사람이라면 "정리"라는 행위를 통해 어떤 부분을 작업해야 하는지 잘 알 것 같아요.

하지만 도메인에 대해 조금은 지식이 부족한 사람이 이 모델링을 통해 개발을 진행할 수도 있으니 아래와 같이 조금 더 구체적인 부분을 적어주면 좋을 것 같습니다.

```
- 주문이 완료된 `매장 주문(table order)`은 주문 테이블을 빈 테이블로 설정하고 방문 고객 수를 0으로 변경한다.
```

요구사항과 비교하면 조금 너무 디테일하고 코드랑 비슷한 느낌이라 별로라고 느끼실수도 있을 것 같아요.
저는 모델링은 개발과 조금 밀접하게 연관되어 기술되어도 괜찮다고 생각합니다~

2022-03-26 14:42 UTC, kyucumber commented on README.md
> +- 주문이 완료된 `매장 주문(table order)`은 테이블을 `정리(clean)` 한다.
중요한 부분은 아니지만 일관성 있게 "주문 테이블"이라고 사용해도 좋을 것 같네요!

2022-03-26 14:42 UTC, kyucumber commented on README.md
> +- `주문테이블(order table)` 은 반드시 이름, `방문 손님 수(number of guest)`, 지정 여부를 가진다.
이건 중요한 부분은 아닌것 같지만 같은 타입의 속성에 대해 다르게 표현된 부분이 궁금해서 코멘트 남깁니다.

메뉴와 주문 테이블 모두 순서대로 boolean 타입의 displayed, empty 라는 속성을 가지고 있습니다.

둘다 동일한 속성값인데 메뉴는 숨기거나 노출할 수 있다로 표현되고, 주문 테이블은 지정 여부를 가진다는 말로 표현되는데 이 경우 모델링을 본 개발자는 메뉴의 경우는 Visible, Invisible이라는 상태 형태로 표현하길 의도한걸로 이해할수 있지 않을까요?

2022-03-28 10:44 UTC, parkeeseul commented on README.md
> +- `상품(Product)` 은 가격을 변경할 수 있다.
이 부분 저도 고민이 많았는데요. 모델링이 어디까지 작성되야 하는지 아직 잘 모르겠네요 😢
 
처음엔 개발을 진행한다는 생각으로 모델링을 접근했었는데, 진행하다 보니 과연 개발적인 관점으로 접근하는게 맞을까? 라는 고민이 들었습니다. 이번 미션의 모델링은 개발적인 관점 보다는 개발자가 아니더라도 모두가 키친포스라는 도메인에 대해 이해할 수 있어야 한다라는 관점으로 접근하는게 맞지 않을까 라고 생각했습니다.

 말씀주신 제약 사항들이 모델링에 포함되므로서 도메인의 이해가 더 잘 된다고 하면 넣어도 좋겠다는 생각도 들면서,
 이미 작성한 요구사항을 단순히 다시 한번 정의하는게 되진 않나 하는 생각이 들어서 제약 사항들을 제외해 보았는데요,
 말씀 주신 것 처럼 팀 모두가 도메인을 잘 이해하기 위해 제약사항이 들어가는게 좋을 것 같네요!
좋은 의견 감사합니다 😄

2022-03-28 15:38 UTC, parkeeseul commented on README.md
> +- 주문이 완료된 `매장 주문(table order)`은 테이블을 `정리(clean)` 한다.
좋은 의견 감사합니다 🙏 
https://github.com/next-step/ddd-strategic-design/pull/144#discussion_r836292178 에서 저의 의견을 남겼었는데요,

> 이번 미션의 모델링은 개발적인 관점 보다는 개발자가 아니더라도 모두가 키친포스라는 도메인에 대해 이해할 수 있어야 한다라는 관점으로 접근하는게 맞지 않을까 라고 생각했습니다. 

`정리(clean)` 라는 행위에 대해 말씀해 주신 사항을 용어사전에 정의하는 것에 대해서는 어떻게 생각하시나요? 😄

2022-03-28 15:51 UTC, parkeeseul commented on README.md
> +- `주문테이블(order table)` 은 반드시 이름, `방문 손님 수(number of guest)`, 지정 여부를 가진다.
주문 테이블의 지정 여부는 주문 테이블이 가질 수 있는 상태에 대한 정의 였고
메뉴의 숨기거나 노출할 수 있다는 메뉴의 행위에 대해 정의했던 부분이였는데 제가 헷갈릴 수 있게 정의를 했었던 것 같습니다 😢 
다음과 같이 정의를 다시 해 보았는데 괜찮을까요? 😄 
```
- `메뉴 (Menu)` 는 하나 이상의 `메뉴 상품 (Menu Product)` , 이름, 가격, 노출 여부, `메뉴그룹(Menu Group)`을 가진다.
  - 가격은 0보다 커야 하며, 속한 `메뉴 상품 (Menu Product)`의 가격의 합보다 작거나 같은 가격을 가져야 한다.
- `메뉴 (Menu)` 는 숨길 수 있다.
- `메뉴 (Menu)` 는 노출 할 수 있다.
```

2022-03-29 14:32 UTC, kyucumber commented on README.md
> +- 주문이 완료된 `매장 주문(table order)`은 테이블을 `정리(clean)` 한다.
그렇게 정리하고 마크다운에 각주를 넣을 수 있었던 것 같은데 연결시켜주면 조금 더 편리하고 좋은 문서가 될 수 있겠네요!

```
- 주문이 완료된 `매장 주문(table order)`은 테이블을 `정리[^clean]` 한다.


\[^clean]: 정리 설명
```

2022-03-29 14:37 UTC, kyucumber commented on README.md
> +- `상품(Product)` 은 가격을 변경할 수 있다.
사실 저도 매번 요런 모델링을 작성할 때 마다 어디까지, 어떻게 작성해야 할지 고민이 많이 되는 것 같아요, 도메인과 상황마다 매번 다른식으로 하기도 해서 저도 어렵다고 생각하고 있습니다. 😭 

재성님이 오늘 강의때 말씀해주셨던 것처럼 요구사항은 불확실하고, 사용자 중심의 설계가 주로 이루어지게 됩니다.

이슬님이 말씀해주신 것 처럼 모델링에서 요구사항과 중복된다고 느껴지는 부분이 많지만 불확실한 요구사항을 다시 한번 되돌아보고 모델링을 기반으로 개발을 할 수 있도록 모델링에 제약과 같은 구체적인 부분이 들어가는게 좋다고 생각해요.

2022-03-29 14:39 UTC, kyucumber approved these changes
다음 단계 진행을 위해 머지하겠습니다.

남겨둔 코멘트는 시간 날 때 한번 확인 부탁드려요.

- https://github.com/next-step/ddd-strategic-design/pull/144#discussion_r837557626
- https://github.com/next-step/ddd-strategic-design/pull/144#discussion_r837552136

2022-03-29 14:41 UTC, kyucumber commented
페어로 꼼꼼하게 잘 진행해주신 부분 인상적이었습니다! 👍 

모델링과 요구사항은 답이 없다보니 아무래도 많은 부분에 대해 리뷰를 남기기 어려웠던 것 같아요.

진행해주신 열정에 비해 리뷰가 부족하진 않았나 하는 아쉬움이 조금 있는데, 혹시 부족한 부분이 있다면 따로 질문 남겨주셔도 좋을 것 같아요!

고생하셨습니다.

2022-03-29 14:41 UTC, merged