[step2] 모델링 하기
next-step/ddd-strategic-design pull request #146
Opened 2022-03-26 14:17 UTC by hyunssooo

안녕하세요 :) 잘 부탁드립니다!

2022-03-27 06:33 UTC, serverwizard requested changes
모델링 잘 해주셨네요 👍
몇 가지 간단한 코멘트 남겼으니 확인 한 번 부탁드릴게요.

궁금하신점은 DM 남겨주세요~ 😄

2022-03-27 06:33 UTC, serverwizard commented on README.md
>  ## 모델링
아래는 모델링하기 미션에서 가장 많이 나왔던 질문 중 하나인데요! 
- Step2를 진행하면서 많이 의아했던 점이 있습니다! 요구사항정리, 모델링, 용어사전의 내용이 많이 중복되는것 같습니다.
   특히 ‘상품가격은 0원 이상이어야 한다. ’와 같은 validation 부류들은 요구사항정리, 모델링, 용어사전 중복해서 들어가도 되는것인지.. 아니면 요구사항정리에만 들어가야 하는것인지 많이 헷갈렸습니다. 명확한 경계라는것은 없다는것을 알면서 라도 
요구사항정리, 모델링, 용어사전이 꼭 담아야 하는 필수 내용들은 숙지하고 싶다는 생각이 들었습니다

이에 대한 제 개인적인 생각을 공유드려요~ 정답은 아니니 참고만 하세요 :) 
```
제 개인적인 생각은 요구사항 정리는 개발할 때 참고하는 기획서라는 느낌을 받아서 디테일한 부분(validation 포함)까지 
들어가는 걸 선호해요.(필수) 그리고 해결하고자 하는 문제의 요구사항을 바탕으로 모델링도 진행할 수 있다고 생각해서 
요구사항과 모델링은 표현하는 방법의 차이일 뿐이지 많이 유사할 수도 있다는 생각이 들더라구요.
용어 사전은 함께 일하는 분들과 커뮤니케이션 할 때 싱크를 맞추기 위해 필요한 거라는 생각이 들어서, 
함께 일하는 사람들이 이러한 validation 부분도 포함하자고 한다면 포함해도 된다는 생각이예요 (옵셔널)
```

2022-03-27 06:33 UTC, serverwizard commented on README.md
> +  - 변경될 때 메뉴의 가격이 메뉴에 속한 상품 금액의 합보다 크면 메뉴가 숨겨진다.
모델의 속성과 기능을 분리해서 잘 정리해주셨네요. 👍 👍 
사실 이 방법도 정답이라고 할 순 없겠지만, 개인적으로 저는 이 방법을 선호하는 편이에요~

아래 가이드도 정답은 아니니 참고만 부탁드려요~
```
Product
- Product는 이름과 가격을 가진다. 

- Product을 추가한다.
   - Product의 가격은 0원 이상이어야 등록할 수 있다.
- Product 목록을 조회한다.
```

2022-03-27 06:33 UTC, serverwizard commented on README.md
> +- `hide (숨길 수 있다)`
아래와 같이 모델링한 것과 비교해보는 것도 좋을 것 같아요.
```
Menu
- Menu는 이름, 가격을 가진다.
- Menu는 하나 이상의 MenuProduct를 가진다.
- Menu는 하나의 Menu Group에 속한다.

- Menu를 추가한다.
   - Menu의 가격은 0원 이상이어야 추가할 수 있다.
   - Menu의 가격이 MenuProduct들 가격의 합보다 작아야 추가할 수 있다.
   - 추가할 Menu Group이 존재하지 않는다면 추가할 수 없다.
```

2022-03-28 16:23 UTC, hyunssooo commented on README.md
> +- `hide (숨길 수 있다)`
좀 더 매끄럽고 자연스럽게 읽을 수 있는 것 같아요 :) 
이 부분을 보니 제 모델링은 조금 개발자 관점이 아니였나라는 생각이 드네요! 🧐

2022-03-28 16:34 UTC, serverwizard approved these changes
모델링 잘해주셨네요. 👍 

그럼 남아있는 미션들도 화이팅입니다. 😄

2022-03-28 16:34 UTC, serverwizard commented on README.md
> +- `hide (숨길 수 있다)`
사실 정답이 있는 부분은 아니다보니, 앞으로도 끊임없이 자신만의 모델링 방식을 만들어가시면 좋을 것 같아요 👍

2022-03-28 16:36 UTC, merged