🚀 2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #159
Opened 2022-04-03 13:48 UTC by hiro032

리뷰어님 안녕하세요! 2단계 모델링 하기 PR 보냅니다!
이번 미션을 페어로 진행했는데요. 진행하다가 애매한 용어가 생겨 질문 남겨 봅니다.
모델링을 하던 중 메뉴를 정리하던 중에,
- 메뉴가 메뉴 그룹에 속한다
- 메뉴가 메뉴 그룹을 갖는다

이 두 문장 중 어떤 게 자연스러운 문장일지 정리가 안돼서 어떤 식으로 표현하는 게 좋을지 결론이 나지 않았습니다.
제 개인적인 생각으로는 요구사항에서 메뉴 그룹으로 메뉴를 조회하는 기능은 존재하지 않고,
메뉴를 조회 시 메뉴 그룹을 보여줘야 한다고 생각해서 메뉴가 메뉴 그룹을 갖는다.라고 정리하는 게 맞는다고 생각했는데요, 확실하지 않은 부분이라 질문으로 남겨봅니다.
감사합니다!

2022-04-05 00:31 UTC, liquidjoo requested changes
2단계 미션 잘 구현해주셨어요 👍 
몇 가지 코멘트 남겼어요~
확인하고 다시 요청 주세요 🙇

2022-04-05 00:31 UTC, liquidjoo commented on README.md
> +  - 상품 가격(`Product Price`)은 0원 이상이여야 한다.
어떤 행위에 대한 유효성 검사일까요?

2022-04-05 00:31 UTC, liquidjoo commented on README.md
> +- 상품(`Product`)은 가격을 변경할 수 있다.
가격을 변경 시 어떤 유효성 검사가 필요할까요?

2022-04-05 00:31 UTC, liquidjoo commented on README.md
> +- 메뉴 그룹(`Menu Group`)은 반드시 이름(`name`)을 가져야 한다.
메뉴 그룹이 이름을 필드값으로 인해 생성자에서 필요로하는지 아니면 메뉴 그룹을 등록할 때 필요로하는지 명확하게 정의하면 좋을 것 같아요

2022-04-05 00:31 UTC, liquidjoo commented on README.md
> +### 메뉴(Menu)
행위에 대한 정의도 같이 표현되며 좋을 것 같아요 :)

2022-04-05 00:31 UTC, liquidjoo commented on README.md
> +- 매장 주문(`Eat In Order`)의 주문 제품(`Order Line Item`)은 수량이 음수일 수 있다.
`수량이 음수일 수 있다` 는 조금 어색한 것 같아요 ~
어떤 부분을 보고 정의를 한 것인지 알 수 있을까요?

2022-04-06 06:50 UTC, hiro032 commented on README.md
> +  - 상품 가격(`Product Price`)은 0원 이상이여야 한다.
'상품 가격을 생성 & 변경 시 0원 이상이어야 한다.' 로 수정했습니다.!

2022-04-06 06:52 UTC, hiro032 commented on README.md
> +- 메뉴 그룹(`Menu Group`)은 반드시 이름(`name`)을 가져야 한다.
`메뉴 그룹을 생성 시 반드시 이름을 가져야 한다.`로 수정했습니다.!

2022-04-06 06:56 UTC, hiro032 commented on README.md
> +### 메뉴(Menu)
가격 변경, 전시의 행위를 표현했습니다.!

2022-04-06 06:57 UTC, hiro032 commented on README.md
> +- 매장 주문(`Eat In Order`)의 주문 제품(`Order Line Item`)은 수량이 음수일 수 있다.
강의에서 나온 부분을 생각해서 모델링에 작성했는데요. 코드를 보고 파악하기는 어려울것같아서 제외 했습니다.!

2022-04-08 01:19 UTC, liquidjoo approved these changes
피드백 반영 잘해주셨어요 👍 
몇 가지 코멘트 남겼어요~ 확인하고 다음 단계에 같이 반영해 보면 좋을 것 같아요
다음 단계 진행해 주세요 🙇

2022-04-08 01:19 UTC, liquidjoo commented on README.md
> +  - Q. 식별자(`Id`) 라는 단어는 개발자가 아닌 사람이 이해하기 어렵지 않을까?
질문은 모델링에 어울리지 않아서 별도의 영역으로 표현해보면 어떨까요?

2022-04-08 01:19 UTC, liquidjoo commented on README.md
> +### 배달 주문(`Delivery Order`)
주문 타입에 대한 설명이 주문에 있기에 주문 하위에 두는 것도 좋을 것 같아요 :)

2022-04-08 01:19 UTC, merged