1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #174
Opened 2022-09-01 18:04 UTC by gmoon92

안녕하세요 리뷰어님 😀

기능 설명은 요구사항에 충분히 정의가 되어 있다보니
용어 사전엔 모든 이해 관계자가 이해할 수 있도록 "어떻게(how)" 보다는 "무엇(what)" 으로 정의하려 노력했습니다.

잘 부탁드립니다!!.🙇🏻‍♂️

2022-09-09 11:16 UTC, kyucumber requested changes
안녕하세요.

용어사전 잘 정리해주셨네요, 몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 주문 상태    | Order Status        | 주문 상태 대분류, 참고 [주문 상태](#주문-상태)  |
주문 유형과 상태에 대한 부분을 따로 분리해주셨네요.

한눈에 어떤 상태가 있는지, 어떤 유형이 있는지 알아볼 수 있어 좋네요 👍

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 비속어   | Profanity     | 부적절한 단어 또는 비속어            |
비속어의 경우 메뉴에서도 다루는 개념인 것 같아요.

상품 하위에만 정리되어 있으면 메뉴와 관련된 용어를 살펴볼 때 비속어와 관련된 부분을 놓칠 수 있지 않을까요?
상품 등록 시 이름에 비속어가 들어올 수 없다고 표시하고 주문 유형 상태처럼 비속어에 대한 부분을 별도로 정리해도 좋을 것 같습니다.

그리고 현재 "욕설"이라는 한 단어로 설명이 이루어지고 있는데요 욕설 분류를 위해 현재 API를 호출하고 있으니 해당 API를 사용한다는 부분이나 어떤 부분을 비속어로 분류할지 추가로 조금 더 설명이 들어가면 좋을 것 같네요.

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 손님     | Table Guest     | 테이블에 앉은 손님                     |
OrderTable의 경우 코드 레벨로 봤을 때 손님 자체에 대한 정보를 가지고 있진 않은 것 같아요.

손님 자체에 대한 설명보다는 테이블이 가지는 numberOfGuests에 대한 부분에 대해 어떤 목적으로 사용하는 값인지, 언제 바뀌는지 등의 용어 정리가 이루어지면 어떨까요?

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 주문 완료 | Completed    | 주문 완료 상태            |
유형과 상태에 대한 용어를 보아도 배달, 포장, 매장 유형 별로 어떤 상태 변경 흐름을 가지는지 한눈에 알기 어려운 것 같아요.

```
- 배달
  - 대기 -> 접수 -> 배달 중 -> 배달 완료 -> 주문 완료
```

불필요할수도 있겠지만 배달과 관련된 도메인을 모르는 사람이 용어를 보고 빠르게 이해할 수 있도록 위와같이 유형 별 상태 변경 흐름을 적어주셔도 좋을 것 같네요.

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 빈 테이블  | Empty Table     | 손님이 없는 테이블                     |
빈 테이블이라는 용어를 별도로 정리해주셔서 오히려 테이블과 빈 테이블이라는 별도의 개념이 존재하는건가? 하고 생각이 들었네요.

저는 테이블이 empty라는 속성을 가지고 해당 속성값이 변경될 수 있음을 표시해주는게 조금 더 자연스러운 것 같아요. 물론 오히려 개발자에게 친숙한 표현일 수 있고 정리하는 사람의 취향일 것 같아서 가볍게 흘려들어주셔도 됩니다.

다른 곳에도 유사한 부분이 많은데 별도로 코멘트를 남기지는 않을게요.

2022-09-09 11:16 UTC, kyucumber commented on README.md
> +| 메뉴 가격    | Menu Price            | 메뉴에 표시될 가격             |
위에도 적었지만 비속어와 관련된 부분이 빠져있는데 메뉴와 관련되어 정리된 부분만 읽더라도 메뉴의 이름이 비속어가 될 수 없음을 인지할수 있으면 좋을 것 같아요.

2022-09-10 13:39 UTC, gmoon92 commented on README.md
> +| 비속어   | Profanity     | 부적절한 단어 또는 비속어            |
메뉴 도메인의 비속어 용어 정의를 누락된것 같습니다 😅
비속어 부분도 별도의 항목을 만들어서 정리하는게 좋을 것 같네요 !

도메인 용어는 이벤트 스토밍과 모델링을 하기 전에 개발 전에 도메인을 이해할 수 있는 표준 단어를 정의한다고 생각했습니다. 최대한 소스를 참고하지 않고 작성된 요구사항을 참고하여 작성했습니다!

제가 정의한 도메인 용어 사전 이해 관계자들간의 의사 소통과 도움을 줄 수 있는 표준, 헷갈릴 수 있는 의미가 되는 단어를 정의하는게 좋다고 생각했습니다. 표준을 정의하는것이 도메인에 대해 이야기를 할때 같은 생각을 할 수 있도록 하기 위함이라 생각합니다!

비즈니스 요구사항이 달라진다고, 도메인 용어 사전이 달라진다? 표준을 정의했는데 기능 구현에 따라 그 의미가 달라지는게 맞는건가? 라는 생각이 듭니다! 🤔 물론 그 경계를 지키면서 정의하면 좋겠지만, 쉽지만은 않네요.

비속어 검증 API에 대한 설명 부분은 기능 요구사항 부분에 정의하는게 좋다 생각합니다 😀

이 부분에 대해서 규남님의 생각은 다르신건가요?🙂

2022-09-10 13:46 UTC, gmoon92 commented on README.md
> +| 주문 완료 | Completed    | 주문 완료 상태            |
이 부분은 도메인 용어 사전에 정의하는 것보단 요구사항 또는 모델링 하는 부분에서 정의하는게 좋다고 생각합니다!

도메인 용어 사전에 데이터 플로우에 대한 부분을 정의하는게 맞는지 고민이 되네요 🙂

2022-09-10 14:16 UTC, gmoon92 commented
안녕하세요 규남님 ! 😁

이번 용어 사전 만들기 과제를 통해 고민된 부분이 있었습니다.

이번 미션엔 개발자 뿐만아니라 프로젝트에 참여할 수 있는 모든 도메인 전문가들도 이해할 수 있는 표준 단어를 정의하기 위해, 최대한 기능적인 부분이나 개발 친화적인 단어 또는 데이터 플로우에 대한 부분은 정의하지 않으려 경계를 지키며 작성했습니다.

제 생각엔 데이터 플로우에 대한 부분은 기능 요구사항 또는 도메인 모델링 단계에서 작성해야 되는게 맞지 않을까 생각합니다. 

도메인 용어란 표준으로 정의를 하는 것이라 생각합니다. 
저의 도메인 용어에 대한 기준은 다음과 같습니다.

- 이중적인 단어로 해석될 수 있는가?
- 영어 단어로 정의하기엔 여러 단어가 나올 수 있는 단어인가?
  - ex) 금액 Price, Money
- 도메인에 대한 이해를 도울 수 있는 단어인가?

비즈니스 요구사항은 언제든 달라질 수 있다. 프로덕트 기능 로직 부분을 도메인 용어 사전에 직간접적으로 정의하는게 맞는건가?
맞다면, 요구사항이 바뀌면 용어 사전도 달라진다는 의미인데 표준 정의한다는게 맞는건가? 🤔

도메인 용어 사전를 정의하는 목적은 요구사항을 쉽게 이해하거나, 표준이 되는 용어 사용으로 빠르고 직관적인 의사소통이 되기 위함이라 생각합니다. 무엇보다 도메인을 바라볼 때 모든 이해관계자가 같은 생각을 하기 위한 목적으로 표준 단어를 정의한다라고 생각합니다.

규남님만의 도메인 용어에 대한 정의와 기준이 혹시 저와 다를까요 ?🤔
도메인 용어 사전을 작성하실 때, 어떤 기준으로 작성하시는지 궁금합니다! 🙂

2022-09-11 03:55 UTC, kyucumber commented on README.md
> +| 비속어   | Profanity     | 부적절한 단어 또는 비속어            |
> 비속어 검증 API에 대한 설명 부분은 기능 요구사항 부분에 정의하는게 좋다 생각합니다 😀

비속어 검증 API에 대한 설명을 용어사전에 넣으면 좋겠다라는 의미로 코멘트를 남긴건 아니었어요. 비속어 분류에 대한 기준을 대략적으로나마 용어사전에 표현하면 좋겠다라는 의도였습니다.
이해 관계자들간에 의사 소통을 할 때 비속어 분류 기준을 모르면 의사소통에 어려움이 있지 않을까요?

말씀하신 것 처럼 요구사항에 잘 정리하신 다음에 용어사전에 해당 부분에 대한 링크를 남기거나 해도 좋을 것 같습니다.

2022-09-11 03:58 UTC, kyucumber commented on README.md
> +| 주문 완료 | Completed    | 주문 완료 상태            |
용어사전은 도메인에 대한 이해를 돕기 위한거라고 생각하는데요, 저는 유형별 주문들의 상태 변경 흐름이 표현되면 해당 유형별 주문을 좀 더 잘 이해할 수 있을거라고 생각했습니다.

저는 유형별 주문(배달, 포장, 매장)의 이해를 돕기 위해 있으면 좋겠다는 의견인데요 사람마다 기준은 다를 수 있으므로 넘어가셔도 좋을 듯 합니다.

2022-09-11 04:02 UTC, kyucumber commented
> 제 생각엔 데이터 플로우에 대한 부분은 기능 요구사항 또는 도메인 모델링 단계에서 작성해야 되는게 맞지 않을까 생각합니다.

만약 데이터 파이프라인의 진행 플로우나 이런 부분이라면 용어사전에 포함되는게 이상하겠지만 유형별 주문에 대한 이해를 돕기 위해 제가 코멘트 남긴 정도는 용어사전에 정의되어도 무방할것 같다고 생각합니다.

> 규남님만의 도메인 용어에 대한 정의와 기준이 혹시 저와 다를까요 ?🤔

위에 남겨주신 기준과 크게 다르지는 않습니다. 저는 주문 내에 존재하는 주문 유형들에 대한 이해를 돕기 위해 있으면 어떨까 하는 의견을 드린거에요.

요구사항이든 용어사전 정리든 정답이 정해진 부분은 아니라서 동의되지 않으시면 반영하지 않으셔도 될 것 같아요 😄

2022-09-11 04:03 UTC, kyucumber approved these changes
안녕하세요

피드백 잘 반영해주셨네요, 다음 단계 진행을 위해 머지할게요.

2022-09-11 04:03 UTC, merged