Step2 - 모델링 하기
next-step/ddd-strategic-design pull request #18
Opened 2020-02-18 05:28 UTC by HaJaeKwon

1. 요구사항과 용어사전에서 사용한 단어, 문장들을 사용하고자 했습니다.
2. 아래와 같이 표현해야 할 것이 많은 경우 상위 개념으로 추상화하여 최대한 간단하게 표현하고자 했습니다.
> RoutingService는 RouteSpecification을 만족하는 Plan 찾는다.

2020-02-18 13:11 UTC, sihoony requested changes
고생하셨습니다~^^
잘 작성해 주셨으며 몇가지 코멘트를 남겼습니다.
궁금하신점이 있으시면 코멘트나 DM주세요~^^

2020-02-18 13:11 UTC, sihoony commented on README.md
> +  - 여러개의 메뉴들을 메뉴 그룹으로 등록한다.
메뉴들을 어떤 조건에 의해서 메뉴그룹으로 등록할 수 있을까?
등록할 수 있다면 관계 도출을 해보는건 어떨까요? 이를 통해 어떤 메시지를 주고 받는지 알 수 있을꺼에요~^^

2020-02-18 13:11 UTC, sihoony commented on README.md
> + - 주문 테이블에 방문 손님 수를 방문 손님 수 변경 조건에 따라 변경한다.
조건을 용어사전에 등록하는게 좋을지 혹은 모델링에서 정의하는게 좋을지 생각해보시면 좋을것 같습니다~^^

2020-02-19 19:25 UTC, HaJaeKwon commented on README.md
>  ## 모델링
속성값 a6ed6ac62b76513e0a56ba3fbde1de736ca9503f 커밋에 추가하였습니다.
연관관계 e0613e10fa3e6ec15544ac66e7ffeb1b32e283eb 커밋에 추가하였습니다.

2020-02-19 19:26 UTC, HaJaeKwon commented on README.md
> +  - 메뉴 이름과 메뉴 가격 정책에 따른 메뉴 가격을 메뉴로 등록한다.
조건, 정책에 관한 내용들은 모델링을 보고 개발해본다는 관점에서 그 내용을 모델링이 포함시켰습니다.
93d5c5d807606a6be5241d2922d600d80f26198d

2020-02-19 19:26 UTC, HaJaeKwon commented on README.md
> + - 주문 테이블에 방문 손님 수를 방문 손님 수 변경 조건에 따라 변경한다.
조건, 정책에 관한 내용들은 모델링을 보고 개발해본다는 관점에서 그 내용을 모델링이 포함시켰습니다.
93d5c5d

2020-02-19 19:27 UTC, HaJaeKwon commented on README.md
> +  - 여러개의 메뉴들을 메뉴 그룹으로 등록한다.
메뉴와 메뉴 그룹의 관계를 e0613e10fa3e6ec15544ac66e7ffeb1b32e283eb 커밋에 추가하였습니다.

2020-02-20 04:42 UTC, sihoony approved these changes
피드백에 대해서 잘 반영해 주셨으며 리뷰드릴께 없네요~^^
고생하셨습니다.
다음 미션을 위해서 Merge하겠습니다.

2020-02-20 04:42 UTC, merged