1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #180
Opened 2022-09-09 15:57 UTC by wenodev

안녕하세요 동철님!! 반갑습니다!!
명절은 잘 보내고 계신가요?ㅎㅎ

용어 사전 확인해 보시고 사소한 의견이라도 주시면 감사하겠습니다 ㅎㅎ
감사합니다!!

2022-09-11 16:33 UTC, sah3122 requested changes
용어 사전 정의 잘해주셨습니다 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요 ! 
리뷰가 많이 늦어져 죄송합니다 🙏

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +- 코드화 될 수 있는 단어들을 정리한다.
기준 명시 좋네요 ㅎㅎ 👍

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +| 주문자 | customer | 상품을 주문하는 사람 |
코드에서는 guest 라는 표현을 사용하는데, customer 라고 정의해주신건 의도적인걸까요 ㅎㅎ ?

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +| 주문 상태 | order status | 주문의 단계|
주문 상태 설명에 대기, 수락, 준비완료... 와 같이 어떤 상태가 있는지 남겨두는것도 좋을것 같아요 😄

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +| 변경하다 | change | 변경하다. |
공통적으로 사용하는 용어에 대한 정의 일까요 ? 
개인적으로 등록, 조회, 변경과 같은 용어를 용어사전에 정리하는것이 크게 의미를 가지는것 같지는 않아요 !

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +| 상품 | product | 메뉴 프로덕트가 사용하는 데이터 |
```suggestion
| 상품 | product | 메뉴 상품이 사용하는 데이터 |
```
정의한 용어를 사용해보세요 😄 
추가로 상품의 정의가 메뉴 상품이 사용하는 데이터라는 정의는 자연스럽지가 않은것 같습니다 🙏 
다른 용어도 한번 확인해보세요 !

2022-09-11 16:33 UTC, sah3122 commented on docs/용어사전.md
> +| 치우다 | clear | 테이블을 치우다. |
clear 와 같은 용어는 일반적으로 많이 사용되는 용어라고 생각해요. 
특정 바운디드 컨텍스트에서 정확한 의미를 가질수 있을것 같은데, 바운디드 컨텍스트를 기준으로 정의해보는것도 좋을것 같아요 !

2022-09-13 13:26 UTC, wenodev commented on docs/용어사전.md
> +- 코드화 될 수 있는 단어들을 정리한다.
감사합니다!

2022-09-13 13:27 UTC, wenodev commented on docs/용어사전.md
> +| 주문자 | customer | 상품을 주문하는 사람 |
코드는 리팩토링 될 수 있다고 가정하고 용어사전에 초점을 맞추어 만들다 보니 customer라는 단어를 떠올리게 되었습니다.
하지만 다시 확인해보니 guest라는 단어가 더 적합한 것 같아 guest로 하려고 합니다!

2022-09-13 13:28 UTC, wenodev commented on docs/용어사전.md
> +| 주문 상태 | order status | 주문의 단계|
넵!! 좋습니다!!

2022-09-13 13:28 UTC, wenodev commented on docs/용어사전.md
> +| 변경하다 | change | 변경하다. |
네네!! 용어사전 만들면서 많이 고민했던 부분인데요!!
일반 적으로 사용하는 단어는 일반 사전에 정의가 되어 있기 때문에 도메인의 용어 사전에 적는것은 불필요 한 것 같아요!!

2022-09-13 13:29 UTC, wenodev commented on docs/용어사전.md
> +| 상품 | product | 메뉴 프로덕트가 사용하는 데이터 |
메뉴와 프로덕트를 다른 바운디드 컨텍스트로 보고 있기 때문에 상품 정의에 메뉴를 제거해보겠습니다!!

2022-09-13 13:29 UTC, wenodev commented on docs/용어사전.md
> +| 치우다 | clear | 테이블을 치우다. |
바운디드컨텍스트 별로 용어사전이 필요하다는 생각도 드네요?!

2022-09-14 13:05 UTC, sah3122 requested changes
피드백 반영 잘해주셨습니다 👍 
조금더 경험해보았으면 하는 부분이 있어 코멘트 남겨두었어요. 
확인 부탁드립니다 🙏

2022-09-14 13:05 UTC, sah3122 commented on docs/용어사전.md
> +- 테이블
정의해주신 Bounded Context 기준으로 용어를 분리해보는것도 도전해보세요 😄 

앞선 피드백에서 남겨드린것 처럼 유비쿼터스 언어는 특정 Bounded Context 내부에서 완전한 의미를 가지기 때문에 개인적으로는 매번 Bounded Context를 기준으로 용어사전 정리하고 있습니다.  ㅎㅎ

2022-09-14 13:05 UTC, sah3122 commented on docs/용어사전.md
> +| 메뉴 목록 | menu group | 메뉴의 집합 |
`메뉴 목록`에 대한 정의가 자연스럽지 않은것 같아요 😄

2022-09-14 13:05 UTC, sah3122 commented on docs/용어사전.md
> +| 배달 완료 | delivered | (배달) 주문을 배달 대행사가 배달 주소지까지 배달한 주문 상태. |
용어 설명에 주문 타입을 나타내기 보다 `배달 주문`에 관한 용어집을 별도로 관리하는건 어떨까요 ? 
예시는 배달 주문으로 남겨드렸지만 특정 주문 타입에서만 사용되는 용어들이 있다면 주문타입별 용어사전을 관리하는것도 좋은 방법이 될것 같습니다 😄

2022-09-15 23:15 UTC, wenodev commented on docs/용어사전.md
> +- 테이블
네 감사합니다!

지금 도메인 주도 설계 구현을 읽고 있는데
> 경계가 되는 단어가 있으면 Bounded Context의 신호이다.

이런 내용이 나오더라구요.

그렇다면 자연스럽게 용어 사전도 Bounded Context로 나눈는 것이 좋다고 생각합니다

2022-09-15 23:32 UTC, wenodev commented on docs/용어사전.md
> +| 메뉴 목록 | menu group | 메뉴의 집합 |
변경해 보겠습니다!!

2022-09-15 23:32 UTC, wenodev commented on docs/용어사전.md
> +| 배달 완료 | delivered | (배달) 주문을 배달 대행사가 배달 주소지까지 배달한 주문 상태. |
네 별도로 분리해봐야 겠네요 ㅎㅎ

2022-09-16 08:59 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
다음 미션도 기대할게요! ㅎㅎ

2022-09-16 08:59 UTC, sah3122 commented on docs/용어사전.md
> +| 호출하다 | call | 배달 주문이 접수되면 배달 대행사를 호출하다 |
배달 주문 용어에 포함되어도 될것 같아요 😄

2022-09-16 08:59 UTC, sah3122 commented on docs/용어사전.md
> +### 포장 주문
피드백 반영 잘해주셨습니다 👍

2022-09-16 08:59 UTC, merged