1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #181
Opened 2022-09-10 03:43 UTC by iljun

안녕하세요 재석님
TDD 과정에서 뵙고 이번에 다시 뵙네요~
이번에도 잘 부탁드립니다~

2022-09-10 06:25 UTC, seok-2-o requested changes
일준님. 안녕하세요
다시 뵙게 되어 대단히 기쁩니다 :)

용어사전 잘 정의해주셨네요. 다만 요구사항에 비해 아직 도출되지 않은 용어들이 많은것 같아요.
교육 과정이니만큼 최대한 많은 용어를 찾아보고 불필요한걸 삭제해보는건 어떨까요?

미션 진행하면서 저와 의견이 다르거나 궁금한점이 있다면 편하게 연락주시길 바라요.

밝고, 풍성한 보름달 처럼 마음속에 행복이 가득한 한가위 보내시길 바랍니다. 🌕

2022-09-10 06:25 UTC, seok-2-o commented on README.md
> +| 한글명      | 영문명             | 설명                                                                         |
아직 요구사항에 비해 많은 부분이 도출되지 않은것 같아요.

예를들어 `비속어` 는 어떻게 정의할 수 있을까요?

2022-09-10 06:25 UTC, seok-2-o commented on README.md
> +| 주문 완료    | COMPLETED       | 손님이 주문한 메뉴를 배달하거나, 전달하거나, 식사를 마친 상태                                        |
`손님` 이라는 용어가 반복적으로 사용되는데 따로 정의한다면 어떤 장/단점이 있을까요?

2022-09-11 07:44 UTC, iljun commented
고민을 하다보니 작성되어있던 코드를 그대로 옮겨온듯한 불편함이 있네요...
요구 사항을 조금 더 그룹화를 해보았고, `비속어` `손님` 과 같은 놓친 용어들도 정리해 보았습니다 🙇

2022-09-11 07:44 UTC, iljun commented on README.md
> +| 한글명      | 영문명             | 설명                                                                         |
무의식중 눈에 보이는 Class만 용어 정리를 진행해버렸네요...
`비속어`도 용어 정리를 해보겠습니다

2022-09-11 07:47 UTC, iljun commented on README.md
> +| 주문 완료    | COMPLETED       | 손님이 주문한 메뉴를 배달하거나, 전달하거나, 식사를 마친 상태                                        |
손님의 역할이 크지 않아 놓쳐버렸네요
손님을 따로 정의한다면 이후에 `BOUNDED CONTEXT`를 나누는 연습을 할 때 도움이 될 수 있을것같네요
또 현업 프로젝트에서 이 손님을 구분하는게 굉장히 중요한 작업이라고 생각이 되구요 
좋은 피드백 감사합니다~~ 🙇

2022-09-11 08:11 UTC, seok-2-o requested changes
쉽지 않은 결정이셨을 것 같은데 새롭게 용어사전을 정의해주셨네요 👍 

지금도 충분히 잘해주셨지만 조금 더 고민해보면 좋을 것 같으부분이 있어 코멘트로 남겨놓았습니다. 확인 후 의견 주시면 좋을 것 같아요.

2022-09-11 08:11 UTC, seok-2-o commented on README.md
> +| 메뉴 그룹 번호 | MenuGroup id   | 메뉴 그룹의 번호로 자동생성이되며, 각 메뉴 그룹의 고유한 값이다   |
상세 구현을 용어사전에 정의할 필요가 있을까요?

용어사전의 이해당사자는 누구일까요?

2022-09-11 08:11 UTC, seok-2-o commented on README.md
> +### Purgomalum
공통으로 쓰는 용어를 별도로 분리해주셨네요.

2022-09-11 08:11 UTC, seok-2-o commented on README.md
> +| 매장 주문 완료 | Complete EatIn Order | 손님이 식사를 마친 상태로 OrderTable을 비어있는 상태로 변경한다                                                                                                           |
각 주문 타입을 다른 컨텍스트로 보고 분리해주셨네요 저는 좋은 방법이라고 생각합니다 💯

2022-09-11 08:11 UTC, seok-2-o commented on README.md
> +| 비노출 메뉴 | hide Menu      | 비노출되어 있는 메뉴                                                                 |
키친포스에서 비노출이 가지는 의미는 무엇일까요?

2022-09-11 08:11 UTC, seok-2-o commented on README.md
> +### MenuGroup
지금도 충분히 잘 작성해주셨지만, 용어 사전에 상세 구현방식이 많이 작성되어 있는것 같아요.
이는 모델링과정에서 자세히 기술하는게 좋지 않을까요?

물론 제가 드리는 의견이 정답은 아니므로, 페어분과 함께 고민해보시면 좋을 것 같아요.

2022-09-12 06:28 UTC, iljun commented on README.md
> +| 메뉴 그룹 번호 | MenuGroup id   | 메뉴 그룹의 번호로 자동생성이되며, 각 메뉴 그룹의 고유한 값이다   |
용어 사전은 같이 일하는 모든 직군의 사람이어야하는데 개발자 입장에서만 작성했군요...

2022-09-12 06:28 UTC, iljun commented on README.md
> +### Purgomalum
🙇

2022-09-12 06:28 UTC, iljun commented on README.md
> +| 매장 주문 완료 | Complete EatIn Order | 손님이 식사를 마친 상태로 OrderTable을 비어있는 상태로 변경한다                                                                                                           |
👍

2022-09-12 06:29 UTC, iljun commented on README.md
> +### MenuGroup
제가 작성한건 용어사전보다는 기술문서와 가깝다는 생각이 드네요 
말씀주신대로 피드백 적용해보겠습니다~

2022-09-12 06:44 UTC, seok-2-o approved these changes
피드백 반영잘해주셨습니다 👍 

함께 고민해보고 싶은 부분이 있어 코멘트로 남겨놓았습니다.
일준님 의견 들려주시면 좋을 것 같아요 :)

이어서 다음 미션 진행해주세요.

2022-09-12 06:44 UTC, seok-2-o commented on README.md
> +| 비노출 메뉴 | hide Menu      | 품절 등의 다양한 이유로 판매하지 못하는 메뉴                    |
품절에 대한 내용은 주어진 코드와 요구사항에 나타나지 않는데 어떻게 도출하신 키워드일까요?

2022-09-12 06:44 UTC, seok-2-o commented on README.md
> +| 배달 완료    | Delivered Delivery Order  | 배달원이 손님에게 배달완료 한 상태                                   |
주어를 배달원으로 잡으신 이유가 있으신가요?

2022-09-12 06:44 UTC, seok-2-o commented on README.md
> +| 배달 주소    | Delivery Address          | 배달해야할 손님의 주소                                          |
잘못된 부분은 아니고 
개인적으로 어색함이 느껴져 의견이 궁금하여 코멘트 남깁니다.
`배달 받을 / 배달해야할` 어떤 차이가 있을까요?

편하게 의견 주시면 좋을 것 같아요

2022-09-12 06:44 UTC, seok-2-o commented on README.md
> +### MenuGroup
용어사전에서 어느정도 정의 해야할지는 항상 고민되는 부분인 것 같아요.
정책과 모델 어렵네요 😢

2022-09-12 06:44 UTC, merged

2022-09-12 06:50 UTC, iljun commented on README.md
> +| 비노출 메뉴 | hide Menu      | 품절 등의 다양한 이유로 판매하지 못하는 메뉴                    |
주문시에는 display된 메뉴만 주문이 가능하다는 코드를 보고 위와 같은 요구사항을 도출했습니다
판매하던 menu를 hide하는 경우가 어떤 케이스가 있을지 고민해보니 메뉴가 판매 불가능한 상황이나 판매가 종료된 메뉴를 hide하여 주문이 불가능하게 한다는 의도로 이해했습니다
물론 code와 요구사항만으로는 품절이란 키워드를 도출하는게 어색할 수 있으나 품절도 메뉴를 판매하지 못하는 한가지의 이유가 될 수 있어 작성해 보았습니다

2022-09-12 06:51 UTC, iljun commented on README.md
> +| 배달 완료    | Delivered Delivery Order  | 배달원이 손님에게 배달완료 한 상태                                   |
주문의 상태를 변경하고 표시하는데 가장 중요한 역할이라 주어를 배달원으로 설정했습니다

2022-09-12 06:54 UTC, iljun commented on README.md
> +| 배달 주소    | Delivery Address          | 배달해야할 손님의 주소                                          |
음... 지금 드는 생각은 용어사전을 작성할때의 관점이라고 생각이 드네요 
키친포스의 관점으로 작성한다면 `배달 받을 손님의 주소`가 적절해보이네요
`배달해야할 손님의 주소`는 베달원의 입장에서 작성된 용어사전인것같네요

2022-09-12 06:55 UTC, iljun commented on README.md
> +| 배달 완료    | Delivered Delivery Order  | 배달원이 손님에게 배달완료 한 상태                                   |
아래와 comment를 보니 키친포스의 관점으로 작성하는게 적절해보이네요...