1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #190
Opened 2022-09-13 14:27 UTC by yunbchae

안녕하세요 리뷰어님! DDD 세레나데 수강생 채윤병입니다 😃 

이번 미션은 최은기(@choieungi)님과 페어로, 각자 용어 사전 정리 후, 서로 작성한 내용 리뷰하면서 통합하는 과정으로 진행했습니다.

페어 리뷰 진행하면서 고민이 됐던 부분 몇가지 문의드리고 싶습니다.

1. 용어 사전 정의 기준
저는 용어 사전이 요구사항의 내용 중 문맥에 따라 혼동의 여지가 있는 용어를 정의하는데 목적이 있다고 생각해서, 요구사항에 나오지 않는 용어는 정리하지 않았습니다. 반면에 은기님은 요구사항에 정의되지 않았더라도 `상품 가격 변경 정책`이나 `메뉴 가격 정책`과 같이 요구사항을 뒷받침 할 수 있는 용어를 함께 정리를 하셨더라구요. 리뷰 진행하면서 요구사항에 명시 되지 않았어도 도메인을 이해하는데 도움이 되는 용어라 생각해 용어 사전에 포함하게되었는데, 리뷰어님은 어떤 기준으로 용어 사전을 정의하시는지 궁금합니다.

2. 동일한 용어 재정의
또 한가지 고민은 동일한 용어를 문맥에 따라 재정의 할 필요가 있는지였어요. 은기님은 `메뉴` 용어 사전에 `메뉴 그룹`을, `주문` 용어 사전에 `주문 테이블`을 재정의 하셨는데, 리뷰 진행하면서 문맥에 의해 정의가 달라지는 용어가 아니라고 판단해서 재정의 하지 않기로 했습니다. 리뷰어님 의견은 어떠실까요?

답변 주시면 감사하겠습니다 🙇🏻‍♂️

2022-09-14 12:12 UTC, starkim06 requested changes
안녕하세요!!

용어사전 너무 잘 정리해주셨네요!!
몇가지 코멘트 남겨두었으니 확인 부탁드립니다!!
질문 주신 내용들에 대해서는 코멘트로 달아두었습니다!

2022-09-14 12:12 UTC, starkim06 commented on README.md
> +| 상품 가격 변경 정책 | changing price policy | 변경된 가격의 상품을 구성하는 메뉴 중에서, 메뉴의 가격이 구성된 상품의 가격보다 크면 메뉴가 가려진다. |                |
용어 사전에 정리하는 단어를 `저는 용어 사전이 요구사항의 내용 중 문맥에 따라 혼동의 여지가 있는 용어를 정의` 라고 해주셨는데요!
상품 가격 변경 정책 이라는건 문맥에 따라 어떤 혼동의 여지가 있다고 생각하셨을까요?

2022-09-14 12:12 UTC, starkim06 commented on README.md
> +| 상품          | product               | 손님에게 제공되는 음식을 뜻한다.                                         | 후라이드 치킨, 양념 치킨 |
예시 작성 👍

2022-09-14 12:12 UTC, starkim06 commented on README.md
> +| 방문한 손님 | guest             | 주문 테이블을 사용중인 손님을 뜻한다.                       |     |
주문 테이블의 경우는 `방문한 손님` 자체 보다는 `방문한 손님의 수`에 대해서 정리하는건 어떨까 하는 생각이 들어요.
작성된 요구사항에서 주문 테이블에서는 손님 자체에 대한 정보는 덜 중요하다고 느껴지네요!

2022-09-14 12:12 UTC, starkim06 commented on README.md
> +| 주문 완료         | complete order        | 주문이 정상적으로 완료되었음을 뜻한다.                 |     |
이 부분들이 모두 `주문 상태` 로 볼 수 있을것 같아요. 
위에서 주문 유형을 묶어주신것 처럼 주문 상태도 묶어서 표현해주시면 어떨까요?
`주문 상태` 를 별도로 용어 사전에 적어주는 것도 읽기 편할것 같다는 생각이 드네요 =)

2022-09-14 12:21 UTC, starkim06 commented
```용어 사전 정의 기준```
저는 용어 사전을 다음과 같은 기준으로 정의하는 것 같아요.
- 프로젝트에 참여하고 있는 모든 구성원들이 사용하는 Ubiquitous Language(보편 언어)에 대해서
- (개인적으로 프로젝트를 할 때는) 다른 구성원들과 한글로 말하는 단어이지만, 그 단어가 영어로는 간단하지 않을 때

말씀 주신 여러 정책들에 대해서는 모델링을 할 때나 인수조건을 정할때 정리하는게 어떨까 생각합니다.

```동일한 용어 재정의```
~~지금의 미션과 같이 작은 프로젝트에서는 제 생각에도 문맥에 의해 정의가 크게 달라지는 용어가 아니라고 생각해서 재정의 하지 않는 것도 좋다고 생각됩니다.
하지만 이 부분은 프로젝트의 크기가 커질수록, 도메인에 대한 이해가 깊어질수록 언제든지 변할 수 있는 부분이라고 생각합니다.~~
기존에 말씀 드린 부분은 하나의 바운디드 컨텍스트에 정의되어 있는 하나의 용어 사전이라고 생각해서 드린 답변이였어요.
생각해보니 지금 바운디드 컨텍스트를 나눈 상태로 용어 사전이 작성되어 있네요. 
이런 경우는 말씀 주신 것 처럼 각각이 별도의 바운디드 컨텍스트, 용어사전이라서 용어를 재정의 해주는편이 더 좋을 것 같네요!

윤병님 생각과 다른 부분이 있으시거나 더 이야기 하면 좋을 부분들이 있으시면 언제든지 편하게 DM 주세요 =) 같이 이야기 하다보면 더 좋은 결과가 나오지 않을까요?!!

2022-09-14 12:22 UTC, merged

2022-09-15 10:04 UTC, yunbchae commented on README.md
> +| 상품 가격 변경 정책 | changing price policy | 변경된 가격의 상품을 구성하는 메뉴 중에서, 메뉴의 가격이 구성된 상품의 가격보다 크면 메뉴가 가려진다. |                |
`상품 가격 변경 정책`은 초기 작성 시에, 혼동의 여지가 있을거라 생각해서 넣은 용어는 아니었어요!

페어 리뷰 중에 페어분이 해당 용어를 용어 사전에 포함하셨고, 요구 사항에 드러나는 용어는 아니지만 요구 사항을 뒷받침 해줄 수 있는 용어라고 생각해서 추가했었습니다 :)

아래 코멘트 주신 것 처럼 모델링 시에 정리해도 괜찮을 것 같아요~!

2022-09-15 10:04 UTC, yunbchae commented on README.md
> +| 방문한 손님 | guest             | 주문 테이블을 사용중인 손님을 뜻한다.                       |     |
확실히 그렇게 보이네요! 수정해서 반영하겠습니다 :)