1단계 - 용어사전 만들기
next-step/ddd-strategic-design pull request #193
Opened 2022-09-14 14:37 UTC by ChoiEungi

안녕하세요!! 이번 첫번쨰 미션 제출드립니다! 이번 미션은 채윤병님과 페어로 진행했습니다! 

저희가 진행한 고민은 다음과 같습니다.

1. 용어 사전 정의 기준
용어 사전을 작성할 때 요구사항의 내용에 나와있는 것을 작성할 지 말지에 대해 윤병님과 이야기를 진행했는데요. 저는 도메인에서 중요하게 작용하는 정책은 요구사항에 나와있는 내용이 아니더라도 작성을 진행했습니다. 그 예로, 상품 가격 변경 정책이나 메뉴 가격 변경 정책들을 작성했습니다. 이 부분에 대해서 **요구사항에는 명시되지 않았지만, 도메인을 이해하는데 도움이 되는 용어**를 포함하는 부분에 대한 리뷰어님의 의견을 듣고 싶습니다.

2. 용어 재정의
저는 `메뉴`에 `메뉴그룹`을 재정의 함으로, 메뉴그룹이 메뉴를 구분하기 위함을 나타내려 했고, `주문`에 `주문테이블`을 재정의해 주문에는 매장 주문에서 주문테이블의 필요성을 나타냈습니다. 이에 대해서, 재정의하는 것에 대한 리뷰어님의 의견이 궁금합니다.

2022-09-15 16:36 UTC, kyucumber requested changes
안녕하세요 리뷰가 조금 늦어졌네요 😭 

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-09-15 16:36 UTC, kyucumber commented on README.md
>  ## 용어 사전
저희가 진행한 고민은 다음과 같습니다.

> 용어 사전 정의 기준

```
용어 사전을 작성할 때 요구사항의 내용에 나와있는 것을 작성할 지 말지에 대해 윤병님과 이야기를 진행했는데요. 저는 도메인에서 중요하게 작용하는 정책은 요구사항에 나와있는 내용이 아니더라도 작성을 진행했습니다. 그 예로, 상품 가격 변경 정책이나 메뉴 가격 변경 정책들을 작성했습니다. 이 부분에 대해서 요구사항에는 명시되지 않았지만, 도메인을 이해하는데 도움이 되는 용어를 포함하는 부분에 대한 리뷰어님의 의견을 듣고 싶습니다.
```

도메인에서 중요하게 작용하는 정책들 중 일부는 용어 사전에 정리한 개념을 이해하는데 도움을 줄 수 있을 것 같아요. 따라서 필요에 따라 용어 사전에 이해에 도움을 줄 수 있는 정책 또한 포함할 수 있다고 생각합니다.

다만 용어 사전이 너무 방대해 질 수 있으므로 용어 자체의 이해를 돕는 데 필요한 개념이 아니라면 요구사항에서 다루는게 좋을 것 같아요 용어 사전에 너무 많은 내용이 들어갈 수 있을 것 같거든요.

> 용어 재정의

```
저는 메뉴에 메뉴그룹을 재정의 함으로, 메뉴그룹이 메뉴를 구분하기 위함을 나타내려 했고, 주문에 주문테이블을 재정의해 주문에는 매장 주문에서 주문테이블의 필요성을 나타냈습니다. 이에 대해서, 재정의하는 것에 대한 리뷰어님의 의견이 궁금합니다.
```

메뉴 하위에 메뉴 그룹, 주문 하위에 주문 테이블에 대한 용어를 재정의했단 말씀이신가요? 잘 이해하지 못했는데 이 부분은 DM으로 다시 말씀해주시면 답변해드리도록 하겠습니다.

2022-09-15 16:36 UTC, kyucumber commented on README.md
> +| 비속어      | profanity         | 욕설 등, 메뉴 이름에 들어가기 적절하지 않은 단어를 뜻한다.            |              |
비속어가 상품, 메뉴에 중복적으로 정리되고 있네요.

이렇게 여러 도메인에서 사용하는 용어의 경우 별도의 항목으로 빼서 정리해도 좋을 것 같아요.

2022-09-15 16:36 UTC, kyucumber commented on README.md
> +| 주문 완료         | complete order        | 주문이 정상적으로 완료되었음을 뜻한다.                 |     |
주문이 가질 수 있는 상태를 잘 정리해주신 것 같아요.

다만 설명을 자세히 읽지 않으면 주문이 가지는 상태에 대한 이야기인지 어떤 행위에 대한 부분을 설명하는건지 헷갈릴 수 있을 것 같아요.

위의 주문 유형의 경우 앞에 접두사로 주문 유형이라는 설명이 들어가 쉽게 구분할 수 있었는데 주문 상태에 대해서도 추가적인 설명이 들어가면 좋을 것 같네요.

2022-09-15 16:36 UTC, kyucumber commented on README.md
> +### 상품
현재 도메인 별로 도출될 수 있는 하위 용어들에 대해서 잘 정리해주신  것 같습니다.

용어를 정리하시다보면 바운디드 컨텍스트가 어떻게 나뉘겠구나 라는 부분이 대략적으로 파악이 되실 텐데요, 용어를 나누신 바운디드 컨텍스트 기준으로 나누어서 정리해주셔도 좋을 것 같아요.

바운디드 컨텍스트 기준으로 용어가 나뉘어져 있다면 용어사전만으로도 조금 더 빠르게 도메인을 이해할 수 있을거라고 생각되네요.

2022-09-15 16:36 UTC, kyucumber commented on README.md
> +| 방문한 손님 | guest             | 주문 테이블을 사용중인 손님을 뜻한다.                       |     |
현재 주문 테이블은 손님의 정보를 가지거나 하지 않고 단순히 numberOfGuest라는 값으로 손님의 수만을 표현하고 있어요 따라서 주문 테이블 하위에 방문한 손님이라는 용어를 별도로 정리할 필요가 있을지 조금 고민되는 것 같네요

2022-09-15 16:36 UTC, kyucumber commented on README.md
> +| 주문 유형 - 매장 주문 | eat in order type     | 손님이 매장을 방문해 주문 테이블에서 주문하는 주문 유형을 뜻한다. |     |
주문이 주문 유형을 가진다는 부분이 한눈에 드러나진 않는 것 같은데요

주문 유형에 대한 설명도 별도로 넣어도 좋을 것 같아요.

2022-09-16 15:16 UTC, ChoiEungi commented
안녕하세요!! 리뷰 반영 진행해서 올려드립니다.

말씀주신대로 모호한 부분을 명확히하니 훨씬 더 처음에 보는 입장에서 이해하기 편해진 것 같아요!!

 리뷰 반영하면서 궁금한 점은, 비속어를 따로 분리해야 한다는 점에서 저희 페어님과 이야기를 나눈 결과 `비속어`라는 부분이 `상품`에서 다루는 비속어과 `메뉴`에서 다루는 비속어가 다를 수 있다고 생각해 각각의 바운디드 컨텍스트에 따로 분리해서 넣었습니다. 감사합니다 :)

2022-09-17 15:44 UTC, kyucumber commented
> 리뷰 반영하면서 궁금한 점은 DM에서 드렸듯, 비속어를 따로 분리해야 한다는 점에서 저희 페어님과 이야기를 나눈 결과 비속어라는 부분이 상품에서 다루는 비속어과 메뉴에서 다루는 비속어가 다를 수 있다고 생각해 각각의 바운디드 컨텍스트에 따로 분리해서 넣었는데 이에 대한 리뷰어님의 의견이 궁금합니다. 감사합니다 :)

지금은 아래와 같이 정리되어 있어 공통적으로 정리되어도 무방할 것 같아 말씀드렸지만

- 욕설 등, 상품 이름에 들어가기 적절하지 않은 단어를 뜻한다.   
- 욕설 등, 메뉴 이름에 들어가기 적절하지 않은 단어를 뜻한다.

위에서 말씀하신 경우처럼 컨텍스트별로 조금씩 다른 설명이 필요한 경우라면 각각의 바운디드 컨텍스트 하위에 별도로 정리하는게 좋다고 생각합니다.

2022-09-17 15:45 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요.

남겨두신 질문에는 코멘트 남겨두었어요~

2022-09-17 15:45 UTC, merged