2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #199
Opened 2022-09-17 15:33 UTC by benggrae

안녕하세요. 총명님

"2단계 모델링" 하기 리뷰 부탁드립니다.

모델링을 행위 기반(서비스 코드와 요구사항을 참조)으로 작성을 진행 하였습니다.
이번 미션을 진행하면서 저희가 코드를 짤때는 중복을 방지 하는것이 미덕이지만 모델링 단계에서는 중복된 내용을 어느정도 허용하는것이 
이해하기 편하다 라고 생각이 들더라구요 이부분에 대해서 총명님은 어떻게 생각하시는지 궁금합니다. 🤔

리뷰 잘 부탁드립니다!

2022-09-19 14:01 UTC, wkdchdaud123 requested changes
@benggrae 님 안녕하세요
모델링 아주 깔끔하게 잘 작성해주셨어요. 👍 
몇가지 코멘트를 남겨두었는데 확인 부탁드려요 🙏

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +### 주문 상태 (매장 주문, 포장 주문)
용어사전을 계속 업데이트하고 개선해 나가시는 군요 👍 💯

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +* **등록된 상품 (`Product`)목록을 조회 한다.**
명시하지는 않았지만 전체적으로 속성과 기능을 잘 구분해서 작성해주신 것 같아요 👍 
지금도 충분하다고 생각하지만 필요하다면 아래처럼 속성과 기능을 명시할 수 도 있을 것 같아요.
참고만 부탁드려요.

```suggestion
#### 속성
* **상품은 이름, 가격을 가진다.**

#### 기능 OR 행위
* **상품 (`Product`)을 등록 한다.**
  * 가격 (`price`)과 이름이 반드시 필요 하다.
  * 상품의 이름은 비속어가 (`Profanity`) 포함 되면 안된다.
  * 이름이 공백이면 등록 할수 없다.
  * 가격은 0원 이상 이어야 한다

* **상품 (`Product`)의 가격을 변경 한다.**
  - 상품 (`Product`)의 변경할 가격이 0원 이상 어야 한다.
  - 상품 (`Product`)이 변경 될때 상품이 포함된 메뉴 (`Menu`)의 가격이 메뉴 상품(`Menu Product`)의 수량 * 가격의 합 보다 크면 메뉴가 숨겨진다.

* **등록된 상품 (`Product`)목록을 조회 한다.**
```

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +  * 가격 (`price`)과 이름이 반드시 필요 하다.
속성이 아닌 기능에서 `가격` 대신 `가격 (price)` 이라고 하신 이유가 있을까요? :)
위에서 아래로 읽기 때문에 오히려 속성에서 한글과 영문이 명시되는 것이 더 좋을 것 같은데
어떻게 생각하시나요??😄

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +  - 메뉴(`Menu`) 의 이름은 필수 이며 비속어(`Profanity`)를 포함하면 안된다.
[여기서](https://github.com/next-step/ddd-strategic-design/pull/199/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R176-R177) 나누어 정리하신 것과 다르게 이름과 비속어를 같이 작성하셨는데 둘 중 한가지 방식으로 통일을 하는 것이 어떨까요? :)
읽는 사람의 입장에서는 어떤 차이가 있는지 의문을 가질 수 있을 것도 같네요 ㅎㅎ
혹시 이유가 있을까요?? 😄

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +  - 주문 완료(`Completed`) 상태가 아닌 `주문(Order)`이 있을 경우 빈 테이블(`Empty Table`)로 변경 할 수 없다.
`주문(Order)`은 주문(`Order`)를 의도하신 것 같은데 백틱이 잘못들어 간 것 같네요 ㅎㅎ:)

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +### 주문 테이블 (`Order Table`)
꼼꼼하고 흐름대로 상세히 잘 작성해주셔서 너무 잘 읽히네요 👍 💯

2022-09-19 14:01 UTC, wkdchdaud123 commented on README.md
> +### 주문 (`Order`)
주문 유형 배달 주문, 포장 주문, 매장 주문 너무 잘 나누어 주셨어요. 👍 💯 

꼭 수정을 해야하는 것은 아니지만 아래 내용도 한번 고민해주세요! 😄

혹시 여기 주문의 속성과 기능을 작성하시면서 배달 주문, 포장 주문, 매장 주문이 필요한 속성과 기능이 다른데 주문이라는 모델 하나에 다 담고자 하니 각 주문의 용어 및 기능의 의미가 모호하고 방대해지지 않았나요? 그렇다면 바운디드 컨텍스트를 나눌 수 있는 지점이 될 것 같아요.
추가로 이벤트 스토밍도 참석하셔서 바운디드 컨텍스트를 나누는 과정도 함께하셨을 것 같아요 👍 

그렇다면 이쪽은 사실 배달 주문, 포장 주문, 매장 주문 바운디드 컨텍스트로 나누어 작성될 수 도 있을 것 같아요. 😄

2022-09-19 14:04 UTC, wkdchdaud123 commented
>  모델링 단계에서는 중복된 내용을 어느정도 허용하는것이 이해하기 편하다 라고 생각이 들더라구요

제가 위 질문에 답변을 놓칠뻔 했네요.
혹시 어떤 중복을 말씀하시는 걸까요? :)

2022-09-20 08:10 UTC, benggrae commented on README.md
> +  - 주문 완료(`Completed`) 상태가 아닌 `주문(Order)`이 있을 경우 빈 테이블(`Empty Table`)로 변경 할 수 없다.
헉 수정하겠습니다

2022-09-20 08:11 UTC, benggrae commented on README.md
> +  * 가격 (`price`)과 이름이 반드시 필요 하다.
속성에 적으면 추후 개발단계시 변수명 짓기에 좋을거 같아요!

2022-09-20 08:18 UTC, benggrae commented
질문했던 부분은 용어사전등과 같이 매장주문,  포장주문, 배달 주문의 각 주문별로 "접수 대기"등과 같이  중복으로 작성 되더라구요.

모델링에서는 바운더리 컨텍스트로 나누어 작성하였을때 "주문을 등록한다"라는 행위는 주문 유형마다 들어가게 될텐데 이 부분 작성에 대한 중복을 이야기 했던거 였습니다!

2022-09-20 10:56 UTC, benggrae commented on README.md
> +  - 메뉴(`Menu`) 의 이름은 필수 이며 비속어(`Profanity`)를 포함하면 안된다.
딱히 이유는 없습니다. 한가지 방식으로 통일하여 작성하도록 하겠습니다.

2022-09-20 10:56 UTC, benggrae commented on README.md
> +### 주문 (`Order`)
주문을 나누어서 작성해보도록 하겠습니다.

2022-09-20 13:41 UTC, wkdchdaud123 commented
> 질문했던 부분은 용어사전등과 같이 매장주문, 포장주문, 배달 주문의 각 주문별로 "접수 대기"등과 같이 중복으로 작성 되더라구요.
> 
> 모델링에서는 바운더리 컨텍스트로 나누어 작성하였을때 "주문을 등록한다"라는 행위는 주문 유형마다 들어가게 될텐데 이 부분 작성에 대한 중복을 이야기 했던거 였습니다!

1. 보편언어라는 것이 바운디드 컨텍스트내에서 특정 의미가 있다는 관점
2. 주문이라고 하지만 매장, 포장, 배달 바운디드 컨텍스트는 각자 다른 길을 가게 될 것이다 라는 관점
3. 바운디드 컨텍스트 별로 모델링 정리한 것이 따로 정리 될 수 있다는 관점

등의 관점이 있겠지만 저는 위와 같은 관점에서 중복을 허용하는 것이 맞다고 봅니다. 
**진짜 중복**이 아닌 **우발적 중복**이라는 관점으로 볼 수 있을 것 같습니다. :)

2022-09-20 13:50 UTC, wkdchdaud123 approved these changes
@benggrae 님
빠르게 피드백 반영 너무 잘해주셨어요. 👍 💯 
다음 미션 진행을 위해 Merge 할게요.

추가로 코멘트 남겨놓았는데요.
다음 미션 진행 시 함께 적용해서 PR 올려주시면 좋을 것 같아요. 👍

2022-09-20 13:50 UTC, wkdchdaud123 commented on README.md
> +| 배달 주소  | Delivery Address | 배달을 받는 장소를 뜻며,배달 주문에서만 사용 한다.         |
다른 곳 수정하시면서 실수로 수정하신 것 같네요 확인 부탁드려요 ㅎㅎ

2022-09-20 13:50 UTC, wkdchdaud123 commented on README.md
> +#### 행위
속성과 행위를 나누어 한눈에 더 잘 들어오는 것 같습니다! 👍 💯

2022-09-20 13:50 UTC, wkdchdaud123 commented on README.md
> +*  속성은 이름을 포함한다.
문장에서 **속성** 이라는 단어는 제거되어도 되지 않을까요??
`메뉴 그룹은 이름을 포함한다.`가 더 의미가 명확한 것 같은데요 
전체적으로 고민을 해보신 후 수정하시면 좋을 것 같아요 👍

2022-09-20 13:50 UTC, wkdchdaud123 commented on README.md
> +#### 배달 주문 (`Delivery Order`)
각 주문을 바운디드 컨텍스트에 맞게 잘 나누어 주셨어요 👍 💯

2022-09-20 13:52 UTC, merged

2022-09-21 14:59 UTC, benggrae commented on README.md
> +| 배달 주소  | Delivery Address | 배달을 받는 장소를 뜻며,배달 주문에서만 사용 한다.         |
이런... 다음 PR때 수정하여 반영하겠습니다!