1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #200
Opened 2022-09-18 02:13 UTC by chr0m3

용어 사전 작성 완료했습니다.

이번 미션 동안 잘부탁드립니다.

2022-09-19 07:30 UTC, sah3122 requested changes
용어사전 정리 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드려요 🙏 
성주님이 개인적인 사정이 생겨 제가 대신 피드백 남겨두었습니다 😄

2022-09-19 07:30 UTC, sah3122 commented on README.md
>  ## 용어 사전
용어 사전 정리 잘해주셧네요 👍 

한가지 고민해볼거리로 용어사전에 정의된 용어는 특정 바운드디 컨텍스트에서 완전한 의미를 가지게 됩니다. 
현재는 키친포스라는 도메인에서 사용하는 모든 용어를 한번에 정리 해주셨는데, 메뉴에서 사용하는 용어, 주문에서 사용하는 용어등과 같이 분리를 해보는것이 어떨까요 ?

2022-09-19 07:30 UTC, sah3122 commented on README.md
> +| (메뉴) 숨김 | Hide | 메뉴를 목록 또는 화면에 보여지지 않게 함. |
메뉴 컨텍스트를 기준으로 정리한다면 이와같이 나타낼 필요가 없을것 같습니다 ㅎㅎ

2022-09-19 07:30 UTC, sah3122 commented on README.md
> +| 매장 (주문) | Eat in | 주문 테이블을 점유한 손님에게 메뉴가 전달되는 주문 유형. |
주문 컨텍스트는 주문 유형에따라 요구하는 요구사항들이 다를거에요. 
주문 유형에 따라서 용어를 정리하는 방법도 좋은 방법이 될것 같습니다 ㅎㅎ

2022-09-20 22:57 UTC, chr0m3 commented on README.md
> +| (메뉴) 숨김 | Hide | 메뉴를 목록 또는 화면에 보여지지 않게 함. |
메뉴 컨텍스트 내에서 노출 또는 숨김이라는 표현을 쓰는 곳이 (지금은 메뉴밖에 없긴 하지만) 메뉴 단 하나임이 언제까지나 보장되지는 않을 것 같습니다.
그리고 실제로 커뮤니케이션에 있어서도 주어를 빼고 "노출한다"와 같이 사용하지 않고 "메뉴를 노출한다"와 같이 사용될 것이기 때문에 '무엇을'에 해당하는 부분을 명시해 주었습니다.

2022-09-20 23:04 UTC, chr0m3 commented on README.md
>  ## 용어 사전
d7839a086b648ea5eeb441dba421911e3090f832
반영되었습니다

2022-09-20 23:15 UTC, chr0m3 commented on README.md
> +| 매장 (주문) | Eat in | 주문 테이블을 점유한 손님에게 메뉴가 전달되는 주문 유형. |
7a7178a12eba241192012e3eac104216e539c6ba
반영되었습니다
IntelliJ의 테이블 포매팅 기능때문에 diff가 이쁘게 안나오네요 ㅠ

2022-09-22 01:33 UTC, sah3122 commented on README.md
> +| 컨텍스트   | 한글명             | 영문명              | 설명                                                                                    |
### 공통 
| 한글명 | 영문명 | 설명  |
|-------|-------|-----|
... 

하나의 테이블로 표현하지 않고 경계를 나누는 방법도 좋을것 같아요 :)

2022-09-22 01:33 UTC, sah3122 commented on README.md
> +| 배달 주문  | 배달 주소           | Delivery address | 손님이 메뉴를 전달 받고 싶어하는 위치를 주소로 나타낸 것. 배달 주문인 경우 반드시 있어야 한다.                               |
주문 유형별 용어 정리 👍

2022-09-22 01:33 UTC, sah3122 commented on README.md
> +| (메뉴) 숨김 | Hide | 메뉴를 목록 또는 화면에 보여지지 않게 함. |
컨텍스트 내에서 용어의 충돌이 생긴다면 새로운 컨텍스트로 분리하는것도 좋은 방법이 될것 같아요 😄

2022-09-22 01:33 UTC, sah3122 approved these changes
피드백 반영 잘해주셧네요 👍 
간단한 코멘트 하나 남겨두었는데 확인 부탁드리며 다음 미션을 진행해주세요 !

2022-09-22 01:34 UTC, merged