1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #202
Opened 2022-09-18 05:53 UTC by DominiQN

안녕하세요! 첫 리뷰 요청 잘 부탁드립니다!

궁금한 점이 몇 가지 있습니다!

- 제약 사항도 용어 사전으로 포함시키는 게 좋을까요?
- 설명이 용어 그 자체를 반복하는 것 같은 느낌이 들 때는 어떻게 하면 좋을까요?

2022-09-18 14:40 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 한글명               | 영문명                        | 설명                                                                                                   |
> 제약 사항도 용어 사전으로 포함시키는 게 좋을까요?

정리하신 용어의 이해를 돕기 위한 제약 사항이라면 용어 사전에 포함되어도 괜찮다고 생각합니다.

> 설명이 용어 그 자체를 반복하는 것 같은 느낌이 들 때는 어떻게 하면 좋을까요?

설명이 용어 자체를 반복하는 경우라면 별도의 설명 없이도 이해가 가능한 용어일 것 같아요. 
예를 들면 가격이나 이름 등이 해당될 수 있겠네요, 이런 경우라면 용어사전에 굳이 정리하지 않아도 괜찮다고 생각합니다.

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 상품의 목록을 조회하다      | List products              | 등록된 모든 상품을 보는 것을 의미                                                                                  |
상품의 등록, 가격 변경, 상품 조회는 말 그대로의 의미를 가지고 있습니다.

용어 사전에는 명사, 동사 등 모든 유비쿼터스 언어들이 정의될 수 있지만 사회통념상 보편적으로 사용될 수 있는 부분에 대해서까지는 꼭 정리하지 않아도 괜찮다는 생각이 들어요.

보편적으로 이해할 수 있는 행위에 대해서는 그 행위에 대한 제약 사항이나 부가적인 설명이 있는 경우만 용어 사전에 추가되어도 괜찮지 않을까요?

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 상품명               | Product name               | 상품의 이름                                                                                               |
위에 제약사항도 용어사전으로 포함시키는게 좋을지 질문해주셨던 것 같아요.

이름에는 비속어가 들어올 수 없다는 제약사항은 상품명에 대한 이해를 돕기 위해서 용어사전에 추가되면 좋을 것 같네요.

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 메뉴 그룹 목록을 조회하다    | List menu groups           | 등록된 모든 메뉴 그룹을 보는 것을 의미                                                                               |
위와 동일한 코멘트인데 등록, 목록 조회는 이름 그대로의 역할을 수행하고 있어서 별도로 정리하지 않아도 괜찮을 것 같아요.

다른 부분도 동일한 내용이 작성되어 있는데 추가로 코멘트를 더 남기지는 않을게요.

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 상품                | Product                    | 매장에서 팔기 위한 물품                                                                                        |
현재 도메인(상품, 메뉴, 메뉴 그룹, 주문 테이블, 주문)별로 도출될 수 있는 하위 용어들에 대해서 잘 정리해주신 것 같아요.

용어를 정리하시다보면 바운디드 컨텍스트가 어떻게 나뉘겠구나 라는 부분이 대략적으로 파악이 되실 텐데요, 바운디드 컨텍스트 기준으로 나누어서 정리해주셔도 좋을 것 같아요.
바운디드 컨텍스트 기준으로 용어가 나뉘어져 있다면 용어사전만으로도 조금 더 빠르게 도메인을 이해할 수 있을거라고 생각되네요.

이 부분은 강의와 이후 미션 단계에서 자연스럽게 다루게 될 것이라 반영하실 필요는 없습니다.

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 숨겨진 메뉴            | Hided menu                 | 숨겨진 메뉴는 주문할 수 없다.                                                                                    |
이번 단계는 모델링이 아니라 용어를 정리하는 단계긴 하지만 노출된 메뉴와 숨겨진 메뉴를 별도의 용어로 정리하셔서 DisplayedMenu, HidedMenu 두가지 도메인이 별도로 존재하는 것 같이 느껴지네요.

메뉴의 displayed라는 속성 값을 통해서 관리되고 있는데 메뉴가 가지는 해당 속성값에 대한 용어 설명 없이 노출된 메뉴와 숨겨진 메뉴라는 별도의 용어를 정리하는 경우 오히려 혼란스러울수 있지 않을까요?

2022-09-18 14:40 UTC, kyucumber commented on README.md
> +| 메뉴 가격을 변경하다       | Change menu price          | 변경한 이후로는 메뉴를 주문할 때 변경된 가격을 기준으로 주문된다.                                                                |
메뉴 가격을 변경할 때 가격 정책이 지켜지지 않는 경우 숨겨진 메뉴가 된다는 부분도 용어의 이해를 돕기 위해 추가하면 어떨까요?

2022-09-19 15:06 UTC, DominiQN commented on README.md
> +| 한글명               | 영문명                        | 설명                                                                                                   |
자세한 답변 감사드립니다!

2022-09-19 15:06 UTC, DominiQN commented on README.md
> +| 상품의 목록을 조회하다      | List products              | 등록된 모든 상품을 보는 것을 의미                                                                                  |
네 동의합니다!

2022-09-19 15:07 UTC, DominiQN commented on README.md
> +| 상품명               | Product name               | 상품의 이름                                                                                               |
추가하겠습니다!

2022-09-19 15:20 UTC, DominiQN commented on README.md
> +| 숨겨진 메뉴            | Hided menu                 | 숨겨진 메뉴는 주문할 수 없다.                                                                                    |
그렇군요 메뉴 노출을 정리해보겠습니다!

2022-09-19 15:26 UTC, DominiQN commented
https://github.com/next-step/ddd-strategic-design/pull/202#discussion_r973707039

가격 정책을 보다 상세하게 적었는데, 리뷰해주신 걸 보니 고민이 듭니다.

상세한 정책을 풀어 적는 것보다는, 추상적으로 적는 게 좋을까요? 아니면 상세히 풀어 적는 게 좋을까요?

아니면 이것도 상황에 따라, 팀의 합의에 따라 다른 걸까요?

2022-09-20 12:06 UTC, kyucumber requested changes
남겨주신 코멘트에 대해 답변 남겨두었어요.

확인하시고 다시 요청하시면 머지하도록 할게요!

2022-09-20 12:06 UTC, kyucumber commented on README.md
> +| 메뉴 가격을 변경하다  | Change menu price     | 변경될 메뉴 가격이 메뉴에 속한 상품 및 수량의 가격의 합보다 작거나 같아야 한다.                   |
```
가격 정책을 보다 상세하게 적었는데, 리뷰해주신 걸 보니 고민이 듭니다.

상세한 정책을 풀어 적는 것보다는, 추상적으로 적는 게 좋을까요? 아니면 상세히 풀어 적는 게 좋을까요?

아니면 이것도 상황에 따라, 팀의 합의에 따라 다른 걸까요?
```

사실 요구사항 정리나 지금 하는 용어사전 정리, 이후에 진행할 모델링들은 모두 명확한 정답이 있는 영역이 아니에요. 말씀하신 것 처럼 상황이나 팀의 합의에 따라 다른 결과를 도출할 수 있을 것 같습니다.

사실 정책을 추상적으로 적으신다고 하면 어떤 느낌으로 적으시려는건지는 잘 이해하지 못했습니다. 요 부분은 추가로 코멘트 남겨주시거나 DM 남겨주시면 관련해서 추가로 말씀드릴게요.

--- 

이전 리뷰 때 아래와 같은 코멘트를 제가 남겼었는데요, 이는 메뉴 가격 변경이라는 용어를 별도로 정리해주셔서 만약 메뉴 가격 변경이라는 용어를 정리할거라면 정책에 대한 설명이 포함되어야 한다고 생각해서 남긴 코멘트입니다.

> 메뉴 가격을 변경할 때 가격 정책이 지켜지지 않는 경우 숨겨진 메뉴가 된다는 부분도 용어의 이해를 돕기 위해 추가하면 어떨까요?

조금 설명이 돌아갔는데, 위 코멘트와 별개로 제 개인적인 생각을 말씀드리면 메뉴 가격 변경, 주문 생성과 같은 행위는 모델링 단계에 말씀하신 정책들과 함께 정리되어도 된다고 생각합니다.

다른 쪽 코멘트에도 남겼지만 등록 ,변경, 조회 등의 보편적인 행위를 용어로 굳이 추출할 필요도 없고 용어 사전에서 상세한 정책 등을 다루기 애매한 경우도 있을 수 있거든요.

물론 메뉴와 메뉴의 노출 여부(displayed)라는 용어를 잘 이해하기 위해서 정책과 관련된 부분을 용어 사전에 남길순 있다고 생각합니다.



조금 장황해진 면이 있는데 최종적으로 정리하면 아래와 같습니다.

- 메뉴 가격 변경 등의 경우 보편적인 행위라 용어로 추출하기 보다는 모델링 단계에 세부적인 정책, 제약과 함께 정리하면 좋겠다.
- 만약 용어로 추출 할거라면 해당 용어의 이해를 도울 수 있는 정책, 제약같은 부분도 필요에 따라 설명에 추가하면 좋겠다.

2022-09-20 12:06 UTC, kyucumber commented on README.md
> +| 공개된 (메뉴)     | Displayed (menu)      | 메뉴가 공개되어야 주문할 수 있으며, 비공개되면 주문할 수 없다.                             |
displayed라는 속성값에 대해 공개된이라는 한글 명은 조금 어색한 것 같아요.

노출 여부, 공개 여부 등의 용어는 어떨까요?

2022-09-20 16:24 UTC, DominiQN commented on README.md
> +| 공개된 (메뉴)     | Displayed (menu)      | 메뉴가 공개되어야 주문할 수 있으며, 비공개되면 주문할 수 없다.                             |
음... 저도 조금 어색하다고 느껴서, 괄호로 수식받는 단어 '메뉴'를 적었어요

저도 공개 여부가 좋아 보입니다! 수정하겠습니다.

2022-09-20 16:29 UTC, DominiQN commented
추상적이라고 한 의미는,
구체적인 제약 사항을 나열하기보다 '정책을 지켜야 한다'처럼, 무언가 제약이 존재하는데 이 도메인은 그걸 지켜야 한다라는 식으로 적는 것을 말씀드리고 싶었습니다!
`메뉴 가격을 변경할 때 가격 정책이 지켜지지 않는 경우 숨겨진 메뉴가 된다`라고 해주신 것처럼이요!

되게 디테일하게 얘기해주셔서 그 부분에 대해서는 이해가 잘 되었습니다! 감사합니다!!!!

2022-09-21 13:37 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요~

2022-09-21 13:37 UTC, merged