2단계 모델링 하기
next-step/ddd-strategic-design pull request #204
Opened 2022-09-18 14:20 UTC by gmoon92

안녕하세요 규남님 😀

이번 도메인 모델링 미션을 진행하면서 나름대로 기준을 잡고 작성했습니다.

- 개발 지식이 필요한 용어보단 모두가 알 수 있는 평문으로 표현하기
    -  `크게 소리 내어` 읽어봤을 때, 의미가 제대로 전달되는지 확인하기
- 모델링 과정은 도메인 용어를 녹여내어서 참여하는 사람 모두 공감가야 한다.
    - 모델링이라는것이 개발자만을 위한것은 아니다.
    - 참여하는 사람이 모두 공감하는 모델링이 좋은 모델이다.
- 모델링 과정은 실제 구현에 도움이 되기 위함이다.
    - 작성한 모델링을 통해 바로 코드로 변환 가능한지 검토해보자.
    - 요구사항, 용어 사전에 비해 개발 친화적인 단계다.

모델링 과정에서 모델의 구성요소들이 포함되도록 작성했습니다.

- 상태
- 행위
- 제약 사향
- 연관 관계
- BOUNDED CONTEXT 설정

컨텍스트는 세 가지로 구분했습니다.

독립된 시스템으로 분리할 수 있는지
추후 컨텍스트가 확장 가능성이 존재하는지

- 상품
- 메뉴
- 주문

잘 부탁드립니다.🙇🏻‍♂️

2022-09-19 15:13 UTC, kyucumber requested changes
안녕하세요

모델링 잘 진행해주셨습니다. 몇가지 코멘트 남겨두었으니 확인 부탁드려요.

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +| 테이블 번호 | Order Table Name | 테이블을 식별할 수 있는 고유한 값 |
Name으로 되어 있네요~

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +  - [주문](#주문(Order))
주문 내에서 매장 주문을 제외하고 배달이나 포장 주문의 경우 테이블과 아무런 관계를 가지지 않습니다.

같은 주문 컨텍스트로 분류하는게 좋을지 고민해볼 수 있을 것 같습니다.

주문 유형(배달, 포장, 매장)별로 필요한 속성과 기능들이 조금씩 다른데 주문이라는 하나의 도메인에 모든 내용을 담기 어렵다면 주문 유형별로 컨텍스트가 나뉠수도 있을까요?

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +- 행위
컨텍스트 내 존재하는 도메인별 속성과 행위를 분리해주셔서 가독성이 좋아졌네요 👍

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +- 주문 컨텍스트
바운디드 컨텍스트별로 잘 나누어 모델링을 진행해주셨네요 👍

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +#### 숨김 메뉴 서비스(HiddenMenuService)
숨김 메뉴 서비스는 현재는 존재하지 않는 개념인 것 같은데 이후 리팩토링에 따라 추가하실 예정인걸까요?

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +  - `메뉴`는 반드시 한 개 이상의 `메뉴 상품`을 가진다.
중요한 부분은 아니지만 `메뉴`는이 계속 중복되어 표현되고 있어요.

메뉴 하위의 속성에 대한걸 다루고 있으니 계속 중복해서 표시하지 않아도 괜찮을 것 같아요~

다른 속성 모델링 부분도 동일하게 표현해주셨는데 별도로 코멘트 남기지는 않을게요.

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +    - `매장 주문`이 `주문 완료`가 되면 `테이블`은 `빈 테이블`로 설정한다.
주문 유형별로 상세하게 모델링을 잘 나누어주셨네요 👍

2022-09-19 15:13 UTC, kyucumber commented on README.md
> +    - `포장 주문`은 `대기` → `접수` → `서빙` → `주문 완료` 순서로 진행된다.
각 주문 별 상태의 흐름을 표현해주셔서 유형별 주문에 대한 이해가 쉬웠던 것 같네요 👍

2022-09-20 01:18 UTC, gmoon92 commented on README.md
> +#### 숨김 메뉴 서비스(HiddenMenuService)
현재는 존재하지 않는 개념이지만, 페어와 모델링 하는 과정에서
확장성을 고려해서 상품과 메뉴 도메인을 각각의 컨텍스트로 분리했습니다.
추후에 리펙토링 과정에서 산출될 것 같습니다.

상품 컨텍스트와 메뉴 컨텍스트간의 격리 여부(시스템 관점)는 추후에 결정되겠지만,  
컨텍스트 경계 사이에 도메인 서비스를 두어 두 컨텍스트를 통합하려 의도 했습니다.

실무에서 DDD 프로젝트를 직접 경험해보진 않아서, 두 컨텍스트를 통합하는데 이벤트도 활용하지만
실제 도메인 서비스를 두는지 궁금합니다.

규남님 의견을 듣고 싶습니다! 😀

2022-09-21 13:06 UTC, gmoon92 commented on README.md
> +#### 숨김 메뉴 서비스(HiddenMenuService)
-----------------
규남님! 곰곰히 생각해보니...
전략적 설계 단계에서 전술적 설계 단계에서 해야할 설계를 포함 시킨듯 하네요 😅

2022-09-21 13:07 UTC, gmoon92 commented on README.md
> +  - `메뉴`는 반드시 한 개 이상의 `메뉴 상품`을 가진다.
동의합니다 !
피드백 주신것 처럼 불필요한 접두사 표현은 제거하는게 가독성 측면에서 더 좋네요😄
감사합니다 !

2022-09-21 13:21 UTC, gmoon92 commented on README.md
> +  - [주문](#주문(Order))
공감합니다 ! 
규남님 피드백 주신것 처럼 매장 컨텍스트에 테이블 도메인이 속하는게 명확하고 경계를 잘 지켜지는것 같습니다.

헷갈리는 부분이 있습니다!
전략적 설계 단계는 개념적인? 단계라 바운디드 컨텍스트로 주문 유형별로 분리를했는데
실무에선 전술적 설계 단계에서 전략적 설계에서 도출된 바운디드 컨텍스트 별로 
기존에 주문(Order) 테이블을 각각의 유형별 테이블로 산출되는지 궁금합니다. 🤔

제 생각은 분리된 바인디드 컨텍스트는 각각의 시스템으로 구성할 수 있고,
분리된 시스템은 테이블 모델도 각각의 매장, 포장, 배달로 구성할 수 있을것 같아서요!
바운디드 컨텍스트 통합하는 과정에서 조회나 이벤트 데이터 일관성을 지키는 등등...
하나의 테이블에서 여러 유형의 테이블로 분리되면 여러 고려할 점이 더 클 것 같다는 생각도 들고...

이 부분에 대해서 규남님은 어떻게 생각하시는지 궁금합니다!...

2022-09-21 13:59 UTC, kyucumber commented on README.md
> +  - [주문](#주문(Order))
```
공감합니다 !
규남님 피드백 주신것 처럼 매장 컨텍스트에 테이블 도메인이 속하는게 명확하고 경계를 잘 지켜지는것 같습니다.

헷갈리는 부분이 있습니다!
전략적 설계 단계는 개념적인? 단계라 바운디드 컨텍스트로 주문 유형별로 분리를했는데
실무에선 전술적 설계 단계에서 전략적 설계에서 도출된 바운디드 컨텍스트 별로
기존에 주문(Order) 테이블을 각각의 유형별 테이블로 산출되는지 궁금합니다. 🤔

제 생각은 분리된 바인디드 컨텍스트는 각각의 시스템으로 구성할 수 있고,
분리된 시스템은 테이블 모델도 각각의 매장, 포장, 배달로 구성할 수 있을것 같아서요!
바운디드 컨텍스트 통합하는 과정에서 조회나 이벤트 데이터 일관성을 지키는 등등...
하나의 테이블에서 여러 유형의 테이블로 분리되면 여러 고려할 점이 더 클 것 같다는 생각도 들고...

이 부분에 대해서 규남님은 어떻게 생각하시는지 궁금합니다!...
```

말씀해주신 것 처럼 바운디드 컨텍스트가 매장 주문, 포장 주문, 배달 주문으로 나뉘게 된다면 저는 각각 별도 유형별 주문 테이블을 가지는 방향으로 가는게 좋다고 생각해요.

바운디드 컨텍스트가 분리되었다는 것은 언제든 팀이 분리되거나 개발 환경이 분리(별도의 마이크로서비스로 추출)될 수 있다는 얘긴데 같은 테이블을 사용한다면 나뉜 바운디드 컨텍스트에 맞게 팀이나 서비스가 분리될 수 없으며 이는 바운디드 컨텍스트가 잘 분리되었다고 볼 수 없을 것 같아요. 하나의 주문 컨텍스트로 보아야 하지 않을까요?

따라서 만약 주문이 동일한 테이블로 관리된다면 주문이라는 컨텍스트가 하나라고 보아야 하지 않을까 생각됩니다.

2022-09-21 14:05 UTC, kyucumber commented on README.md
> +#### 숨김 메뉴 서비스(HiddenMenuService)
숨김 메뉴 서비스라고 하는게 도메인 서비스의 영역으로 본다면 전술적 설계 단계에 포함되는게 자연스럽긴 합니다.

다만 모델링이든 용어 정리든 무조건 이런건 이 단계에 해야해 이런 규칙이 명확히 정해진 것은 아니므로 메뉴의 숨김과 관련된 부분을 모델링 단계에 표현하고 싶다면 넣어도 크게 상관 없다고 생각해요.

2022-09-21 14:05 UTC, kyucumber approved these changes
남겨주신 질문에 코멘트 남겨두었어요.

https://github.com/next-step/ddd-strategic-design/pull/204#discussion_r976547842
https://github.com/next-step/ddd-strategic-design/pull/204#discussion_r976555422

코멘트 확인 부탁드려요~

다음 단계 진행을 위해 머지하겠습니다.

2022-09-21 14:06 UTC, merged