Step3 기능 우선 패키지 구성하기 리뷰 요청합니다.
next-step/ddd-strategic-design pull request #221
Opened 2022-09-25 11:33 UTC by chosundeveloper

2022-09-27 09:19 UTC, starkim06 requested changes
안녕하세요! 

몇가지 코멘트 남겨두었습니다. 확인 부탁드려요 😄 
확인후 다시 요청주시면 머지하도록 하겠습니다!

2022-09-27 09:19 UTC, starkim06 commented on src/main/java/kitchenpos/eatinorder/application/OrderService.java
> +import kitchenpos.deliveryorder.domain.OrderStatus;
eatinorder 컨텍스트에서 deliveryorder를 알 필요는 없을것 같아요!

2022-09-27 09:19 UTC, starkim06 commented on src/main/java/kitchenpos/product/application/ProductService.java
> +import kitchenpos.menu.menu.repository.MenuRepository;
product 컨텍스트에서 menu를 알고 있을 필요가 있을지에 대해서 고민해보셔도 좋을 것 같아요.
저는 개인적으로 바운디드 컨텍스트는 언제든 별도의 서비스로 분리될수도 있다고 염두해두는 편입니다.

2022-09-27 09:19 UTC, starkim06 commented on src/main/java/kitchenpos/deliveryorder/infra/KitchenridersClient.java
> +package kitchenpos.deliveryorder.infra;
변경하지 않은 코드에 리뷰가 남겨지지 않네요;;

이렇게 별도로 분리한 interface가 infra 모듈에 있는것이 좋은지에 대해서도 한 번 고민해보시면 좋을것 같아요!

2022-09-27 09:19 UTC, starkim06 commented on README.md
> +  - `상품 가격(product price)`은 0원 이상이어야 한다.
전체적으로 들여쓰기 해주셔서 가독성이 더 좋아진것 같아요!!

2022-10-25 17:52 UTC, chosundeveloper commented on src/main/java/kitchenpos/eatinorder/application/OrderService.java
> +import kitchenpos.deliveryorder.domain.OrderStatus;
deliveryOrder와 eatinOrder 분리했습니다.

2022-10-25 17:53 UTC, chosundeveloper commented on src/main/java/kitchenpos/product/application/ProductService.java
> +import kitchenpos.menu.menu.repository.MenuRepository;
분리 가능성을 염두해서 하는게 좋을 것 같습니다

2022-10-25 17:56 UTC, chosundeveloper commented on src/main/java/kitchenpos/deliveryorder/infra/KitchenridersClient.java
> +package kitchenpos.deliveryorder.infra;
infra 모듈이 아닌 어느 부분으로 옮기는게 좀 더 적합할까요?

2024-04-14 15:15 UTC, starkim06 commented on src/main/java/kitchenpos/deliveryorder/infra/KitchenridersClient.java
> +package kitchenpos.deliveryorder.infra;
DIP(https://www.baeldung.com/cs/dip)를 참고해보시면 질문해 주신 부분에 답이 되지 않을까 싶습니다.
마찬가지로 JpaRepository 가 아닌 repository들의 패키지도 비슷한 맥락에서 고민해 보시면 좋을 것 같아요.
이 부분에 대해서 해당 이해가 안 가시면 언제든지 편하게 DM으로 질문 주세요 =)

2024-04-14 15:15 UTC, merged

2024-04-14 15:18 UTC, starkim06 commented
안녕하세요 @chosundeveloper 님, 시간이 많이 지났지만 기존에 PR이 열려 있어서 질문 주신 부분에 대해서 답변을 달아두었습니다.
(그동안에 이미 답을 찾으셨을지도 모르겠네요.)

기존의 코멘트나, 이번에 추가한 코멘트에 대해서 질문이 있으시면 언제든 DM 주세요 =)