docs: 용어 사전 작성
next-step/ddd-strategic-design pull request #222
Opened 2022-09-25 15:22 UTC by sangw0804

안녕하세요! 회사 일정때문에 요번 미션을 좀 늦게 시작하게 되었습니다 ㅠ
늦었지만 잘 부탁드립니다!

2022-09-26 02:24 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-09-26 02:24 UTC, kyucumber commented on README.md
> +| 비속어       | Purgomalum | 손님에게 보이면 안되는 단어                                      |
메뉴와 상품의 이름에 비속어가 사용되면 안되는데 설명에 그런 부분이 없어 용어사전만 봤을 땐 비속어가 왜 정리되었는지 이해하기 어려울 것 같아요.

설명에 관련 내용도 추가해주시면 좋을 것 같아요.

2022-09-26 02:24 UTC, kyucumber commented on README.md
> +### 주문
메뉴, 상품, 주문 별로 나누어서 용어를 잘 정리해주셨습니다.

용어를 정리하면서 정하신 기준에 따라 대략적으로 바운디드 컨텍스트가 어떻게 나뉘겠구나 하는 부분이 어느정도 파악이 되셨을 것 같아요. 
지금 용어사전 정리 단계에서는 불필요할 수 있지만 이후 모델링이나 전술적 설계 단계에서 추가로 고민해보시면 좋을 것 같은 부분을 남겨두었으니 참고 부탁드릴게요.

### 주문 컨텍스트의 분리

지금은 주문 컨텍스트는 하나만 존재하고 있으며 이에 따라 주문 유형별로 행위와 속성이 상이한 부분이 많습니다.
하나의 클래스에 담기에는 불필요한 부분이 많아(주문 테이블은 매장 주문에서만 필요함, 배달 대행사 호출은 배달 주문에서만 필요하다 등) 결합도가 높아지고 응집도가 떨어질 수 있을 것 같습니다.

기존 제공된 코드 내에서는 주문이 RDB상 테이블이 하나라 컨텍스트를 나누기는 조금 애매할 수 있는데, 리팩토링 과정에서 매장, 포장, 배달 주문 자체의 컨텍스트를 분리하는 부분도 고려해볼 수 있을까요?

2022-09-26 02:24 UTC, kyucumber commented on README.md
> +| 주문테이블     | OrderTable       | 홀 주문시 필요한 테이블                                        |
테이블을 주문 하위에 포함시켜주셨는데 테이블의 경우도 여러 용어들과 제약조건, 개념들이 많이 포함되어 있어 별도로 분리되어서 표현되어도 좋을 것 같아요.

정답이 있는 부분은 아니라 반영하시진 않아도 되는데 분리하는게 좋을지 한번 고민해보시면 좋을 것 같습니다.

2022-09-26 02:24 UTC, kyucumber commented on README.md
> +| 메뉴를 숨기다    | Hide Menu             | 메뉴가 손님에게 보이지 않고 주문 불가능한 상태가 되게 함                   |
개인적인 의견일 수 있는데 이런 말 그대로 이해할 수 있는 행위를 용어 사전에 별도로 정리할 필요가 있을지 고민되는 것 같아요.

메뉴 노출과 관련된 부분의 설명은 필요할 것 같은데 메뉴가 가지는 노출 여부(displayed)에 대해 손님에게 보이거나 보이지 않는다는 설명을 추가하는건 어떨까요?

2022-09-26 02:24 UTC, kyucumber commented on README.md
> +### 주문
OrderLineItem에 대한 부분도 용어로 정리하면 어떨까요?

2022-10-01 03:04 UTC, sangw0804 commented on README.md
> +### 주문
넵 요거는 이후 리팩토링에서 분리 해보도록 하겠습니다!

2022-10-01 12:27 UTC, kyucumber approved these changes
수고 많으셨습니다.

다음 단계 진행을 위해 머지할게요

2022-10-01 12:27 UTC, merged