Step2 - 모델링 하기
next-step/ddd-strategic-design pull request #239
Opened 2022-10-10 02:45 UTC by DoLiLu

안녕하세요

Step2 - 모델링 하기 미션 리뷰 요청합니다.

질문이 하나 있는데, 
OrderLineItem을 어떻게 표현해야할지 잘 모르겠습니다.

그래서 일단 OrderLineItem, OrderLineItems로 표현하여 진행 하였습니다.

감사합니다.

2022-10-11 13:56 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 
확인 부탁드릴게요~

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +- 상품의 이름에는 비속어가 포함될 수 없다.
`상품` 은 가격을 변경할 수 있어야 하는데요. 이 부분도 모델링에 추가하는 것은 어떨까요?

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +- OrderLineItem은 가격과 수량을 갖는다.
`OrderLineItem` 은 요구 사항에 `주문 항목` 이라고 나와 있네요!

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +- 메뉴는 메뉴 그룹에 속한다.
개인적인 의견인데 `메뉴` 하위에  `메뉴` 라는 단어는 빼도 괜찮지 않을까요? 
```
### 메뉴
- 식별자, 이름, 가격, 메뉴 상품을 갖는다.
- 가격은 메뉴 상품 금액의 합 이하 여야 한다.

```

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +### 매장 주문
각 주문을 BC 별로 잘 나눠주셨어요 👍

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +- OrderLineItem은 가격과 수량을 갖는다.
매장 주문에서 주문 테이블과 주문은 별도로 나눠서 정리해도 괜찮을 것 같아요. 
개행이 없으니 가독성이 좀 떨어지는 것 같아요.

2022-10-11 13:56 UTC, hyunssooo commented on README.md
> +- 상품의 이름에는 비속어가 포함될 수 없다.
각각 가지는 속성과 행위를 분리해서 모델링을 진행해 보아도 좋을 것 같아요.

2022-10-12 11:29 UTC, DoLiLu commented on README.md
> +- 메뉴는 메뉴 그룹에 속한다.
수정하였습니다.

2022-10-12 11:30 UTC, DoLiLu commented on README.md
> +- OrderLineItem은 가격과 수량을 갖는다.
수정하였습니다.

2022-10-12 11:34 UTC, DoLiLu commented
리뷰를 받고 질문이 하나 생겼는데,
리뷰어님이 생각하시는 모델링의 범위는 어디까지라고  생각하시나요?

2022-10-13 12:04 UTC, hyunssooo commented
@DoLiLu 안녕하세요. 
모델링의 범위보다는 모델링의 목적이 무엇인가를 고민해 보시면 좋을 것 같아요. 
제가 생각하는 모델링의 목적은 관계자들의 멘탈 모델을 반영하고 서로가 같은 모델을 생각하게 하는 것 같아요. 그래서 모델링의 결과물은 글뿐만 아니라 다이어그램, 이미지 등 여러 가지로 나올 수 있다고 생각해요. 관계자들이 모두 이해할 수 있는 범위의 모델링이 모델링의 범위 아닐까요?

2022-10-13 12:07 UTC, hyunssooo approved these changes
안녕하세요. 
모델링 미션 잘 진행해 주셨어요. 
몇 가지 코멘트 남겼는데 다음 step 진행하시면서 확인 부탁드려요!

2022-10-13 12:07 UTC, hyunssooo commented on README.md
> +- 주문 항목의 수량은 1보다 커야 한다.
처음에는 context 별로 잘 나눠줬다고 생각했는데 `매장 주문 테이블` 이 나눠지니깐 조금 애매해진 것 같아요. 
`매장 주문 테이블`은 `매장 주문` 하위로 들어가야 하지 않을까요? 
`메뉴`와 `메뉴 그룹`도 고민해 보시면 좋을 것 같아요.

2022-10-13 12:07 UTC, merged