1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #256
Opened 2023-08-31 13:09 UTC by cocahack

안녕하세요! 이번 미션 잘 부탁드립니다.

2023-09-01 10:12 UTC, cocahack commented on README.md
> +- 테이블을 비울 수 있다.
이 두 부분은 사전에서 정의한 용어를 사용하는걸로 변경해봤습니다!

2023-09-01 12:58 UTC, kyucumber requested changes
용어사전 잘 정리해주셨네요.

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-09-01 12:58 UTC, kyucumber commented on README.md
>  ## 용어 사전
꼼꼼하게 잘 정리해주셨습니다.
다만 하나의 표에 모든 용어들이 다 들어있어 한눈에 잘 안들어오는 느낌이 있는데요, BOUNDED CONTEXT(상품, 주문 등)별로 나누어서 표로 정리해보시면 어떨까요?

2023-09-01 12:58 UTC, kyucumber commented on README.md
> +| 비속어          | profanity        | 저속하거나 모욕적인 단어                     |
비속어와 관련해 외부 API를 사용하는데요, 외부 API에 대한 부분도 별도로 정리하면 어떨까요?

https://github.com/next-step/ddd-strategic-design/blob/9b21d9e71b2368c0a301898b5fb85345b109731e/src/main/java/kitchenpos/infra/DefaultPurgomalumClient.java#L20

2023-09-01 12:58 UTC, kyucumber commented on README.md
> +| 주문 상태       | order status     | 손님의 주문 진행 상태                        |
주문 상태의 흐름이 어떻게 되는지 한눈에 들어오지 않는 것 같아요. 그리고 주문 유형(배달, 포장 등)에 따라도 상태의 흐름이 다른데 이 부분을 한눈에 보이게 아래처럼 정리하면 어떨까요?

- 배달 주문
  - 대기 -> 접수 -> 배달 시작 -> 배달 완료 -> 완료
- 포장 주문
  - 대기 -> 접수 -> 서빙 -> 완료

2023-09-01 13:18 UTC, kyucumber requested changes
용어사전 잘 정리해주셨네요.

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-09-02 04:12 UTC, cocahack reviewed
말씀해주신대로 컨텍스트 그룹핑과 비속어 API 사전에 반영했습니다 🙇🏻‍♂️

2023-09-02 04:12 UTC, cocahack commented on README.md
>  ## 용어 사전
상품, 메뉴, 주문 세 가지 컨텍스트가 있다고 생각하고 수정해보았습니다 🙇🏻‍♂️

2023-09-02 04:12 UTC, cocahack commented on README.md
> +| 비속어 검증기 | Purgomalum   | 상품 이름에 포함된 비속어를 검증하는 시스템 |
상품, 메뉴에서 사용하고 있지만, 별도의 컨텍스트로 분리할만큼 큰 부분은 아닌거 같아 일단 상품과 메뉴에 각각 넣었습니다.

2023-09-02 04:12 UTC, cocahack commented on README.md
> +| 주문 상태       | order status     | 손님의 주문 진행 상태                        |
제안주신 내용은 모델링 단계에서 해야할 내용이라고 생각해서 따로 나누지는 않았습니다.

용어 사전이라는 단어때문에 정책이나 상태와 같은 내용은 최대한 덜어내고 적어야한다고 생각했는데, 리뷰어님은 어떻게 생각하시는지요?

2023-09-02 09:47 UTC, kyucumber commented on README.md
> +| 주문 상태       | order status     | 손님의 주문 진행 상태                        |
말씀하신 것 처럼 용어 사전은 가볍게 가져가는게 좋겠지만, 저는 주문에 대한 이해를 돕기 위해서 충분히 추가될 수 있는 내용이라 생각합니다.

2023-09-02 09:51 UTC, kyucumber commented on README.md
> +| 주문 테이블      | order table      | 매장에서 식사가 가능한 테이블                |
주문이라는 이름이 prefix로 붙긴 하지만 주문 테이블과 주문은 생성 및 삭제에 대한 라이프사이클이 완전히 다릅니다.

주문 테이블 컨텍스트와 주문 컨텍스트를 분리할 필요는 없을까요?

2023-09-02 09:52 UTC, kyucumber requested changes
피드백 잘 반영해주셨습니다.

추가 코멘트 남겨두었는데 확인 부탁드립니다.

https://github.com/next-step/ddd-strategic-design/pull/256/files#r1313795817
https://github.com/next-step/ddd-strategic-design/pull/256/files#r1313796300

2023-09-02 12:34 UTC, cocahack reviewed
코멘트 주신 내용 반영했습니다. 

- 주문 컨텍스트 안에 유형별 주문이 있다고 생각하고 사전을 분리했습니다.
- 주문 테이블은 별도의 컨텍스트로 나누기에는 비즈니스 로직이 비교적 간단하다고 생각하였습니다. 그래서 따로 컨텍스트로 나누지는 않았고, 대신 매장 주문의 하위에 위치시켜서 둘 간의 연관성을 나타내보았습니다.

2023-09-03 02:54 UTC, kyucumber approved these changes
용어사전 잘 정리해주셨습니다.

다음 단계 진행을 위해 머지하겠습니다.

2023-09-03 02:54 UTC, merged