용어사전 정리
next-step/ddd-strategic-design pull request #262
Opened 2023-09-01 06:57 UTC by kymiin

kitchenpos 용어들에 대해 정리해 보았습니다.

그럼 잘 부탁드립니다!
감사합니다. :grinning:

2023-09-01 15:57 UTC, wlroh requested changes
경윤님 안녕하세요 :)
두번째 미션을 함께할 노웅래입니다.
미션 고생많으셨습니다 👍 
코멘트 달았는데요, 확인 부탁드려요!

2023-09-01 15:57 UTC, wlroh commented on README.md
> +### 음식
컨텍스트 단위로 잘 분리해주셨네요 💯 
용어사전은 컨텍스트 안에서 진정한 힘을 발휘하죠! 👍

2023-09-01 15:57 UTC, wlroh commented on README.md
> +| 음식 이름 | product name  | 음식의 이름 (비속어가 포함될 수 없음)       |
비속어에 대한 용어정리도 해보는 것은 어떤가요?
비속어가 어떤 것을 뜻하는 것일까? 단순 욕설이 포함만 안되는 것인가? 그렇다면, 은어가 포함돼도 괜찮을가? 이런저런 고민들이 생겨요.

2023-09-01 15:57 UTC, wlroh commented on README.md
> +| 음식 가격 | product price | 음식의 가격 (0원 이상이어야 함)          |
용어 정의 뿐만아니라 요구사항도 같이 정리해주셔서 좋네요 💯

2023-09-01 15:57 UTC, wlroh commented on README.md
> +| 테이블 이름    | order table name | 주문 테이블 이름 |
주문 테이블이 무엇인지도 정리하는 것은 어떤가요?

2023-09-01 15:57 UTC, wlroh commented on README.md
> +| 서빙 완료 | served         | 조리가 완료된 음식을 손님한테 서빙이 끝난 상태                 |
배달주문건으로 보면 설명이 애매하네요. 🤔  
손님에게 조리가 완료된 음식을 서빙하는 것일까요?

2023-09-01 15:57 UTC, wlroh commented on README.md
> +### 주문
주문에서 용어를 더 도출해보는 것은 어떤가요?
예를들면, 주문에서 봐라보는 메뉴와 메뉴에서 봐라보는 메뉴가 같은 메뉴일까요?

2023-09-01 15:57 UTC, wlroh commented on README.md
> +| 주문 타입 | order type     | eat-in |
주문 타입 용어가 공통에도 있고, 각각의 주문건에도 있네요

2023-09-03 23:38 UTC, kymiin commented on README.md
> +| 음식 이름 | product name  | 음식의 이름 (비속어가 포함될 수 없음)       |
네, 말씀주신 내용 고민해보고 다시 정리 하였습니다

2023-09-04 13:53 UTC, wlroh approved these changes
경윤님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 
코멘트 적은 것이 있는데, 다음 미션하시면서 같이 확인부탁드려요!
다음 미션도 화이팅입니다 🔥

2023-09-04 13:53 UTC, wlroh commented on README.md
> +| 주문 시간 | order Date     | 주문을 한 시간                                 |
각각의 주문 유형별로 정리해주셔서 해당 내용은 제거하는 것은 어떤가요?
각 주문 상태가 각각의 주문 유형별로 의미하는 바가 다르게 느껴져서 공통보다는 각각의 주문별로 정리된 것이 더 이해하기 좋은 것 같아요.

2023-09-04 13:53 UTC, merged