1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #264
Opened 2023-09-01 14:11 UTC by Saerang

용어사전 만들기 짝이랑 같이 진행했습니다.
잘부탁드립니다 !

2023-09-02 10:16 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-09-02 10:16 UTC, kyucumber commented on README.md
> +| 주문 상태  | orderStatus     | 주문이 처리되고 있는 상황을 표현한 상태. 주문 상태에는 대기 중, 접수됨, 서빙됨, 배달 중, 배달 완료, 주문 완료가 있다. |
주문 상태의 흐름이 어떻게 되는지 한눈에 들어오지 않는 것 같아요. 그리고 주문 유형(배달, 포장 등)에 따라도 상태의 흐름이 다른데 이 부분을 한눈에 보이게 아래처럼 정리하면 어떨까요?

- 배달 주문
  - 대기 -> 접수 -> 배달 시작 -> 배달 완료 -> 완료
- 포장 주문
  - 대기 -> 접수 -> 서빙 -> 완료

2023-09-02 10:16 UTC, kyucumber commented on README.md
> +| 주문 테이블 | orderTable      | 매장 주문한 고객이 식사하는 테이블. 주문 테이블을 할당받아야 매장 주문이 가능하다                          |
주문이라는 이름이 prefix로 붙긴 하지만 주문 테이블과 주문은 생성 및 삭제에 대한 라이프사이클이 완전히 다릅니다.

주문 테이블 컨텍스트와 주문 컨텍스트를 분리할 필요는 없을까요?

2023-09-02 10:16 UTC, kyucumber commented on README.md
> +### 주문
요건 생각하시는 바운디드 컨텍스트를 기준으로 용어를 나누어주셨다고 보면 될까요?

2023-09-02 10:16 UTC, kyucumber commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
"메뉴의 이름에는 비속어가 포함될 수 없다."와 관련해 비속어와 관련된 내용을 용어사전에 정리할 필요는 없을까요? 상품도 공통적으로 해당하는 부분이라 나누신 바운디드 컨텍스트 이외에 공통 영역에 대한 용어로 정리해주셔도 좋을 것 같아요.

https://github.com/next-step/ddd-strategic-design/blob/b75942652dec10e7f21058610bb9af5016aab476/src/main/java/kitchenpos/infra/DefaultPurgomalumClient.java#L20

2023-09-02 10:16 UTC, kyucumber commented on README.md
> +| 주문     | order           | 고객이 원하는 상품을 구매하는 행위                                                     |
주문 항목(order line item)에 대한 용어도 정리하면 어떨까요?

2023-09-02 12:18 UTC, Saerang commented on README.md
> +| 주문     | order           | 고객이 원하는 상품을 구매하는 행위                                                     |
order line item은 위에 있습니다.

2023-09-02 12:19 UTC, Saerang commented on README.md
> +| 주문 상태  | orderStatus     | 주문이 처리되고 있는 상황을 표현한 상태. 주문 상태에는 대기 중, 접수됨, 서빙됨, 배달 중, 배달 완료, 주문 완료가 있다. |
처음에는 주문유형에 따라 나눠보려고 했는데, 용어사전이라는게 용어들 정리하는것 같아서 별도로 나누진 않았습니다.
근데 용어사전이 바운디드 컨텍스트를 나눠서 시간에 흐름에 맡게 정리하는건가요?

2023-09-02 12:22 UTC, Saerang commented on README.md
> +### 주문
그냥 주문과 큰그림만 분리하였습니다.

2023-09-02 12:23 UTC, Saerang commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
비속어도 추가되면 좋을 것 같네요 👍

2023-09-02 14:31 UTC, Saerang commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
바운디드 컨텍스트를 나누게 되면 결과적으로, 도메인 용어들이 바운디드 컨텍스트 내에 사용용도가 다 다를텐데 공통이라는게 있을 수 있을까요? 
당장은 비속어라는 뜻을 상품이나, 메뉴나 같게 사용한다고 해도 나중에는 다르게 변할 수 있어서 이부분은 각각 들어가는게 맞아보이는데 어떻게 생각하시나요?

2023-09-02 14:37 UTC, Saerang commented on README.md
> +| 주문 테이블 | orderTable      | 매장 주문한 고객이 식사하는 테이블. 주문 테이블을 할당받아야 매장 주문이 가능하다                          |
분리해야겠네요 👍

2023-09-02 14:38 UTC, Saerang commented
전반적으로 바운디드 컨텍스트를 다 분리하였습니다.

2023-09-03 02:46 UTC, kyucumber requested changes
안녕하세요.

컨텍스트별로 나누어 용어를 잘 정리해주셨네요. 코멘트 남겨주신 부분에 답변 남겨두었고 컨텍스트 분리와 관련해 추가 코멘트 남겨두었으니 확인 부탁드릴게요.

2023-09-03 02:46 UTC, kyucumber commented on README.md
> +| 주문 상태  | orderStatus     | 주문이 처리되고 있는 상황을 표현한 상태. 주문 상태에는 대기 중, 접수됨, 서빙됨, 배달 중, 배달 완료, 주문 완료가 있다. |
용어사전이 꼭 바운디드 컨텍스트별로 나뉘어 작성될 필요 없습니다. 다만 저는 비즈니스의 전체에 대한 용어가 한번에 정리되어 있는 것 보다는 나누어진 컨텍스트별로 나누어 용어를 살펴보면 더 빠르게 잘 이해할 수 있어 나누어 작성되는게 좋다고 생각합니다.

그리고 주문 유형별로 상태의 흐름을 위와 같이 정리하는게 어떨까 제안드린 부분은, 주문 유형별로 상태가 어떻게 흘러가는지를 잘 모르고 주문 상태나 유형이라는 용어를 완벽히 잘 이해하긴 어렵다고 생각했기 때문입니다. 이 작업 또한 용어사전 정리를 위해 필수적으로 수행되어야 하는 부분은 아닙니다.

2023-09-03 02:46 UTC, kyucumber commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
> 바운디드 컨텍스트를 나누게 되면 결과적으로, 도메인 용어들이 바운디드 컨텍스트 내에 사용용도가 다 다를텐데 공통이라는게 있을 수 있을까요? 당장은 비속어라는 뜻을 상품이나, 메뉴나 같게 사용한다고 해도 나중에는 다르게 변할 수 있어서 이부분은 각각 들어가는게 맞아보이는데 어떻게 생각하시나요?

현재는 비속어와 관련된 부분을 상품과 메뉴가 동일하게 "https://www.purgomalum.com/service/containsprofanity" 외부 API를 사용하고 있습니다. 만약 지금 나누어주신 메뉴와 상품 바운디드 컨텍스트를 하나의 팀에서 관리하고 있다면 공통적인 부분으로 추출해 정리해두더라도 이상하지 않다고 보이네요.

말씀하신것 처럼 이후에 상품, 메뉴가 나타내는 비속어가 달라질 수 있을것 같은데요, 그 땐 달라진 부분을 용어사전에 반영하면 될 것 같습니다. 

그리고 이후에 상황에 따라 상품, 메뉴 바운디드 컨텍스트별로 팀이 쪼개지게 되면 같이 정리한 공통 용어도 의미가 없어질 수 있겠네요.

말이 길어졌는데 요약하면 아래와 같습니다.

1. 지금 상황에선 공통으로 추출되어도 문제가 없다.
2. 이후 비속어와 관련된 부분이 변경되면 용어사전에 반영해야 하며, 팀에서 맡고있는 컨텍스트의 범위에 따라 용어사전의 내용 또한 달라질 수 있다.

2023-09-03 02:46 UTC, kyucumber commented on README.md
> +| 주문     | order           | 고객이 원하는 상품을 구매하는 행위                                                     |
엇 죄송합니다. 제대로 못 봤네요.

2023-09-03 02:46 UTC, kyucumber commented on README.md
> +### 메뉴
메뉴와 메뉴 그룹 컨텍스트를 나누어주셨네요.

메뉴를 만들기 위해 메뉴 그룹이 생성되어 있어야 하는 부분이나, 메뉴 그룹은 생성 이외에 별도로 복잡한 로직이 없는 부분을 고려했을 때 현재 상황에서 메뉴 컨텍스트와 메뉴 그룹 컨텍스트가 나뉘는게 맞을지 고민해보셔도 좋을 것 같아요.

2023-09-03 12:08 UTC, Saerang commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
현재는 하나의 팀이 다 맡고 있다고 보시는건가요? 추후에 나눌 이유가 있다고 하면 분리하는게 좋은데, 당장 없다고 하면 공통으로 풀어도 괜찮을 것 같네요.

2023-09-04 11:56 UTC, kyucumber commented on README.md
> +| 메뉴     | menu          | 하나 이상의 상품으로 구성된 집합, 구매는 메뉴 단위로 이루어짐 |
> 현재는 하나의 팀이 다 맡고 있다고 보시는건가요? 추후에 나눌 이유가 있다고 하면 분리하는게 좋은데, 당장 없다고 하면 공통으로 풀어도 괜찮을 것 같네요.

현재는 하나의 레파지토리 내에 여러 바운디드 컨텍스트들이 합쳐져 있는 상태라 공통으로 풀어도 문제가 없을 것 같아요. 이후 나눠진 컨텍스트별로 정책이 바뀌든, 팀이 분리되든 그때 가서 다시 용어사전을 수정하면 되지 않을까 싶네요.

2023-09-04 11:57 UTC, kyucumber approved these changes
용어사전 잘 정리해주셨습니다.

다음 단계 진행을 위해 머지할게요. 별개로 남겨둔 코멘트 확인 부탁드려요~

https://github.com/next-step/ddd-strategic-design/pull/264#discussion_r1314852838
https://github.com/next-step/ddd-strategic-design/pull/264#discussion_r1314855111

2023-09-04 11:58 UTC, kyucumber commented on README.md
> +### 주문
현재 주문 컨텍스트 하위에 용어만 배달, 포장, 매장으로 나누어주신 것 같습니다. 

주문 컨텍스트가 꽤 복잡한 상태로 보여요. 현재로서는 불필요할 수 있겠지만 이후 코드가 복잡해짐에 따라 주문 컨텍스트가 또 한번 배달 주문, 포장 주문, 매장 주문 컨텍스트로 나뉠 수 있을지와 같은 부분도 고민해보시면 좋겠습니다.

2023-09-04 11:59 UTC, merged

2023-09-04 12:00 UTC, kyucumber commented on README.md
> +### 주문
아마 이벤트 스토밍 실습 때 관련 이야기를 나누셨을 것 같네요! 참고차 적어둡니다.

2023-09-05 12:50 UTC, Saerang commented on README.md
> +### 주문
주문을 위에 두지말고, 배달주문, 포장주문, 매장주문을 나누라는 뜻일까요?