🚀 2단계 - 모델링 하기Step2
next-step/ddd-strategic-design pull request #268
Opened 2023-09-02 04:18 UTC by ryuhistory

안녕하세요. 2단계 모델링 하기 정리 했습니다.
모델링에 대한 
팀 전체에 사용하는 용어로 사용 하려 고민을 하다보니
단어 선택이 참 어렵게 느껴지네요. 최대한 개발관련 용어는 지양 하도록 작성했습니다.
감사합니다.

2023-09-02 18:48 UTC, sihoony requested changes
안녕하세요. 제형님!
2단계 미션도 잘 진행해 주셨네요. 👍 
간단한 코멘트를 추가했으니 확인해주세요~! 
즐거운 주말되세요~! 😄

2023-09-02 18:48 UTC, sihoony commented on README.md
>  ## 모델링
모델링의 대상을 넓혀보는 건 어떨까요? (상품, 주문 테이블 등...)
우리가 구현에 필요한 도메인이 어떤것들이 있는지 작성해보면 개발해야하는 항목들이 명확하게 보일 수 있겠네요~! 😄

2023-09-02 18:48 UTC, sihoony commented on README.md
> +### 메뉴
메뉴라는 도메인의 기능 외 속성들을 정의해보면 어떨까요?
메뉴가 갖고 있는 `상품의 이름`, `상품의 가격` 들을 정의하면 명확해 질 것 같네요~! 😄

2023-09-02 18:48 UTC, sihoony commented on README.md
> +### 주문
속성들을 정의해보면 좋을 것 같네요. 😄

2023-09-03 11:40 UTC, ryuhistory commented on README.md
>  ## 모델링
말씀처럼 처음 모델링시에는 최대한 데이테일하게 모델링을 나누어서 
하는게 더 좋을거 같네용 😄

2023-09-04 00:28 UTC, sihoony approved these changes
안녕하세요. 제형님,
피드백 잘반영해 주셨습니다. 다음 미션을 위해서 Merge하겠습니다. 👍 
즐거운 하루 되세요~! 😄

2023-09-04 00:28 UTC, sihoony commented on README.md
> +   - 메뉴이름, 메뉴가격, 메뉴종류, 메뉴그룹, 등록할 상품정보는 필수로 입력되야 한다.
속성과 기능이 명확하게 구분된다면, 개발에 쉽게 적용할 수 있겠네요~! 😄

2023-09-04 00:28 UTC, merged