Step1: 용어 사전 만들기
next-step/ddd-strategic-design pull request #272
Opened 2023-09-02 19:07 UTC by chyjeon

안녕하세요 리뷰어님! 만나게 되어 반갑습니다 :)
step1 용어사전을 작성하여 올렸습니다.
잘부탁드립니다!!

2023-09-03 15:40 UTC, wlroh requested changes
창열님 안녕하세요 :)
이번 미션을 함께할 노웅래입니다.
미션 고생하셨습니다 👍 
코멘트 달았는데요, 확인부탁드려요!

2023-09-03 15:40 UTC, wlroh commented on README.md
> +### 메뉴그룹
바운디드 컨텍스트 단위로 용어 정리해주셨네요 👍 
용어사전은 컨텍스트 내에서 진정한 힘을 발휘하죠

2023-09-03 15:40 UTC, wlroh commented on README.md
> +| 상품       | product             | kitchenPos가 판매하는 물건      |
메뉴의 설명은 `고객이 구매 가능한 상품`이고, 메뉴 상품 또한 `메뉴에 포함된 상품`이라고 설명이 되어 있네요.
그러면, `메뉴 == 상품` 
메뉴 상품은 `고객이 구매 가능한 상품` 에 포함된 상품 으로도 볼 수 있는데 혼란스러운거 같아요.

2023-09-03 15:40 UTC, wlroh commented on README.md
> +| 상품       | product             | kitchenPos가 판매하는 물건      |
추가로, 예시를 추가해보는 것도 이해하는데 더 좋을 것 같은데 어떻게 생각하시나요?

2023-09-03 15:40 UTC, wlroh commented on README.md
> +| 주문 유형    | orderType           | 주문 방법                    |
주문 유형 중에 어떤 것들이 있는지도 같이 정리해주는 것은 어떤가요?
현재는 어떤 주문유형이 있는지 알기 힘든 구조네요.

2023-09-03 15:40 UTC, wlroh commented on README.md
> +| 배달됨      | DELIVERED           | 상품이 배송지에 배달 완료됨          |
주문 상태에 대해서도 어떤 종류가 있는지 적어보는 것은 어떤가요?
그리고, 설명에는 용어를 통일해보는 것은 어떤가요?
대기중의 경우 `확인` 이라는 용어를 사용했는데, `승인`이라는 용어와 다른 것인가 생각도 들어서요.

2023-09-03 15:40 UTC, wlroh commented on README.md
> +| 제공됨      | SERVED              | 주문 접수 후 상품이 준비됨          |
`제공됨` 에 대한 설명으로는 준비됨이라고 나와있어, 상품이 전달이 안되고 준비까지만 된 것 인가? 생각이 들어요.

2023-09-03 16:01 UTC, chyjeon commented on README.md
> +| 주문 유형    | orderType           | 주문 방법                    |
함께 작성하겠습니다!

2023-09-03 16:01 UTC, chyjeon commented on README.md
> +| 배달됨      | DELIVERED           | 상품이 배송지에 배달 완료됨          |
종류도 함께 작성하겠습니다! 같은 용어를 다르게 사용했네요.. 통일하겠습니다

2023-09-03 16:01 UTC, chyjeon commented on README.md
> +| 제공됨      | SERVED              | 주문 접수 후 상품이 준비됨          |
의미를 명확하게 작성하겠습니다!

2023-09-03 16:22 UTC, chyjeon commented on README.md
> +| 상품       | product             | kitchenPos가 판매하는 물건      |
앗 그러네요.. 용어를 수정해보겠습니다.. 예시도 고민해보겠습니다! :)

2023-09-04 13:43 UTC, wlroh approved these changes
창열님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 
코멘트 달았는데요, 다음 미션 진행하시면서 같이 반영해주세요.
다음 미션도 화이팅입니다 🔥

2023-09-04 13:43 UTC, wlroh commented on README.md
> +
예시를 설명란으로 옮기는 것은 어떤가요?
한 눈에 설명과 예시를 볼 수 있어, 이해하기 수월하지 않을까해요.

2023-09-04 13:43 UTC, wlroh commented on README.md
> +| 제공됨      | SERVED              | 주문 접수 메뉴를 고객에게 전달함                                           |
배달주문의 경우는 고객에게 전달하는 것이 아닌거같아요.
주문별로 정리해보는 것은 어떤가요?

2023-09-04 13:43 UTC, wlroh commented on README.md
> +| 배달원      | KitchenridersClient | 배달하는 내용에 대한 설명                                               |
배달하는 내용에 대한 설명이라는 것이 어떤 뜻일까요?
좀더 다듬어보면 좋을 것 같아요.

2023-09-04 13:43 UTC, wlroh commented on README.md
> +| 완료       | COMPLETED           | 상품이 고객에게 제공됨                                                 |
매장 식사의 경우는 상품이 고객에게 제공된다는 설명은 어색한 것 같아요.

2023-09-04 13:43 UTC, merged

2023-09-04 16:38 UTC, chyjeon commented on README.md
> +| 완료       | COMPLETED           | 상품이 고객에게 제공됨                                                 |
유형별로 나누어 생각하겠습니다!

2023-09-04 16:38 UTC, chyjeon commented on README.md
> +| 배달원      | KitchenridersClient | 배달하는 내용에 대한 설명                                               |
더 어울리게 수정하겠습니다

2023-09-04 16:38 UTC, chyjeon commented on README.md
> +| 제공됨      | SERVED              | 주문 접수 메뉴를 고객에게 전달함                                           |
주문별로 정리하겠습니다!!

2023-09-04 16:38 UTC, chyjeon commented on README.md
> +
새로 정리하겠습니다!