1단계: 용어 사전 만들기
next-step/ddd-strategic-design pull request #300
Opened 2023-09-05 13:56 UTC by JiwonDev

오프라인 페어로 용어를 한번 정리한 후, 각자 더 정리해서 용어사전을 만들어 보았습니다. ( 다른 PR https://github.com/next-step/ddd-strategic-design/pull/290 )

리뷰 잘부탁드립니다 😀

2023-09-06 14:56 UTC, Hyeon9mak requested changes
안녕하세요 지원님, 용어 사전 만들기 잘 진행해주셨습니다.
이미지를 통해서 메뉴그룹과 메뉴, 상품간의 관계를 표현해주신 부분 매우 인상적입니다 😄 👍 
주문 또한 어떤 느낌으로 주문을 이해하고 계신지 한눈에 파악할 수 있었어요.
우선 용어사전에 집중해서 코멘트 몇 가지 남겼습니다.

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +| 메뉴 그룹  | MenuGroup     | 메뉴들을 그룹화하는 카테고리를 의미한다. <br> 메뉴판을 의미하지는 않는다. 고객이 메뉴그룹 자체를 주문할 수는 없다. <br> 예를 들어 `디저트, 메인 요리, 사이드` 등과 같이 여러 메뉴들을 분류할 때 사용된다.             |
상세한 예시를 들어 설명해주신 덕분에 어떤 모습일지 상상하며 용어를 이해할 수 있네요 👍

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +| 메뉴     | Menu          | 사용자가 선택 가능한 판매 가능한 서비스의 항목을 의미한다. <br> 메뉴는 하나 이상의 메뉴상품을 가지고 있으며, 이름, 가격, 전시여부와 같은 정보를 지닌다. <br> 예를 들어 `양념치킨, 콜라, 배달료, 룸사용료` 등이 될 수 있다. |
양념치킨, 콜라는 메뉴로서 상상이 되는데, 배달료와 룸사용료는 어떤 걸까요? 차림비 같은 느낌?

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +   - `메뉴주문불가(hide)` | 메뉴가 판매중단된 상태, 고객에 노출되지 않는다.
`display` 라는 영문명과 `주문가능`이라는 한글명, `hide` 라는 영문명과  `주문불가`라는 한글명이 잘 매치되지 않는 것 같아요.
또한 설명에서는 판매중/판매중단으로 다른 표현이 사용되네요 😱 
추후 비즈니스가 고도화됨에 따라 가시적 / 기능적으로 나눠서 주문가능여부가 갈릴 수도 있을텐데, 이런 경우 용어를 재정의하기 어려울 것 같아요.
(기존 구성원들이 합의하고 이해한 용어를 바꾸는 비용이 엄청나기 때문)
영문명과 한글명, 설명을 서로 통일해보는 건 어떨까요?

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +   - `상품가격(productPrice)` | 상품의 가격을 의미한다. 상품 가격은 0원일 수 있다.
메뉴그룹, 메뉴, 상품 관련 용어들을 위 한글명/영문명/설명에 정리된 내용과 묶어서 정리하는건 어떻게 생각하시나요?

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +| 주문유형  | OrderType     | 주문은 하나의 주문유형을 가진다. <br> 주문유형 [`배달(Delivery), 포장(TakeOut) 매장식사(EatIn)`]                                                    |
주문을 관심사 경계(바운디드 컨텍스트)에 따라 나눌 것이냐, 타입으로 나눌 것이냐에 따라 주문에 대한 용어정의법이 달라질 수 있겠어요!
(바운디드 컨텍스트를 이용할 경우 주문 타입이 사라질 수 있음)
지원님은 어떤 방식을 더 선호하시나요?

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +  - `주문내역리스트(orderLine)` | 주문한 메뉴 리스트
누가 주문했는지 대상을 설명하는 것도 좋아보여요 😄 👍

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +| 매장 테이블 | OrderTable    | 고객이 앉아 음식을 먹을 수 있는 테이블을 의미하며 매장식사 주문에 사용된다. <br> 주문 테이블은 점유여부, 최대 손님수등의 정보를 가지고 있다.                                       |
> 고객이 앉아 음식을 먹을 수 있는 테이블을 의미하며 매장식사 주문에 사용된다.

역시나 상세한 설명 👍 👍 
새로 합류한 개발자, 기획자도 읽고 어떤 용어인지 한방에 이해할 수 있겠어요.

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +  - `주문종료됨(orderCompleted)` | 주문이 종료된 경우, 성공여부와 상관없이 더 이상 진행 할 수 없는 주문상태
엄청 상세한 용어 설명이네요 👍 👍 
역시나 주문을 어떻게 설명하냐에 따라 용어 정리가 달라질 수도 있겠어요.

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +  - `점유중이지 않은 매장테이블(unoccupied table)` | 사용중이지 않은 빈 테이블
명확한 정리네요 😄 👍

2023-09-06 14:56 UTC, Hyeon9mak commented on README.md
> +  - `비속어(profanity)` | 사전적으로 비속한[불경스런] 말, 주문 또는 메뉴의 이름으로 사용할 수 없는 단어를 의미한다.
공통으로 사용되는 용어까지 추출하여 개별정리!! 💯 👍

2023-09-08 11:00 UTC, JiwonDev commented on README.md
> +| 메뉴     | Menu          | 사용자가 선택 가능한 판매 가능한 서비스의 항목을 의미한다. <br> 메뉴는 하나 이상의 메뉴상품을 가지고 있으며, 이름, 가격, 전시여부와 같은 정보를 지닌다. <br> 예를 들어 `양념치킨, 콜라, 배달료, 룸사용료` 등이 될 수 있다. |
매장 POS라고 생각하고 고민해보니, 실제 사용시 주문내역에 `추가배달료` 같은 서비스 추가요금도 많이 사용하더라구요. 그걸 생각해서 `메뉴 == 음식` 이 아닌 다양한 예시를 적어봤습니다!

예를 들어 횟집의 차림비, 도서산간 추가배달료등이 될 수 있습니다.

2023-09-08 11:00 UTC, JiwonDev commented on README.md
> +   - `메뉴주문불가(hide)` | 메뉴가 판매중단된 상태, 고객에 노출되지 않는다.
음.. 개인적으론 영어명을 좀 더 명확하게 바꾸고싶긴한데
이미 코드에서 hide, display가 사용중이니 그대로 따라가서 `메뉴 노출됨` `메뉴 숨겨짐`으로 변경하겠습니다. 😀
```md
   - `메뉴노출됨(display)` | 메뉴가 노출된 상태, 고객이 주문할 수 있다.
   - `메뉴숨겨짐(hide)` | 메뉴가 숨겨진 상태, 고객이 주문할 수 없다.
```

2023-09-08 11:00 UTC, JiwonDev commented on README.md
> +   - `상품가격(productPrice)` | 상품의 가격을 의미한다. 상품 가격은 0원일 수 있다.
비즈니스에 있어 핵심이 되는 단어들`(상품, 메뉴, 주문)`과 핵심은 아니지만 관련된 단어들을 나눠서 보여주고 싶었어서 이렇게 해놨긴합니다.

합쳐서 쭉 나열식으로 적는게 더 보기좋을까요? 😀

2023-09-08 11:00 UTC, JiwonDev commented on README.md
> +| 주문유형  | OrderType     | 주문은 하나의 주문유형을 가진다. <br> 주문유형 [`배달(Delivery), 포장(TakeOut) 매장식사(EatIn)`]                                                    |
말이 살짝 헷갈리는데, 아래 둘중 무엇을 선호하냐고 여쭤보신거죠?
- 관심사경계: 주문 자체를 `배달주문`, `포장주문`, `매장주문`으로 나눠 다른 영역으로 본다는 말.
- 타입: 모두 같은 주문인데, 타입으로 구분하여 분기처리

보통 처음에 타입으로 구분하는걸 선호합니다. 도메인이 복잡해지기 전에는 `어디까지를 바운디드 컨텍스트로 나눌것인가?` 고민하는 시간 자체가 아깝고 잘 나누기도 어렵더라구요.

다만 기능이 추가되면서 하나로 보기엔 애매한 부분이 많아 개발이 어려워졌을 그 시점, 즉 필요한 시점에 리팩토링을 통해 나누는게 맞다고 생각하긴해요!

2023-09-08 11:00 UTC, JiwonDev commented on README.md
> +  - `주문내역리스트(orderLine)` | 주문한 메뉴 리스트
`고객이 주문한 메뉴 리스트` 로 변경하겠습니다 👍

2023-09-10 04:35 UTC, Hyeon9mak approved these changes
안녕하세요 지원님, 질문에 대한 생각 공유해주셔서 이해하기 한결 좋았습니다.
답변 코멘트 확인해주시고 바로 다음 단계로 넘어가면 될 것 같아요. 💪

2023-09-10 04:35 UTC, Hyeon9mak commented on README.md
> +   - `상품가격(productPrice)` | 상품의 가격을 의미한다. 상품 가격은 0원일 수 있다.
취향차이겠지만 저는 용어사전은 말 그대로 용어와 그들을 설명하는 내용으로 이루어져있으므로, 핵심/비핵심을 나눌 필요는 없다고 생각했어요.

2023-09-10 04:35 UTC, Hyeon9mak commented on README.md
> +| 주문유형  | OrderType     | 주문은 하나의 주문유형을 가진다. <br> 주문유형 [`배달(Delivery), 포장(TakeOut) 매장식사(EatIn)`]                                                    |
넵, 그것도 좋은 방법이라고 생각합니다.
이벤트 스토밍 모임에서 이미 경험하셨듯 관심사 경계를 나누는 것과 타입을 나누는 것은
비즈니스 복잡도가 높아지면 진행될 수도 있겠지만, 함께 일하는 팀원들과 이벤트스토밍을 통해서
어떻게 합의를 하느냐에 따라 결정할 수도 있을 것 같아요.
이벤트 스토밍 모임에 참여하실 때 경계를 나누셨을텐데 타입을 통해 나누셨길래 궁금했습니다.

2023-09-10 04:35 UTC, merged