1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #315
Opened 2023-09-08 05:51 UTC by HackSung

안녕하세요 😄 
페어로 지정되신 분이 연락 드리기도 전에 이미 1단계를 완수하고 머지가 되셨고 
저는 리뷰진도가 늦은 관계로 혼자서 용어 사전을 정의했습니다.

참고로 용어 사전을 상품, 메뉴, 주문 세가지로 분류하였고
주문의 경우 주문 유형에 상관없이 공통으로 사용되는 단어와
주문 유형별 사용되는 단어로 나누어 보았습니다.

감사합니다.

2023-09-08 18:39 UTC, wlroh requested changes
학성님 안녕하세요 :)
미션 고생하셨습니다 👍 
코멘트 추가했는데요, 확인 부탁드려요!

2023-09-08 18:39 UTC, wlroh commented on README.md
> +| 비속어   | Profanity     | 상품 이름에 포함될 수 없는 단어 |
상품 도메인 용어 정리 잘해주셨네요 👍 💯

2023-09-08 18:39 UTC, wlroh commented on README.md
> +| 주문 항목  | Order Line Item    | 주문에 포함된 메뉴                                      |
도메인으로 나누신 것이여서 현재상태로 둬도 괜찮을 것 같은데, 용어사전은 바운디드 컨텍스트 안에서 진정한 힘을 발휘한다고 생각해요
추후 바운디드 컨텍스트로 나눌때는 주문컨텍스트에서 이야기하는 메뉴와 메뉴 컨텍스트에서 이야기하는 메뉴는 같을까요?
이부분은 바운디드 컨텍스트 나눌때 더 이야기해보면 좋을 것 같아요

2023-09-08 18:39 UTC, wlroh commented on README.md
> +| 주문 서빙  | Order Serving      | 주문된 음식이 조리 완료되어 손님에게 전달 직전의 상태로 수락된 주문에 한해서 가능  |
배달 주문의 경우는 전달되는 주체가 손님 대신 배달 대행사로부터 나온 기사님이지 않을까요? 🤔

2023-09-08 18:39 UTC, wlroh commented on README.md
> +| 테이블 점유 상태 | Table Occupancy Status | 주문 테이블의 상태로 손님이 착석중인지 비어 있는지 알려주는 상태 |
`주문 테이블의 상태로, 손님이 착성중인지 비어 있는지 알려주는 상태` 혹은
`주문 테이블에 손님이 착성중인지 비어 있는지 알려주는 상태` 는 어떤가요?
쉼표없이 쭉 이어지다 보니 처음 읽었을 때 이해못하고 여러번 읽으면서 이해했어요

2023-09-08 18:39 UTC, wlroh commented on README.md
> +| 배달 완료 | Delivery Complete | 주문을 배달 완료한 상태로 배달 시작한 주문에 한해서 가능 |
꼼꼼하게 잘 정리해주셨네요 👍 💯

2023-09-09 00:59 UTC, HackSung commented on README.md
> +| 주문 항목  | Order Line Item    | 주문에 포함된 메뉴                                      |
넵~ 서로 다른 바운디드 컨텍스트에서는 동일 용어가 나타나더라도 의미는 다를 수 있음을 기억하겠습니다. 😄

2023-09-09 01:02 UTC, HackSung commented on README.md
> +| 테이블 점유 상태 | Table Occupancy Status | 주문 테이블의 상태로 손님이 착석중인지 비어 있는지 알려주는 상태 |
네 쉽고 명확하게 의미전달될 수 있도록 표현에 더 신경쓰겠습니다. 😄

2023-09-09 01:06 UTC, HackSung commented on README.md
> +| 주문 서빙  | Order Serving      | 주문된 음식이 조리 완료되어 손님에게 전달 직전의 상태로 수락된 주문에 한해서 가능  |
네에 전달하는 주체를 표현은 안했는데 매장 직원인지 배달기사인지 명시하는게 좋다는 의미이신거죠?

2023-09-09 17:40 UTC, wlroh approved these changes
학성님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 
간단한 피드백 추가했는데요, 다음 미션 진행하면서 확인부탁드려요!
다음 미션도 화이팅입니다 🔥

2023-09-09 17:40 UTC, wlroh commented on README.md
> +| 주문 서빙  | Order Serving      | 주문된 음식이 조리 완료되어 매장 직원이나 배달 기사가 손님에게 전달하기 직전의 상태로 수락된 주문에 한해서 가능 |
배달 주문의 경우 `주문 대기` &rarr; `주문 수락` &rarr; `주문 서빙` &rarr; `배달 시작` &rarr; `배달 완료` &rarr; `주문 완료` 상태로 알고 있어요
`주문 서빙`이 배달 기사가 손님에게 전달하기 적전의 상태라고 보면 이미 배달이 시작 된 이후인가로 혼동될 수도 있을 것 같아요

2023-09-09 17:40 UTC, wlroh commented on README.md
> +| 주문 서빙  | Order Serving      | 주문된 음식이 조리 완료되어 손님에게 전달 직전의 상태로 수락된 주문에 한해서 가능  |
주문의 유형에 따라 `주문 서빙` 에 대한 용어 설명이 다를 것 같다는 의미였어요~
학성님 말씀처럼 주체에 대한 내용도 포함되고 손님에게 전달 직전이라는 의미가 배달주문에서는 적잘하지 않은 의미로 보여졌어요.
상세 내용은 아래 적어두었어요 확인 부탁드려요.

2023-09-09 17:40 UTC, merged