feat(step3): 기능우선 패키지 구성
next-step/ddd-strategic-design pull request #321
Opened 2023-09-09 03:05 UTC by chyjeon

안녕하세요 리뷰어님! 리뷰 감사드립니다 :)
step2를 마무리하고, 마지막인 step3를 작성하여 올렸습니다.
마지막 단계도 잘부탁드립니다!!

2023-09-09 18:13 UTC, wlroh commented
주문 컨텍스트의 경우 너무 포괄적으로 구성되어 있고, 그 외 컨텍스트가 너무 세분화되어있는 것 같아요.
바운디드 컨텍스트 조정을 다시 해보면 어떨까요? 
너무 고민이 되시면 편하게 DM 주셔도 좋아요

2023-09-09 18:14 UTC, wlroh requested changes
창열님 안녕하세요 :)
미션 고생하셨습니다 👍 
코멘트 달아놓은것이 있는데요, 확인부탁드려요!

2023-09-09 18:14 UTC, wlroh commented on src/main/java/kitchenpos/common/infra/DefaultPurgomalumClient.java
> +package kitchenpos.common.infra;
common 패키지를 통해 공통으로 사용되는 비속어를 두셨네요 👍 💯 
저는 common 패키지는 양날의 검이라고 생각해요. 장점도 많지만, 장점이 바로 단점으로도 바뀔 수 있다고 생각하고요.
같이 고민해보면 좋을 것 같아요.

2023-09-09 18:14 UTC, wlroh commented on src/main/java/kitchenpos/common/infra/PurgomalumClient.java
> +package kitchenpos.common.infra;
비속어 체크하는 인터페이스와 구현체 모두 infra 계층에 두셨네요.
infra 계층은 어떤 역할을 하는 계층이라고 생각하세요?
그리고, domain 계층은 어떤 역할을 하는 계층일까요?

이부분은 고민해보면 좋을 것 같아서 이야기 드린 것이여서 이번 미션에 꼭 답변하지 않아도 좋고, 반영하지 않아도 좋아요 😄

2023-09-10 15:19 UTC, chyjeon commented on src/main/java/kitchenpos/common/infra/DefaultPurgomalumClient.java
> +package kitchenpos.common.infra;
혹시 common을 안쓰면 어떤 방법이 있나요? 저는 고민해봤는데 다른 방법이 잘 떠오르지가 않았습니다 :(

2023-09-10 15:20 UTC, chyjeon commented on src/main/java/kitchenpos/common/infra/PurgomalumClient.java
> +package kitchenpos.common.infra;
크게 생각해보지 않았던 부분인데 이부분은 조금 더 생각해보도록 하겠습니다..!

2023-09-11 15:48 UTC, wlroh commented on src/main/java/kitchenpos/common/infra/DefaultPurgomalumClient.java
> +package kitchenpos.common.infra;
common 을 패키지에 구현하지 않고, 각 컨텍스트마다 중복으로 구현하는 방법이 있어요
common 패키지를 사용하면, 동일한 요구사항 변경이 생겼을 때 한번에 수정이 되는 장점이 있지만, 여러 곳에서 common 을 사용하기 때문에 관리가 중요하기도 해요.

2023-09-11 15:55 UTC, wlroh commented
주문 컨텍스트 관련해서 세분화 잘 해주셨어요 👍 
매장 주문컨텍스트에 주문테이블도 같이 위치해주셨네요 👍 👍 
현재 주문관련해서 공통 컨텍스트, 매장주문 컨텍스트, 배달주문 컨텍스트, 포장주문 컨텍스트로 구성해주신 것 같아요.
이럴때는 
```
order
 |- common
    |- domain
 |- delivery
 |- eatin
 |- takeout 
```
처럼 주문 컨텍스트로 세분화해도 좋을 것 같아요 😄

2023-09-11 15:58 UTC, wlroh requested changes
창열님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 👍 
궁금하신 점이 있으실까해서 한번더 요청드려요
다음 리뷰 요청 주시면 머지하겠습니다 😄

2023-09-11 17:01 UTC, chyjeon commented on src/main/java/kitchenpos/common/infra/DefaultPurgomalumClient.java
> +package kitchenpos.common.infra;
그렇군요! 이번과제에서는 크게 다르지 않아 생각하지 않은 부분이었습니다..! 앞으로는 common을 사용할때 그러한 부분을 고려하며 사용하겠습니다!

2023-09-14 13:21 UTC, wlroh approved these changes
창열님 안녕하세요 :)
리뷰가 너무 늦어서 죄송합니다.. 
피드백 잘 반영해주셨어요 👍 👍 
간단한 코멘트 하나 남겼는데 확인부탁드리고,
마지막 미션까지 고생많으셨어요!!
다음 미션도 응원하겠습니다 🔥

2023-09-14 13:21 UTC, wlroh commented on src/main/java/kitchenpos/order/orderEatIn/domain/OrderTable.java
> +package kitchenpos.order.orderEatIn.domain;
매장 주문 컨텍스트에서 저는 2개의 애그리거트가 있다고 보는데요~
매장주문 애그리거트와 주문테이블 애그리거트 기준으로 패키지를 추가해보면 가독성이 더 좋아져요
추가로, 각각의 애그리거트의 하위도메인들의 메서드들의 접근제어자를 default 혹은 protect 로 설정해주면
외부에서 루트 애그리거트를 통해서만 접근하도록 구현이 가능하고요 😄 

```
domain
|- order
|   |- ...
|_ ordertable
    |- ...
```

2023-09-14 13:21 UTC, wlroh commented on src/main/java/kitchenpos/common/infra/PurgomalumClient.java
> +package kitchenpos.common.infra;
해당 내용에 대해서는 다음 단계 미션을 진행하면서 더 고민해볼 수 있는 부분으로 보여져서,
혹시나 미션이 끝나고도 궁금하시면 편하게 연락주세요 😄

2023-09-14 13:22 UTC, merged