🚀 3단계 - 기능 우선 패키지 구성하기
next-step/ddd-strategic-design pull request #336
Opened 2023-09-16 21:39 UTC by Rok93

3단계도 잘 부탁드립니다 현구님 🙏

2023-09-17 01:41 UTC, Hyeon9mak requested changes
안녕하세요 경록님, 패키지 분리 고생하셨습니다.
용어사전, 모델링 중 고민해주신 부분들이 코드로는 표현되지 못한 것 같아 아쉬워요. 😢 
관련해서 코멘트 남겼습니다.

2023-09-17 01:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/external/deliveryagency/DefaultDeliveryAgencyClient.java
> +
2단계 모델링하기에서 경록님은 `배달 대행사(= Delivery Agency)` 를 배달주문 컨텍스트 항목으로 분류하셨어요.
그런데 코드 상에서는 '외부' 라는 패키지로 분류해주셨어요. 😱 

모델링을 정의할 때의 생각과 이를 코드로 표현할 때 생각이 일치되지 않는 모습이에요.
바운디드 컨텍스트를 고민하며 준비한 모델링 과정이 무색해지지 않게끔, 모델링을 기반으로 패키지를 나눠보면 어떨까요?

2023-09-17 01:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/common/domain/OrderLineItem.java
> +package kitchenpos.order.common.domain;
바운디드 컨텍스트 기준에서 "식당에서 바라보는 피자" 와 "길거리 바닥에 떨어져있는 피자" 는 서로 완전히 피자로 취급하죠.
현재 경록님의 패키지 구성에서는 "배달주문의 주문항목" 과 "매장주문의 주문항목", "포장주문의 주문항목" 을 같은 주문항목으로 취급하고 있는 것 같아요.

아마 이런 생각이 계속 드시는 이유는 미션 프로젝트의 규모가 작아서 모든 주문방식에 대해 인지가 가능해지고, '전지적 작가 시점'을 가지고 계셔서인 것 같아요. 
간단한 예시를 들어서, 배달주문 하나에 팀원 200명, 매장주문 하나에 팀원 500명, 포장주문 하나에 팀원 100명으로 이루어진 거대 서비스에서도 과연 서로 같은 주문항목(`OrderLineItem`)을 사용할 수 있을까요? 서로 같은 형태를 유지할 순 있을까요? 아마 각 주문에 특화된 형태로 주문항목이 바뀌어있지 않을까요? 도합 900명의 코드를 common 으로 묶어서 관리할 수 있을까요?

2023-09-17 01:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/common/domain/OrderStatus.java
> +}
각 주문에 특화된 상태가 생겼는데 이제 불필요하지 않을까요? 🤔

2023-09-17 01:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/common/domain/OrderType.java
>      DELIVERY, TAKEOUT, EAT_IN
역시나 사용되지 않을 것 같아요.

2023-09-17 01:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/eatinorder/domain/EatInOrder.java
> +    private OrderStatus status;
매장주문과 포장주문만 common 의 status 를 사용할 이유가 있을까요?
바운디드 컨텍스트에서 정말 common 이라는게 존재할까요? 🤔

2023-09-17 07:37 UTC, Rok93 commented on src/main/java/kitchenpos/order/common/domain/OrderType.java
>      DELIVERY, TAKEOUT, EAT_IN
OrderType은 사용처가 없는데 제거하는걸 깜빡했네요 😅

2023-09-17 09:56 UTC, Rok93 commented on src/main/java/kitchenpos/order/common/domain/OrderLineItem.java
> +package kitchenpos.order.common.domain;
`어설픈 추상화` 생각이 나는 피드백이네요. 
코드 상의 중복을 추상화하기전에 정말로 중복인지 고민해봐야하는 것처럼 정말로 이 컨텍스트가 중복인건지? 를 고민하라는 얘기를 많이 들어봤었는데, 바운디드 컨텍스트와 결이 비슷한지느 모르겠지만 유사한 관점이라고 느껴지네요. 👀

2023-09-17 09:58 UTC, Rok93 commented on src/main/java/kitchenpos/external/deliveryagency/DefaultDeliveryAgencyClient.java
> +
제가 모델링했던 내용 기준으로 패키지 추가로 나누도록 수정했습니다. 😃
(실컷 모델링해두고 막상 패키지에는 반영안한 부분들이 있었네요 😅)

2023-09-17 09:58 UTC, Rok93 commented on src/main/java/kitchenpos/order/common/domain/OrderLineItem.java
> +package kitchenpos.order.common.domain;
> 간단한 예시를 들어서, 배달주문 하나에 팀원 200명, 매장주문 하나에 팀원 500명, 포장주문 하나에 팀원 100명으로 이루어진 거대 서비스에서도 과연 서로 같은 주문항목(OrderLineItem)을 사용할 수 있을까요? 서로 같은 형태를 유지할 순 있을까요? 아마 각 주문에 특화된 형태로 주문항목이 바뀌어있지 않을까요? 도합 900명의 코드를 common 으로 묶어서 관리할 수 있을까요?

직관적으로  어떤 차이점이 있을지 딱 생각나지는 않지만 충분히 각 컨텍스트별로 주문항목 이라는 개념이 달라질 수 있을 것 같아요. 🤔

2023-09-17 10:19 UTC, Rok93 commented on src/main/java/kitchenpos/order/eatinorder/domain/EatInOrder.java
> +    private OrderStatus status;
컨텍스를 분리하면서 컨텍스트에 fit한 개념을 따로 만들어서 그 컨텍스트 내에서만 사용하는 것이 이해는되는데 이렇게 처음부터 다 쪼개놓는게 조금 낯설게 느껴지네요. 🤔

2023-09-18 10:06 UTC, Hyeon9mak approved these changes
안녕하세요 경록님, 정성껏 반영해주신 내역 확인했습니다 👍 👍 
미션 완료 기준을 충분히 만족해주신 것 같고 제 주관적인 생각만 몇 가지 더 남겼습니다.
다음 미션을 진행하시는데 도움이 되면 좋겠습니다.
고생 많으셨습니다. 다음 미션도 화이팅! 💪

2023-09-18 10:06 UTC, Hyeon9mak commented on src/main/java/kitchenpos/deliveryagency/DeliveryAgencyClient.java
> +
<img width="551" alt="image" src="https://github.com/next-step/ddd-strategic-design/assets/37354145/376c1734-f4a2-4332-be29-21fe50dcaf14">

https://github.com/Rok93/ddd-strategic-design/blob/0b4a61ae0bd690b23f522586e0eac2516696e909/README.md

경록님께서 작성해주신 모델링 문서에서 배달업체는 개별 컨텍스트가 아닌 배달주문 컨텍스트에 포함되었던 것 같아요. 아직까진 모델링 때와 형상이 다른거 같아요! 이렇게 구상하신 이유가 있을까요?

2023-09-18 10:06 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/deliveryorder/application/DeliveryOrderService.java
> +import kitchenpos.order.deliveryorder.domain.DeliveryOrderStatus;
👍 👍 
추후 배달주문을 수정할 때 매장주문, 포장주문 영역을 일절 신경쓸 필요 없이 마음 편하게 수정할 수 있겠네요.

2023-09-18 10:06 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/eatinorder/domain/EatInOrder.java
>      private LocalDateTime orderDateTime;
> commmon 스러운게 있을 수도 있지 않을까 싶기도하면서, 말씀하신 것처럼 지금은 규모가 작은 프로젝트이기 때문에 각 컨텍스트에 도드라진 차이가 없다고 느껴져서 그런 것 같기도하고. 🤔

핵심을 짚어주셨다 생각해요. 현재는 경록님이 배달/포장/매장 주문에 대한 이해를 마치신 상태기 때문에 이와 같은 추상화가 가능하죠.
그러나 만약 주문별로 팀과 서버가 나뉘어있다고 생각한다면 절대로 만들어질 수 없는 코드가 됩니다.
(그나마 서로 협의하고 사용하는 DTO 정도가 되겠네요.)

2023-09-18 10:06 UTC, Hyeon9mak commented on src/main/java/kitchenpos/order/eatinorder/domain/EatInOrder.java
>      private LocalDateTime orderDateTime;
결국 DDD 는 "더 좋은 설계를 하는 방법" 이 아니라, "더 편하고 쉽게 일하는 방법" 을 고민하는거니까요, 코드 설계와 나눠서 생각해보시면 더 쉽게 이해가 될 것 같아요 👍

2023-09-18 10:07 UTC, merged

2023-09-19 11:59 UTC, Rok93 commented on src/main/java/kitchenpos/deliveryagency/DeliveryAgencyClient.java
> +
deliveryorder 라는 상위 패키지를 만들고 이 상위 컨텍스트에 소속된 배달업체를 패키지 계층 구조를 어떻게 해야할지 고민하다가, 별도로 쪼개게됐네요. 🤔

deliveryorder의 application 패키지에  deliveryAgencyClient를 넣었어도 됐을거 같기도하구요. 🤔

2023-09-19 12:03 UTC, Rok93 commented on src/main/java/kitchenpos/deliveryagency/DeliveryAgencyClient.java
> +
일단 쪼개두고 고민만하고 크게 변경하지 않았던 것 같아요. 🤔
다음 미션 진행할 떄는  delivery-agency 컨텍스트를 deliveryorders 내부로 넣을 것 같아요.