2단계 - 모델링하기
next-step/ddd-strategic-design pull request #337
Opened 2023-09-17 04:01 UTC by t1dmlgus

안녕하세요! 현수님:) 
_**2단계: 모델링**_ 리뷰 부탁드립니다.
늦었지만, 페어분과 서로 관점이 다른 부분은 싱크를 맞추면서
전반적으로 같은 도메인을 구상할 수 있도록 미션을 진행했습니다. 

가감없이 피드백 주시면 감사하겠습니다. 😄

#### 구현 중점
- 연관된 도메인 따른 바운디드 컨텍스트 분리
- 각 바운디드 컨텍스트 별 행위와 상태를 고려하여 모델링
- 도메인 이해관계자가 이해할 수 있도록 모델링
- 공통으로 사용되는 용어 사전 분리

#### 질문 사항

1. 
1단계에서 현수님이 리뷰주셨던 _"상품에 대한 설명도 조금 추가되어도 좋을 것 같아요. 상품은 이름과 가격을 가진다."_ 부분을 
다음과 같이 모델링으로 정의했습니다. _"Product는 식별자, Displayed Name, Price 를 갖는다. "_ 
그런데 미션 진행하면서 현수님이 리뷰주셨던 용어사전 내 용어설명 부분을 모델링으로 표현할 수 있을 거 같은데, 
이와 같이 용어사전에 정의할 지, 모델링으로 정의할지 기준을 정의할 수가 없더라구요.
해당 내용 관련해서 현수님 의견을 들어볼 수 있을까요?

2. 
미션을 진행하는데 페어분과 제가 개발자다보니, 추후 구현할 부분(식별자,  VO 등)도 고려하면서 모델링을 진행하고 있더라구요.
모델링 진행함에 있어, 최소한의 모델링은 어느정도로 인지하면 좋을까요?!

3. 
_"메뉴의 가격은 메뉴에 속한 상품들의 가격 총합보다 작거나 같아야 한다"_ 와 같이 해당 서비스에만 해당된다고 생각되는 부분을 컨텍스트 내 **_정책_** 으로 따로 도출했습니다만, 도메인 모델링으로 정의해도 별 다를점이 없다고 느껴집니다. 타 서비스와 다른 모델링 부분을 **_정책_** 이라고 도출하는 것도 좋을 듯한데, 혹시 이부분에 대해서 어떻게 생각하시나요?!

2023-09-17 15:55 UTC, hyunssooo requested changes
안녕하세요. 
모델링 미션 잘 진행해 주셨습니다.
몇 가지 코멘트 남겼습니다. 확인 부탁드려요. 
함께 고민해 보면 좋을 것 같아요. 🙂

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +
모델링에서도 중요한 것은 모델을 구성원 모두가 보고 이해할 수 있어야 한다고 생각하는데요. 저와 같은 모델을 생각할 수 있게 맞춰나가는 과정이라고 봐주시면 될 것 같아요. 🙂

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +- Price는 가격을 갖는다.
`DisplayedName`, `Price`는 그 자체로 이름, 가격을 의미하지 않나요? 
`Price는 가격을 갖는다.` 라는 문장은 조금 어색한 것 같아요.

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +
상품의 가격이 변경될 경우 해당 상품이 속한 메뉴들은 상품에 가격에 의해서 전시 여부가 변경될 수 있는데요. 이 부분도 표현해 보는 것은 어떨까요? 

> "메뉴의 가격은 메뉴에 속한 상품들의 가격 총합보다 작거나 같아야 한다" 와 같이 해당 서비스에만 해당된다고 생각되는 부분을 컨텍스트 내 정책 으로 따로 도출했습니다만, 도메인 모델링으로 정의해도 별 다를점이 없다고 느껴집니다. 타 서비스와는 다른 비즈니스적인 부분을 정책으로 도출 하는 것도 좋을 듯한데, 혹시 이부분에 대해서 어떻게 생각하시나요?!

`정책` 으로 분리해 설명해 주시는 점은 구성원이 동의하면 충분히 좋다고 생각합니다. 궁금한 점이 있는데요. 말씀하신 `도메인 모델링` 과 `정책` 은 각각 어떤 의미 일까요? 

> 해당 서비스에만 해당된다고 생각되는 부분을 컨텍스트 내 정책 으로 따로 도출

이라고 말씀 주셨는데 그렇다면 `메뉴 가격 정책`은 상품에 속하나요? 

> 타 서비스와는 다른 비즈니스적인 부분을 정책으로 도출

말씀해 주신 이 부분이랑은 조금 앞뒤가 안 맞는 것 같아서요. 🤔 제가 잘못 이해하고 있는 부분이 있는 것 같은데 조금 더 설명 부탁드립니다. 🙂

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +- Menu Products 금액의 합은 Menu의 Price보다 크거나 같아야 한다.
```suggestion
- Register Menu 를 할 수 있다.
  - Register Menu 시, Displayed Name, Price, Menu Product 는 필수여야 한다.
  - Register Menu 시, 1개 이상의 Product 로 구성되어야 한다.
  - Menu Products 금액의 합은 Menu의 Price보다 크거나 같아야 한다.
```

뎁스가 빠진거죠?

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +- Menu를 Displayed Menu 또는 Hide Menu를 할 수 있다.
display에 대한 조건이 있는데요. 이 부분도 명시해 보는 것은 어떨까요? 

가격 변경에 대한 부분은 빠져 있는 것 같아요. 이 부분도 작성해 보시면 좋을 것 같습니다.

2023-09-17 15:55 UTC, hyunssooo commented on README.md
> +   - OrderStatus는 순서를 갖는데, (Waiting > Acceptec > Served > Delivering > Delivery Complete > Completed)와 같이 진행된다.
각 주문 마다 다른 Status를 명시해 주셨네요! 👍

2023-09-17 16:02 UTC, hyunssooo commented
1, 2 두 질문은 함께 답변 드릴수 있을 것 같아요. 

제가 생각하는 모델링의 목적은 구성원들의 멘탈 모델을 반영하고 서로가 같은 모델을 생각하게 하는 것 같아요. 그래서 모델링의 결과물은 글뿐만 아니라 다이어그램, 이미지 등 여러 가지의 형태가 나올 수 있다고 생각해요. 중요한 것은 `구성원 모두가 모델 자체를 이해할 수 있어야 하는 것`이라고 생각해요. 

> 용어사전에 정의할 지, 모델링으로 정의할지 기준을 정의할 수가 없더라구요.

각각 다르게 정의되어야 한다는 말씀이실까요? 🤔 생각하시는 용어 사전과 모델링은 무엇인가요? 

구성원 모두가 이해할 수 있는 모델이 좋은 모델링이고 모델링의 범위라고 생각합니다. 🙂

2023-09-19 15:38 UTC, t1dmlgus commented
전반적으로 리뷰주신 부분, 확인 후 피드백 반영했습니다.
추가적으로 아래 내용에 대해 의견주시면 감사하겠습니다:)

> 제가 생각하는 모델링의 목적은 구성원들의 멘탈 모델을 반영하고 서로가 같은 모델을 생각하게 하는 것 같아요. 그래서 모델링의 결과물은 글뿐만 아니라 다이어그램, 이미지 등 여러 가지의 형태가 나올 수 있다고 생각해요. 중요한 것은 `구성원 모두가 모델 자체를 이해할 수 있어야 하는 것`이라고 생각해요.

공감합니다:)

> "용어사전에 정의할 지, 모델링으로 정의할지 기준을 정의할 수가 없더라구요."
> 
> 각각 다르게 정의되어야 한다는 말씀이실까요? 🤔 생각하시는 용어 사전과 모델링은 무엇인가요?

아닙니다. 동일하게 정의하지만, 아래와 같이 _"상품은 이름과 가격을 갖는다"_ 를 
모델링으로 정의할 지, 용어사전에 정의할지 어떤 기준으로 어느곳에 정의해야할지 여쭤보고자 합니다.

1. 모델링으로 정의
Product 는 이름과 가격을 갖는다.

2. 용어사전 내 용어설명에 정의
| 상품 | Product | 상품은 이름과 가격을 갖는다. | 


제가 생각하는 **_모델링_** 은 도메인 이해관계자들이 도메인 모델을 이해할 수 있도록 표현할 수 있는 것을 모델링이라 생각하며,
**_용어사전_** 도 모델링 중 하나로, 이해관계자들이 모델링을 통해 모델을 구상하면서 참고할 수 있는 모델링이라 생각됩니다.
개인적인 생각으로는 용어사전 내 용어는 _**컨텍스트 내에서 용어가 갖는 의미를 내포하도록 정의**_ 하면 좋을 듯한데,
리뷰주셨던 _"상품은 이름과 가격을 갖는다"_ 를 용어사전에 정의하게되면 어떤 기준으로 용어사전으로 정의하고자 하는지 
현수님 의견을 듣고 싶습니다.

2023-09-19 17:13 UTC, hyunssooo commented
네네 저도 미션을 함께 진행하고 있는 `이해관계자`로써 의견을 드린 거 였습니다. 🙂 
> 용어사전 도 모델링 중 하나로, 이해관계자들이 모델링을 통해 모델을 구상하면서 참고할 수 있는 모델링이라 생각됩니다.

용어 사전과 모델링의 내용은 겹칠 수 있다고 생각해요. 같은 요구 사항으로 만들어지니 겹치는 것은 당연하다고 생각합니다. 
`모델링 중 하나` 라고 표현해 주신 부분도 어느 정도 동의 합니다. 유비쿼터스 언어를 통해서 모델링을 하기 때문이에요. 
_**컨텍스트 내에서 용어가 갖는 의미를 내포하도록 정의**_  이 의견도 동의합니다. 

그럼 용어 사전의 상품에 대한 설명에 대한 피드백 한번 부탁드립니다. 🙂
지금 생각해 보면 개인적으로는 조금 더 추가될 수 도 있을 것 같아요. `메뉴를 구성하는 단위` 
앞서 작성해 주신 `메뉴에 등록될 음식` 이랑 비슷한 느낌이네요!

혹시라도 제가 잘못 이해하고 있는 부분이 있으면 말씀 부탁드릴게요.

2023-09-20 06:55 UTC, t1dmlgus commented
> 용어 사전과 모델링의 내용은 겹칠 수 있다고 생각해요. 같은 요구 사항으로 만들어지니 겹치는 것은 당연하다고 생각합니다. `모델링 중 하나` 라고 표현해 주신 부분도 어느 정도 동의 합니다. 유비쿼터스 언어를 통해서 모델링을 하기 때문이에요. _**컨텍스트 내에서 용어가 갖는 의미를 내포하도록 정의**_ 이 의견도 동의합니다.

의견 감사합니다!
해당 내용 관련해서 기준보다는 모델링과 용어사전을 통일성 있게 구성하도록 진행해야겠네요:)


> 그럼 용어 사전의 상품에 대한 설명에 대한 피드백 한번 부탁드립니다. 🙂 지금 생각해 보면 개인적으로는 조금 더 추가될 수 도 있을 것 같아요. `메뉴를 구성하는 단위` 앞서 작성해 주신 `메뉴에 등록될 음식` 이랑 비슷한 느낌이네요!

좋네요! 
메뉴 컨텍스트와 연관관계에 있어 `메뉴에 등록될 음식` 보다 더 명확해진 느낌입니다:)

2023-09-21 00:45 UTC, hyunssooo approved these changes
안녕하세요.
모델링 진행하신다고 고생 많으셨습니다. 
다음 step 진행 부탁드려요.
늦어서 죄송해요.🥲

2023-09-21 00:45 UTC, merged