1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #344
Opened 2024-05-16 00:27 UTC by hvoiunq

안녕하세요 리뷰어님! 
어제 페어프로그래밍 진행해서 바로 제출해봅니다☺️

회고
제가 주어를 많이 생략하고 이야기 한다는걸 깨닫게 된 순간인거 같아요!
그리고 이렇게 많은 용어사전이 나올 거라 생각못했는데 
당연히 이건 서로 알지 않을까 했던 단어도 누군가는 모호하게 느낄 수 있구나 라는 생각도 들었고, 그러다보니 채워 넣을게 많아지더라구요.
생각한 것보다 시간이 오래걸렸는데, 그만큼 너무 재밌던 시간이었습니다!

이번 과제 잘 부탁드리겠습니다~~!

2024-05-16 15:39 UTC, wlroh commented
효정님 안녕하세요 😄 
미션 고생하셨습니다!

> 제가 주어를 많이 생략하고 이야기 한다는걸 깨닫게 된 순간인거 같아요!
그리고 이렇게 많은 용어사전이 나올 거라 생각못했는데
당연히 이건 서로 알지 않을까 했던 단어도 누군가는 모호하게 느낄 수 있구나 라는 생각도 들었고, 그러다보니 채워 넣을게 많아지더라구요.
생각한 것보다 시간이 오래걸렸는데, 그만큼 너무 재밌던 시간이었습니다!

이부분이 바로 페어프로그래밍의 장점이자 용어사전의 힘이죠! ㅎㅎ
다만, 아쉬운것이 하나 있었는데 용어사전이 한줄만 밀린줄 알고 작성하신 것 리뷰하려다가 내려가면갈수록 점점더 많이 밀리고 있어서 빠르게 Request Change 드려요!

추가로, 현재 용어사전이 어떤 요구사항에 대한 용어인지 확인하기 힘든 것 같아요 😢

2024-05-16 15:41 UTC, wlroh requested changes
효정님 안녕하세요 😄 
이번 미션을 함께할 노웅래입니다.
미션 고생하셨습니다 👍 
코멘트 드린것이 있는데요 확인부탁드려요!

2024-05-16 15:41 UTC, wlroh commented on README.md
> +|서빙 완료  | served  |  - 주문 후 전체 또는 부분 취소가 불가능하다.  |
설명과 한글명이 매칭이 안되고 있어요 😢 
확인 부탁드려요

2024-05-16 15:41 UTC, wlroh commented on README.md
> +|상품 가격  | product price  |  - 상품을 표현하는 이름으로, 등록할 때 필요하다. (단, 비속어 포함 불가)  |
> 상품을 표현하는 이름으로, 등록할 때 필요하다. (단, 비속어 포함 불가)

`비속어 포함불가`라는 제약조건까지 포함하셨네요 👍 👍 

하지만, 여기서 `비속어` 는 무엇이라고 생각하실까요?
욕설만 해당하는 것일까요? 아니면 은어도 포함되는 것일까요?

2024-05-19 14:06 UTC, hvoiunq commented
@wlroh 

안녕하세요 웅래 리뷰어님! 지난 리뷰 때 제가 잘못 올리는 바람에ㅠㅠ....

이번에 페어님이 피드백 받으셨던 내용과 리뷰어님이 말씀해주신 부분들 같이 적용해서 수정해두었습니다 :)
리뷰 잘 부탁드립니다!

2024-05-20 13:30 UTC, wlroh requested changes
효정님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
코멘트 추가한 것이 있는데, 확인부탁드려요!

2024-05-20 13:30 UTC, wlroh commented on README.md
> +| 서빙 완료 | served       | - 배달/포장 주문: 음식 조리 및 포장까지 완료된 상태를 말한다. <br> - 매장 주문: 음식 조리가 끝나 손님에게 전달할 수 있는 상태를 말한다.
현재 서빙완료에 대한 주문상태만 용어로 도출되어 있는데 주문 상태에 대해 모두 정의해보면 어떨까요?
그리고 주문 유형에 따라 이미 분류해주셔서 주문상태를 각 유형마다 용어로 도춣해보면 어떨까요?

2024-05-20 13:30 UTC, wlroh commented on README.md
> +| 배달 대행사 | delivery rider   | - 배달 주소로 메뉴를 전달해주는 대행사. <br> - 배달 대행사 수락이 안되는 경우, 배달 접수가 안된다.
> 배달 대행사 수락이 안되는 경우, 배달 접수가 안된다.

배달대행사의 수락이 안되면 주문접수가 안된다는 의미일까요? 🤔

2024-05-20 13:30 UTC, wlroh commented on README.md
> +### 상품
하위도메인별로 용어사전 잘 정리해주셨네요 👍 👍

2024-05-20 13:30 UTC, wlroh commented on README.md
> +| 주문 상태 | order status | - 주문의 상태를 말하며, 주문 접수(WAITING), 주문 수락(ACCEPTED), 서빙 완료(SERVED), 배달 중(DELIVERING), 배달 완료(DELIVERED), 주문 완료(COMPLETED)  <br> - 배달 주문: 주문 접수 → 주문 수락 → 서빙 완료 → 배달 중 → 배달 완료 → 주문 완
주문 상태에 대해 잘 나와있고, 주문유형별로 정리되어있어서 좋네요 👍

2024-05-24 09:28 UTC, hvoiunq commented on README.md
> +| 배달 대행사 | delivery rider   | - 배달 주소로 메뉴를 전달해주는 대행사. <br> - 배달 대행사 수락이 안되는 경우, 배달 접수가 안된다.
@wlroh 앗! 수락이 안되는건데 접수로 적어두었네요!! 수정하겠습니다 :)

2024-05-24 09:29 UTC, hvoiunq commented on README.md
> +| 서빙 완료 | served       | - 배달/포장 주문: 음식 조리 및 포장까지 완료된 상태를 말한다. <br> - 매장 주문: 음식 조리가 끝나 손님에게 전달할 수 있는 상태를 말한다.
@wlroh 오! 좋은 의견인 거 같습니다!ㅎㅎ 요건 페어님께 내용 전달해서 그렇게 수정해볼게요 😃

2024-05-24 13:41 UTC, hvoiunq commented
리뷰어님! ㅎㅎ 
피드백 주신거랑 step2 모델링 진행하면서 빠진 용어들이 있어서 추가해두었습니다. 
그리고 페어님 피드백에 주문 유형별로 용어를 분리해보는것도 좋아보인다고 의견이 있어서 그것도 같이 적용봤습니다 :)

2024-05-25 10:11 UTC, wlroh approved these changes
효정님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
용어사전은 꾸준히 업데이트가 필요한 것이라고 생각해요
다음 단계 진행하시면서 용어사전도 꾸준한 업데이트 부탁드려요!

2024-05-25 10:11 UTC, merged