1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #346
Opened 2024-05-16 10:56 UTC by jinyoonYang

안녕하세요 페어 현기님과 함께 용어사전 정의했습니다. 

as-is 버전의 시스템 기준으로 용어명칭 보단 용어가 의미하는 설명에 초점을 두었고 상태 값 별로 구분지어 소통하기 편하게 정의해보았습니다. 
2주차 과제도 잘 부탁드립니다.

2024-05-16 17:20 UTC, wlroh commented
진윤님 안녕하세요 😄 
이번 미션을 함께할 노웅래입니다.
미션 고생많으셨어요!

> 용어명칭 보단 용어가 의미하는 설명에 초점을 두었고 상태 값 별로 구분지어 소통하기 편하게 정의해보았습니다.

진윤님이 말씀주신 코멘트 보면서 궁금했던 것이 있었는데요.
혹시 용어명칭이 혹시 한글명과 영문명을 뜻하는 의미였을까요? 🤔

2024-05-16 17:22 UTC, wlroh requested changes
진윤님 안녕하세요 😄 
이번 미션을 함께할 노웅래입니다.
미션 고생하셨습니다 👍 
코멘트 적은것이 있는데요 확인부탁드려요!

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 매장  | shop     | POS를 조작하고 치킨을 판매하는 클라이언트. |
> POS를 조작하고 치킨을 판매하는 클라이언트

여기서 `클라이언트` 의 의미가 서버 & 클라이언트의 클라이언트일까요? 🤔 
아니면 고객을 뜻하는 비즈니스 용어로 사용되는 클라이언트일까요?
클라이언트에 대해 정의를 하거나 혹은 조금더 범용적인 단어로 표현해보는 것을 어떨까요?

용어사전은 모든 이해관계자가 쉽게 이해해야 한다고 생각해요.
만약 서버 & 클라이언트 의 의미라면 개발용어는 용어사전에 지양해야하지 않을까 생각하는 편이에요

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 가격  | price   | 0 이상의 상품의 가격.       |
> 0 이상의 상품의 가격.

사소한 것이긴 한데 가격을 의미하므로 `0원 이상의 상품의 가격` 으로 표현해보면 조금 더 자연스럽다고 생각하는데 어떻게 생각하시나요?

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 이름  | name    | 상품의 이름.             |
상품의 이름에 비속어가 들어갈 수 없는 요구사항이 있는데요.
비속어에 대해서도 용어정리해보면 어떨까요?

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 이름    | name       | 메뉴그룹의 개성을 나타내는 그룹의 이름.     ex.매운치킨들, 두마리메뉴 |
예시까지 작성해주셨네요 👍 👍 
이해하기 훨씬 좋은 것 같아요.

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 메뉴     | menu    | 고객에게 판매되는 단위.  하나 이상의 상품으로 구성된다.      |
> 고객에게 판매되는 단위. 하나 이상의 상품으로 구성된다.

`상품` 은 무엇일까요? 상단에 정의해주신 `상품 (메뉴를 구성할 수 있는 최소 단위)` 를 뜻할까요?

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 가격     | price   | 0 이상의 메뉴의 가격. 구성된 상품의 가격보다 크거나 같아야한다. |
> 구성된 상품의 가격보다 크거나 같아야한다. 

제약조건도 같이 포함되어서 좋네요 👍 👍 
`가격`이라는 용어만 듣더라도 구성된 상품의 가격 초과된 금액이라고 누구나 떠올려서 커뮤니케이션하기 편해지겠네요

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 주문 상태 | order status    | 주문의 진행 상태.              |
각 주문 방식에 따라 주문상태가 무엇이 있는지 작성해보면 어떨까요?

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 포장 주문     | accepted      | 포장 주문을 접수한 상태.         |
한글명이 동일한데 확인부탁드려요 😢

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 매장 주문     | accepted     | 매장 주문을 접수한 상태.          |
여기도 한글명이 동일해요. 확인부탁드려요

2024-05-16 17:22 UTC, wlroh commented on README.md
> +### 배달 주문
`배달 대행사` 와 같은 용어도 추가해보는 것은 어떤가요?

2024-05-16 17:22 UTC, wlroh commented on README.md
> +| 비공개 메뉴 | hide    | 고객이 주문 불가능한 비공개된 메뉴                   |
한글명은 명사인데 영문명은 동사로 보여져요.
영문명도 한글명에 맞게 수정해보면 어떨까요?
추가로, 용어사전에서 영문명도 정의하는 이유는 무엇이라고 생각하실까요?

2024-05-17 14:30 UTC, jinyoonYang commented on README.md
> +| 매장  | shop     | POS를 조작하고 치킨을 판매하는 클라이언트. |
치킨을 판매하는 가게로 pos기를 구매한 고객이라는 의미로 클라이언트를 썼는데 좀더 명시적으로 바꿔보았습니다.

2024-05-17 14:35 UTC, jinyoonYang commented on README.md
> +| 메뉴     | menu    | 고객에게 판매되는 단위.  하나 이상의 상품으로 구성된다.      |
넵 맞습니다 ~!
상품은 위에 예시로 들었던 치킨이 될 수 있고 메뉴는 치킨과 같은 상품으로 1개 또는 여러개로 조합해서 구성할 수 있음을 의미적으로 담아보았습니다. 

여러 상품 조합 메뉴는 예시로 세트메뉴가 있을 수 있습니다.

2024-05-17 14:44 UTC, jinyoonYang commented on README.md
> +| 비공개 메뉴 | hide    | 고객이 주문 불가능한 비공개된 메뉴                   |
개발때 활용할 수 있는 명칭으로 함께 정의하여 다른 도메인 개발자들과 fit을 맞추기 위한 목적으로 이해하고 있습니당

2024-05-18 02:06 UTC, jinyoonYang commented
> 진윤님 안녕하세요 😄 이번 미션을 함께할 노웅래입니다. 미션 고생많으셨어요!
> 
> > 용어명칭 보단 용어가 의미하는 설명에 초점을 두었고 상태 값 별로 구분지어 소통하기 편하게 정의해보았습니다.
> 
> 진윤님이 말씀주신 코멘트 보면서 궁금했던 것이 있었는데요. 혹시 용어명칭이 혹시 한글명과 영문명을 뜻하는 의미였을까요? 🤔

네네 맞습니당 메뉴, 상품/ menu 같은 도메인으로 정의할 단어의 명칭보단 설명에 좀 더 집중해서 정리했던 것 같아서 코멘트 남겼던 부분입니다~!

2024-05-18 16:45 UTC, wlroh requested changes
진윤님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
코멘트 드린것이 있는데요, 확인부탁드려요!

2024-05-18 16:45 UTC, wlroh commented on README.adoc
> +|이름 |name |비속어가 없는 상품의 이름.
비속어도 별도의 용어로 분리해보면 어떨까요?
비속어가 욕설만 해당하는지 은어도 포함되는지 해석이 많이 달라질 것 같아요

2024-05-18 16:45 UTC, wlroh commented on README.adoc
> +(매장/포장 : 대기 -&gt; 접수 -&gt; 서빙 -&gt; 완료, 배달 : 대기 -&gt; 접수 -&gt; 서빙 -&gt; 배달중 -&gt; 배달 완료 -&gt; 완료)
플로우가 정리되어 있어서 상태를 한눈에 볼수있어 좋네요 👍 👍 
여기서 가독성을 조금더 개선하고자 아래와 같이 개행을 넣어보면 어떨까요?
```
매장/포장: 대기 -> 접수 -> 서빙 -> 완료
배달 : 대기 -> 접수 -> 서빙 -> 배달중 -> 배달 완료 -> 완료)
```

2024-05-18 16:45 UTC, wlroh commented on README.adoc
> +|매장 주문 접수 대기 |waiting |매장이 주문을 접수하기 전 상태
상단에 정리해주신 `주문 상태` 의 워딩과 통일해보면 어떨까요?
위에서는 `대기` 인데 `접수 대기` 로 표현이 되어있어요
상태 관련해서 매장주문말고도 전체적으로 통일해보면 어떨까요?

2024-05-18 16:45 UTC, wlroh commented on README.md
> +| 메뉴     | menu    | 고객에게 판매되는 단위.  하나 이상의 상품으로 구성된다.      |
답변감사합니다 진윤님 😄 
지금 단계에서는 저도 이견은 없으나, 모델링을 진행하시면서 `상품`과 `상품 (메뉴를 구성할 수 있는 최소 단위)` 같은 것인지 고민해보시면 좋을 것 같아요

2024-05-18 16:45 UTC, wlroh commented on README.md
> +| 비공개 메뉴 | hide    | 고객이 주문 불가능한 비공개된 메뉴                   |
> 개발때 활용할 수 있는 명칭으로 함께 정의하여 다른 도메인 개발자들과 fit을 맞추기 위한 목적으로 이해하고 있습니당

네 진윤님 말씀처럼 개발때 활용할 수 있는 명칭인 점에서 이부분도 중요한 포인트인 것 같아요.
코멘트 드린 의도는 

> 네네 맞습니당 메뉴, 상품/ menu 같은 도메인으로 정의할 단어의 명칭보단 설명에 좀 더 집중해서 정리했던 것 같아서 코멘트 남겼던 부분입니다~!

물론 단어의 명칭에 대해서도 중요하게 생각하시는 것 같지만 해당 코멘트를 보면서 단어의 명칭보다는 설명에 더 집중하셨던 것 같아서 혹시나 해서 말씀드려요~

용어사전에 정의된 영문명에 집중하지 않고 작성하게 될 경우, 나중에 구현할 때 용어사전에 있는 워딩이 마음에 안들었을 때 이슈가 될수가 있어요. 더 좋은 워딩이 떠올라 용어사전에 있는 워딩과 다른 워딩을 사용하게 되면 이것은 나중에 커뮤니케이션에 큰 오해를 불러올 수 있는 리스크가 생겨서 용어사전 작성 때 설명뿐만 아니라 용어의 명칭도 중요하다는 것을 말씀드리고 싶었어요

2024-05-19 06:26 UTC, jinyoonYang commented
말씀하신 내용 참고해서 수정해보았습니다!

2024-05-19 14:42 UTC, wlroh commented
진윤님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 👍 
용어사전은 이번 단계에서 마무리되는 것이 아니라 꾸준히 업데이트가 필요한데요!
모델링 미션 진행하시면서 용어가 추가로 나올 수 있고 수정이 필요한 상황이 올 수 있는데 그때마다 용어사전도 꾸준히 업데이트 부탁드려요!

2024-05-19 14:44 UTC, wlroh approved these changes
진윤님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
간단한 코멘트 적었는데 다음 단계 진행 전에 확인 부탁드려요
그럼 다음 단계도 화이팅입니다 🔥

2024-05-19 14:44 UTC, wlroh commented on README.adoc
> +|배달원 |rider |고객에게 치킨을 배달하는 사람.
저희가 키친포스여서 치킨만 배달하지 않아서 치킨 대신 다른 표현은 어떨까요?

> 고객에게 배달주문을 전달하는 사람.

으로도 표현할 수 있을 것 같고요!

2024-05-19 14:44 UTC, merged