1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #35
Opened 2020-02-22 01:58 UTC by ddingcham

안녕하세요.
지금 까지 미션 중에 가장 어렵네요...
매운 맛으로 부탁드립니다. ( _ _ )

2020-02-22 07:20 UTC, kyucumber requested changes
안녕하세요, 용어 사전 정리해주시느라 고생 많으셨습니다! 😄 

간단한 코멘트 몇가지 남겼습니다.

보시고 궁금하신 점 있으시면 코멘트 / 슬랙 메세지 남겨주세요!

2020-02-22 07:20 UTC, tramyu commented on README.md
> +| 테이블 상태 정책 | Table Status Rule | 단체 지정 되어 있지 않거나, 모든 주문들이 최종 주문 상태인 경우에만 테이블 상태를 변경할 수 있다. |
이런 상세한 부분들은 모델링에서 정의되어도 좋을 것 같아요!

2020-02-22 07:20 UTC, tramyu commented on README.md
> +| 최종 주문 상태 | Final Order Status | 최종 주문 상태의 주문은 상태를 변경할 수 없다. (계산 완료) |
최종 주문 상태는 주문 상태(Order Status)의 `COMPLETION`을 뜻하는 것 같아요
혼동을 주지 않도록 `COMPLETION`임을 명시해주면 좋을 것 같네요

그리고 이 부분은 제약 조건, 정책과 같은 부분이라 모델링에 포함되어도 좋을 것 같습니다.

2020-02-22 07:20 UTC, tramyu commented on README.md
> +| 메뉴 구성 상품 | Menu Product | 메뉴를 구성하는 상품이다. |
메뉴 구성 상품은 어떤 속성을 가지는지 간단하게 설명해주면 어떨까요?

```suggestion
| 메뉴 구성 상품 | MenuProduct | 메뉴를 구성하는 상품, 상품과 상품 수량 정보를 가진다  |
```

2020-02-23 04:52 UTC, ddingcham commented on README.md
> +| 테이블 착석 인원 | Table Occupied Guest | 착석 상태의 테이블에 앉은 손님을 뜻하며, 아직 도착하지 않은 경우에는 0명으로 취급한다. |
작성 후에 용어 사전에 정의한 용어를 활용 했는지
확인한다는 게 깜빡 했네요.
감사합니다 ( _ _ ) 👍

2020-02-23 04:56 UTC, ddingcham commented on README.md
> +| 주문 메뉴 정책 | Order Menu Rule | 주문은 1개 이상의 메뉴를 갖는다. |
OrderLineItem 을 용어 사전에 정의 할 지 말 지 고민을 했었는데요.
제가 생각하기에, OrderLineItem 에 대한 개념은 개발적인 요소가 아닐까 싶어서
생략하였습니다.

다시 생각해보니 꼭 OrderLineItem이 아니더라도,
주문한 메뉴와 개수에 대한 정의는 필요할 것 같네요.

감사합니다 👍

2020-02-23 04:58 UTC, ddingcham commented on README.md
> +| 메뉴 구성 상품 | Menu Product | 메뉴를 구성하는 상품이다. |
👍 
정책만 적어 놓고,
해당 정책이 적용될 부분은 빼 먹었네요

2020-02-23 05:10 UTC, ddingcham commented on README.md
> +| 테이블 | Table | 식당에서 손님들이 식사를 하는 장소 |
감사합니다 ( _ _ )

관련해서, 명확하게 이해가 안되는 부분이 있는데요.

제가 강의를 들으면서, 이해를 한 내용 상
요구사항이나 용어 사전에 사용되는 용어는 기술적인 표현을 배제해야 한다고 이해 했는데요.
(전자)

피드백 주신 내용처럼 강의 내용 중에 어떤 부분은
기술적인 표현으로 헷갈릴 수 있는 부분에 대해서는 
명시적으로 구분을 해야한다는 부분도 있더라구요. (후자)

그러면, "후자"에 헷갈릴 소지가 있는 부분에 대해 명시적으로 구분해야 한다는 것과
기술적인 표현을 배제해야 한다는 "전자"의 전제조건이 
상충되는 것처럼 보이는데......

용어 사전이나 요구 사항 문서만 봤을 때는 문제가 없지만,
문서들에 정의된 용어를 가지고 의사소통 할 때, 오해 소지를 줄이는 게 목적인 건데
제가 "후자" 관련해서, 이 부분을 빠뜨리고 이해한 걸까요?


간결하게 질문드리고 싶은데, 죄송합니다 ㅠㅠ

2020-02-23 05:37 UTC, ddingcham commented
리뷰 감사합니다. ( _ _ )
역시, 혼자하면 암묵적인 부분이 생길 수 밖에 없네요 ㅠㅠ

2020-02-23 09:57 UTC, tramyu commented on README.md
> +| 테이블 | Table | 식당에서 손님들이 식사를 하는 장소 |
사실 용어 사전이나 요구사항만 봤을 땐 지금 사용한 테이블(Table)이라는 용어는 전혀 문제가 없어요.

지금 용어사전과 모델링 두가지 모두에 대한 리뷰를 달고 있다 보니 모델링 단계도 염두에 두고 리뷰를 남긴 거기도 합니다. (모델링 단계에서 Table -> OrderTable 등으로 변경하게 되면 용어 사전도 업데이트를 해주어야 하니까요)

정리하자면, 요구사항 정리나 용어사전 단계에서는 테이블이란 용어를 사용해도 기본적인 설명 등이 들어갈거기 때문에 전혀 문제 없을 것 같습니다.


아래는 그냥 개인적인 의견을 몇가지 정리해서 덧붙인건데, 참고만 해주시면 될 것 같습니다.

- 테이블 자체도 굉장히 포괄적인 단어(그냥 물건을 올릴 수 있는 모든 것들..)이 될 수 있기 때문에 조금 더 상세하게 용어를 구분하면 어떨까 하는 생각정도는 들긴 하네요

- 기술적인 표현을 최대한 배제해야 하는 건 맞지만 이런 부분이 사전에 문제가 될 수 있단걸 알기 때문에 그런 부분에 대해서는 미리 용어를 상세하게 정리하는 것도 나쁘지 않다고 생각해요. 기술적으로 사전에 문제가 될 수 있는 부분을 알고 명확히 용어를 정하는것 자체는 기술적인 표현을 사용한건 아니니까요

2020-02-23 10:00 UTC, kyucumber requested changes
코멘트 남기셨던 부분에 대해 제 생각을 정리해서 남겼어요.

혹시 보시고 다른 의견이 있으시거나, 궁금하신 점 있으면 추가로 코멘트 / 슬랙 메세지 남겨주세요!

다시 재 요청 주시면 머지하도록 하겠습니다.

2020-02-24 09:17 UTC, kyucumber approved these changes
용어사전 작성하시느라 고생 많으셨습니다~ 😄 

다음 단계 진행을 위해 머지할게요!

질문 주셨던 내용은 잘 해소 되셨을까요?

2020-02-24 09:17 UTC, merged

2020-02-24 11:39 UTC, ddingcham commented
> 용어사전 작성하시느라 고생 많으셨습니다~ 😄
> 
> 다음 단계 진행을 위해 머지할게요!
> 
> 질문 주셨던 내용은 잘 해소 되셨을까요?

```
테이블 자체도 굉장히 포괄적인 단어(그냥 물건을 올릴 수 있는 모든 것들..)이 될 수 있기 때문에 조금 더 상세하게 용어를 구분하면 어떨까 하는 생각정도는 들긴 하네요
```

이 말씀 덕분에 해결 되었습니다. : )
"포괄적인 단어"라는 표현 덕분에 깨달은 느낌을 받았습니다. ( _ _ )