1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #351
Opened 2024-05-16 13:30 UTC by pawoo0211

안녕하세요 2주차 진행하게 된 박상권이라고 합니다. 용어 사전 미션 진행하여 PR 생성합니다. 아래 질문 사항이 있는데 해당 질문 답변해주시면 감사하겠습니다.

감사합니다.

질문 사항
- 상품 수량이나 주문 항복 수량과 같이 중복되는 용어를 전략적 설계에서도 bounded context 를 나눠서 용어집을 작성해야 하나? 
- 메뉴 이름이나 메뉴 가격처럼 너무 당연한 것들도 용어집에 작성해야 하나?

2024-05-17 07:33 UTC, Hyeon9mak requested changes
안녕하세요 상권님! 용어 사전 만들기 잘 진행해주셨습니다.

주문 영역을 살펴보면 주문 유형별로 비슷한 용어를 다루어
각각 어느 용도로 사용되는 용어인지 헷갈리는 부분이 있는데요,

이 주문들을 서로 완전히 다른 영역으로 나누고
각 용어를 다시 정리해보는 경험을 해보시는 건 어떨까요?
(피자 가게에서 바라보는 따듯한 피자와, 골목 쓰레기 더미에서 바라보는 차가운 피자는 서로 완전히 다른 피자다.)

궁금하신 점 질문 남겨주세요!

2024-05-17 07:33 UTC, Hyeon9mak commented on README.md
> +| 메뉴 숨김    | Hide Menu         | 점장은 메뉴를 숨길수 있다. 메뉴를 숨기면 손님은 해당 메뉴를 주문할 수 없다. |
현실에 빗대어 잘 설명해주신 덕분에 용어의 의미를 바로 이해할 수 있네요 👍

2024-05-17 07:33 UTC, Hyeon9mak commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                                                    |
`배달 완료`와 `완료`는 어떤 차이를 갖나요?

2024-05-17 07:33 UTC, Hyeon9mak commented on README.md
> +| 메뉴 가격 변경 | Change Menu Price | 점장은 메뉴 가격을 변경할 수 있다.                         |
"가격을 변경한다." 라는 행위가 우리가 다루는 컨택스트만의 특수한 정의를 가지지 않는다면 생략하여도 괜찮다고 생각해요.
상권님은 어떻게 생각하시나요?

2024-05-17 07:33 UTC, Hyeon9mak commented on README.md
> +| 상품 수량 | Product Quantity | 상품의 수량을 의미한다.                            |
> 상품 수량이나 주문 항복 수량과 같이 중복되는 용어를 전략적 설계에서도 bounded context 를 나눠서 용어집을 작성해야 하나?

`수량` 이라는 용어에 대한 말씀이시겠죠? 상품 수량과 주문 항목 수량이 서로 각기 다른 정책을 갖게 되는 경우
`e.g. 상품 수량은 무조건 1 이상이어야한다. 주문 항목 수량은 0 이상이어야 한다.`
별도로 표기해주는 것이 좋다고 생각합니다... 만 아닌 경우 꼭 그럴 필요는 없겠네요 😄 

용어 사전이 너무 길고 지루하면 동료들이 읽기 피곤해 할테니까요!

2024-05-17 07:33 UTC, Hyeon9mak commented on README.md
> +| 상품 이름 | Product Name     | 상품의 이름을 의미한다.                            |
> 메뉴 이름이나 메뉴 가격처럼 너무 당연한 것들도 용어집에 작성해야 하나?

특별한 무언가를 갖지 않는다면 꼭 작성할 필요는 없다고 생각해요.
다만 가격과 이름 모두 `음수일 수 없다.`, `비속어가 포함되면 안된다.` 등의 정책이 있지 않나요? 😄 
이런 경우 작성을 해두는 편이 유리하겠네요!

2024-05-18 07:03 UTC, pawoo0211 commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                                                    |
아래와 같이 생각했습니다.

배달 완료: 음식이 손님에게 배달이 완료된 상태
완료: 주문이 완료된 상태

2024-05-18 07:05 UTC, pawoo0211 commented on README.md
> +| 메뉴 가격 변경 | Change Menu Price | 점장은 메뉴 가격을 변경할 수 있다.                         |
좋은 말씀이신 것 같습니다.

컨텍스트안에 특수한 정의를 가지지 않고 이미 보편적인 단어라면 유비쿼터스 언어로 정의할 필요가 없는 것 같아요.

2024-05-19 22:08 UTC, Hyeon9mak requested changes
안녕하세요 상권님! 코멘트가 살짝 누락된 것 같아 다시 request changes 남깁니다!

2024-05-19 22:08 UTC, Hyeon9mak commented on README.md
> +- 매장 주문을 제외한 주문의 경우 주문 항목의 수량은 0 이상z이어야 한다.
😉

2024-05-19 22:08 UTC, Hyeon9mak commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                                            |
요구사항 정의서에 `배달 완료` 인 경우에만 `완료` 처리를 할 수 있다고 나타나 있군요!
제가 해당 부분을 놓쳤습니다. 🙏

2024-05-19 22:08 UTC, Hyeon9mak commented on README.md
> +| 배달 완료     | Complete Delivery | 손님에게 정상적으로 음식을 배달 완료한 상태                                                              |
포장, 매장 주문은 `배달 시작`, `배달 완료`, `배달 대행사`, `배달 대행사 호출` 과 같은 용어를 이해할 필요가 없을거에요.
각 주문이 서로 알아야할 것과 알 필요가 없는 것들을 나누는 경계, 범위를 저희는 '바운디드 컨텍스트' 라고 부르는 것 같아요!

각기 주문 유형을 완전히 다른 주문으로 바라보고, 이를 나누어 정의해보는 것은 어떨까요?
(이전에 남겨드린 코멘트가 누락된 것 같아 재차 남겨드려요!)

2024-05-20 10:05 UTC, pawoo0211 commented on README.md
> +| 배달 완료     | Complete Delivery | 손님에게 정상적으로 음식을 배달 완료한 상태                                                              |
바운디드 컨택스트라는 개념이 모호했는데 말씀하신 내용이 명쾌한 것 같습니다.

주문 유형에 따라 정의해보도록 하겠습니다.

2024-05-21 16:26 UTC, Hyeon9mak approved these changes
안녕하세요 상권님! 주문을 컨텍스트별로 나눠주신 덕분에
각 주문별로 인지해야할 용어들이 획기적으로 줄어들었네요!!
조만간 코드를 리팩터링 하실 때 더 큰 효과를 불러올것이라 분명 기대됩니다!! 😄 

아주 간단한 코멘트와 함께, 다음 단계로 가시죠!

2024-05-21 16:26 UTC, Hyeon9mak commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                            |
`배달중` 과 같이 매장 주문시에 알 필요가 없는 정보들이 사라지고,
매장 주문시 알아야할 정보가 획기적으로 줄어들었네요!

매장 주문과 관련된 비즈니스, 개발을 다룰 때 집중도가 확연히 올라가겠네요!

2024-05-21 16:26 UTC, Hyeon9mak commented on README.md
> +| 배달 대행사 호출 | Call Delivery     | 손님에게 배달을 하기 외부 배달 대행사에게 요청하는 행위                                                       |
배달 대행사도 배달주문 쪽으로 이관시켜주셨군요! 👍 👍

2024-05-21 16:26 UTC, Hyeon9mak commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                            |
(꼭 반영해주실 필요 없고 상권님의 의견을 여쭙는 질문)
주문 테이블은 별도로 다루는 것이 좋을까요, 매장 주문으로 포함시키는 것이 좋을까요? 😄 
상권님의 견해가 궁금합니다!

2024-05-21 16:26 UTC, merged

2024-05-22 03:15 UTC, pawoo0211 commented on README.md
> +| 완료        | Complete          | 손님에게 음식 제공이 끝나서 주문이 완료된 상태                                            |
사실 생각을 못했는데 주문 테이블을 매장 주문 안으로 포함시키는 것이 좋은 것 같습니다.

기존에 현구님이 말씀해주신 것처럼 바운디드 컨텍스트는 알 필요가 없는 것을 바운더리의 기준으로 삼는 것 같습니다. 또한 주문 테이블의 라이프 사이클이 매장 주문과 같이 가기 때문에 매장 주문 하위에 주문 테이블이 있으면 도메인 트랜잭션 처리가 보다 편리할 것 같습니다!

현구님은 어떻게 생각하시는지 현구님의 의견도 궁금합니다!