🚀 1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #374
Opened 2024-05-19 16:01 UTC by hoa0217

안녕하세요 리뷰어님~ 페어(@domodazzi)님과 함께 진행하였습니다.

피드백 잘 부탁드립니다!

2024-05-20 12:54 UTC, kyucumber requested changes
용어사전 잘 정리해주셨네요. 잘 정리해주셔서 간단한 코멘트만 몇개 남겨두었습니다.

다음 요청 시 머지하도록 할게요.

2024-05-20 12:54 UTC, kyucumber commented on README.md
> +| 메뉴 그룹    | MenuGroup      | 메뉴를 분류하는 카테고리 ex) 추천, 세트메뉴, 음료 |
예시를 다 잘 넣어주셔서 용어 이해에 도움이 되네요 👍

2024-05-20 12:54 UTC, kyucumber commented on README.md
> +| 숨김 메뉴    | Hide Menu    | 손님에게 숨겨지는 메뉴                                               |
숨김 메뉴라는 용어를 더 잘 이해하기 위해서, 어떤 경우 숨김처리가 될 수 있는지 등에 대해서도 정리하면 어떨까요?

예를 들면 사장님이 숨길 수 있다거나 혹은 어떤 가격 정책에 의해 숨겨질 수 있다거나 하는 부분이 추가되면 용어에 대해 더 잘 이해할 수 있을 것 같습니다.

2024-05-20 12:54 UTC, kyucumber commented on README.md
> +| 주문 유형 | Order Type      | 손님이 주문하는 유형. ex) [배달 주문](#배달-주문), [매장 주문](#매장-주문), [포장 주문](#포장-주문)                |
주문 유형에 대한 설명 및 링크를 걸어주신 부분이 좋네요!

그리고 각 주문 유형별로 주문 상태가 어떻게 변경되는지도 한눈에 볼 수 있어서 좋은 것 같습니다. 👍

2024-05-20 12:54 UTC, kyucumber commented on README.md
> +| 주문 유형 | Order Type      | 손님이 주문하는 유형. ex) [배달 주문](#배달-주문), [매장 주문](#매장-주문), [포장 주문](#포장-주문)                |
중요한 부분은 아니나 주문 유형의 각각에 대한 영문명(Takeout, Delivery, EatIn) 등도 용어 사전 정리에 포함되면 좋을 것 같아요!

2024-05-20 12:54 UTC, kyucumber commented on README.md
> +| 배달 요청 | Delivery Request  | 주문 접수 후 배달 대행사 통해 라이더를 호출한다. |
배달 대행사라는 용어가 나왔는데 라이더란 용어는 정리되었지만 배달 대행사라는 용어는 사전에 정리되지 않은 것 같아요. 

라이더가 용어 사전에 추가되었으므로 배달 대행사에 대한 부분도 정리하면 어떨까요?

2024-05-20 12:56 UTC, hoa0217 commented on README.md
> +| 배달 요청 | Delivery Request  | 주문 접수 후 배달 대행사 통해 라이더를 호출한다. |
배달 대행사를 깜빡했네요! 추가하겠습니다!!

2024-05-20 12:57 UTC, hoa0217 commented on README.md
> +| 주문 유형 | Order Type      | 손님이 주문하는 유형. ex) [배달 주문](#배달-주문), [매장 주문](#매장-주문), [포장 주문](#포장-주문)                |
유형에 대한 설명도 필요하다는 말씀이신거죠? 수정하겠습니다~

2024-05-20 12:59 UTC, hoa0217 commented on README.md
> +| 숨김 메뉴    | Hide Menu    | 손님에게 숨겨지는 메뉴                                               |
용어사전이라 행위에 대한 부분을 제외하고 작성하다보니 해당 설명이 도출되었습니다. 페어와 이야기해보고 수정하겠습니다!

2024-05-21 14:30 UTC, hoa0217 commented
### 변경사항
- [x] 숨김메뉴 설명추가
- [x] 메뉴는 하나의 메뉴 그룹에 속한다 내용 추가
- [x] 주문 유형 용어 설명 추가
- [x] 라이더 용어 설명 배달 주문 파트로 이동
- [x] 배달 대행사 용어 설명 추가

2024-05-22 14:11 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요. 🙇

2024-05-22 14:11 UTC, merged