🚀 2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #375
Opened 2024-05-19 17:29 UTC by dkswnkk

2단계도 잘 부탁드립니다!

말 그대로 모델링만 하면 되는지? 아니면 요구사항까지 다시 적어야 하는지,, 만약 적는다면 얼마나 세세하게 적어야 하는지 계속해서 고민되었는데 일단 모델링의 흐름에 해당하는 요구사항들만 작성해보았습니다!

2024-05-20 14:16 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 
확인 부탁드릴게요. 
함께 고민해 보면 좋을 것 같아요. :)

2024-05-20 14:16 UTC, hyunssooo commented on README.md
> +```mermaid
mermaid 👍

2024-05-20 14:16 UTC, hyunssooo commented on README.md
> +7. 메뉴의 가격이 메뉴에 속한 상품 금액의 합보다 높을 경우 메뉴를 숨겨야 한다.
시퀀스 다이어그램에 상품, 메뉴, 메뉴 그룹이 한번에 묶인 이유가 있을까요? 
각각 따로 작성되어도 괜찮을 것 같아서요.

2024-05-20 14:16 UTC, hyunssooo commented on README.md
> +
여기도 분리해 보는 것은 어떨까요?

2024-05-20 14:16 UTC, hyunssooo commented on README.md
> +8. 배달 완료된 주문만 완료할 수 있다.
각 케이스별로 나눠 보는 것은 어떨까요? 전체적으로 한번에 너무 많은 것을 표현 되는 것 같습니다. 

`배달 주문 정책` 이라고 하지만 각각의 케이스 별로 다를 것 같은데요. 예를 들어 주문 완료 요청에서도 배달 주소에 대한 검증이 들어갈까요?

궁금한 점이 있는데요. 정책이라는 별도의 도메인?이 있는 걸까요? 배달 주문 내부에서 검증하거나 외부 도메인(배송 대행 서비스)에 요청 할 것 같아서요.

2024-05-21 17:24 UTC, dkswnkk commented
슬랙 DM으로 피드백 주고받은 내용으로 다듬어보았습니다!!
피드백 계속 주시면 반영하겠습니다!

2024-05-22 13:56 UTC, hyunssooo requested changes
안녕하세요. 
모델링 잘 진행해 주셨습니다. :) 
가벼운 코멘트 남겨뒀는데요. 확인 부탁드려요. 
다음 요청에는 merge 하도록 하겠습니다.

2024-05-22 13:56 UTC, hyunssooo commented on README.md
> +```
```mermaid
sequenceDiagram
    actor User as 사용자
    participant Product as 상품
    participant Menu as 메뉴
    User ->> Product: 상품 가격 변경 요청
    Product ->> Product: 가격 정책 검증
    Product -->> Menu: 관련된 메뉴 가격 검증
    Menu ->> Menu: 관련 메뉴 가격 정책 검증
    alt 가격이 높을 경우
        Menu ->> Menu: 메뉴 숨김 처리
    end 
    Product ->> User: 상품 가격 변경 완료
```

이렇게 변경해 보는 것은 어떨까요? 메뉴가 숨김 처리 되었다고 상품에 전달하는 것은 없을 것 같아서요. 🙂

여기서도 조금 더 다듬어 볼 수 있을 것 같은데요. 
메뉴의 노출 여부가 변경되는 시점은 언제일까요? 상품의 가격이 변경된 후 아닐까요?

저희가 흔히 말하는 이벤트 개념에 가까울 것 같은데요.
`상품의 가격이 변경됨.` 이후에 메뉴에서는 숨김 처리 여부를 판단할 것 같아서요. 

```mermaid
sequenceDiagram
    actor User as 사용자
    participant Product as 상품
    participant Menu as 메뉴
    User ->> Product: 상품 가격 변경 요청
    Product ->> Product: 가격 정책 검증
    Product ->> User: 상품 가격 변경 완료
    
    Product -->> Menu: 상품 가격 변경 완료
    Menu ->> Menu: 관련 메뉴 가격 정책 검증
    alt 가격이 높을 경우
        Menu ->> Menu: 메뉴 숨김 처리
    end
```

2024-05-22 13:56 UTC, hyunssooo commented on README.md
> +- 메뉴를 숨김 상태로 변경할 때는 상품들의 총합 가격을 검증하지 않는다.
숨김에 대한 정책은 별도로 없는 것이니 생략해도 좋을 것 같아요.

2024-05-22 15:54 UTC, dkswnkk commented on README.md
> +```
mermaid에 alt라는 기능도 있었군요!! 

말씀하신 대로 메뉴의 숨김 처리는 가격이 변경되고 나서인데 이걸 놓쳤네요.. 자세하게 봐주셔서 감사합니다. 

> 메뉴의 노출 여부가 변경되는 시점은 언제일까요? 상품의 가격이 변경된 후 아닐까요?

이 부분도 반영했습니다!

2024-05-23 11:16 UTC, hyunssooo approved these changes
안녕하세요. 
모델링 미션 잘 진행해 주셨습니다. :) 
함께 고민하니 저도 즐거운 경험이였습니다.
다음 step 진행 부탁드릴게요!

2024-05-23 15:56 UTC, merged

2024-05-23 15:56 UTC, hyunssooo commented
아이고 깜빡하고 머지를 안했네요. 다음 step 진행 부탁드립니다!