Step1 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #382
Opened 2024-05-20 15:57 UTC by sjhello

처음 뵙겠습니다 리뷰어님!
리뷰 잘 부탁드립니다 😃

하실 말씀이 있으시다면 편하게 말씀해주세요! 감사합니다 :)

2024-05-22 14:43 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 메뉴그룹    | Menu Group        | 메뉴들을 특정한 기준대로 모은 `메뉴의 집합`이다 |
메뉴 그룹, 상품, 메뉴 등에 대한 명확한 예시를 추가해주시면 용어 이해에 더 도움이 될 것 같네요!

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 메뉴 노출 상태 | Menu Displayed    | 메뉴의 노출 상태를 말한다. 메뉴의 노출 상태는 `노출됨`, `숨김`이 있다 |
메뉴가 가지는 프로퍼티와 행위를 잘 정리해주셨네요.

메뉴 뿐만 아니라 다른 도메인들 하위에 용어들이 너무 많아지면 용어 사전의 가독성이 떨어질 것 같아요. 만약 그런 부분이 우려되신다면 프로퍼티와 행위를 분리해서 정리해도 좋을 것 같다는 생각이 드네요.

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 메뉴 숨김    | Hide Menu         | 메뉴를 숨긴다.                                   |
메뉴는 어떤 경우 숨겨질까요? 메뉴 도메인을 잘 이해하기 위해 어떤 경우 숨김 메뉴가 되는지 설명을 추가하면 어떨까요?

1. 사장님이 숨기는 경우
2. 가격 정책에 의해 자동으로 숨겨지는 경우

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 매장 주문의 상태    | Eat In Order Status   | 매장 주문의 상태는 `대기`, `수락`, `음식 제공됨`, `완료` 이다.       |
주문 타입 별 상태 흐름을 잘 표현해주셔서 한눈에 잘 이해가 되네요 👍

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 메뉴 이름    | Menu name         | 메뉴의 이름을 말한다. ex> 후라이드 콜라 세트                         |
메뉴 및 상품의 이름에는 비속어가 들어갈 수 없습니다. 해당 부분도 설명에 들어가면 어떨까요?

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +### 배달 주문
배달 주문에 포함되는 주소에 대해서도 정리하면 어떨까요?

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +### 주문
주문의 경우 주문 타입별로 수량에 대한 요구사항이 있습니다.

주문 도메인의 이해를 돕기 위해 관련 설명도 추가하면 좋을 것 같아요.

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 테이블 비어있음     | Clear                 | 테이블이 `사용중이지 않는 상태`를 말한다.              |
테이블 비어있음을 의미하는 clear가 동사로 비우는 행위 자체를 의미하는 것 같이 느껴지네요. 영문명을 수정하는건 어떨까요?

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 주문 테이블       | Order Table           | 손님들이 앉아서 식사 할 수 있는 키친포스의 테이블을 의미한다. |
다른 도메인과 다르게 이름이나 인원 수 등의 프로퍼티에 대한 정보가 빠진 것 같아요.

2024-05-22 14:43 UTC, kyucumber commented on README.md
> +| 테이블 비어있음     | Clear                 | 테이블이 `사용중이지 않는 상태`를 말한다.              |
테이블을 비울 때, 빈 테이블로 설정할 수 없는 경우도 있을 것 같아요. 용어의 이해를 돕기 위해 추가하면 어떨까요?

2024-05-22 14:43 UTC, kyucumber commented on README.md
>  ## 모델링
제가 세부적인 요구사항과 같은 부분도 적으면 어떨까 하는 부분이 다소 애매하게 느껴지실수도 있을 것 같아요.

용어 사전 정리의 경우 사실 정해진 답은 없습니다. 저는 해당 부분들이 포함되면 용어를 더 잘 이해할 수 있을 것이라 생각해서 넣으면 좋겠다고 말씀드리는거라 꼭 추가하진 않아도 괜찮습니다.

2024-05-23 13:30 UTC, sjhello commented
안녕하세요 리뷰어님!
동료와 함께 용어사전을 보충해보았습니다. 바쁘신 와중에도 리뷰 해주셔서 감사합니다 :)

2024-05-23 16:22 UTC, kyucumber approved these changes
용어사전 잘 정리해주셨네요.

다음 단계 진행을 위해 머지할게요!

2024-05-23 16:22 UTC, merged