🚀 1단계 - 용어 사전 만들기
next-step/ddd-strategic-design pull request #391
Opened 2024-05-22 14:18 UTC by dlfdyd96

안녕하세요, [1단계 용어 사전 만들기 미션] 페어이신 박지민님과 진행하였습니다!

리뷰 잘 부탁드립니다 🙇🏼

2024-05-23 14:56 UTC, Hyeon9mak requested changes
안녕하세요 일용님, 모델링 미션을 함께할 최현구입니다. 🙇‍♂️ 
용어사전 만들기 잘 진행해주셨어요!
몇 가지 코멘트 남겼으니 확인해주세요 😄

2024-05-23 14:56 UTC, Hyeon9mak commented on README.md
> +| 메뉴 노출 정책 | MenuExposurePolicy | 메뉴 노출 정책은 메뉴가 올바르게 노출되었는지 검증하는 정책이다. |
용어 사전은 일용님의 비즈니스에서 특정되는 유비쿼터스 언어들을 정리하는 것에 집중해야한다고 생각합니다.
`정책 (Policy)` 이라는 표현은 사실 일용님의 키친포스 애플리케이션이 아니더라도 상식적으로, 널리 사용되는 표현이죠!
이런 것들을 모두 정리하기엔 정리하시는 일용님도 귀찮고, 읽는 동료들도 '정말로 중요한 용어가 무엇인지' 파악이 어려워진다고 생각해요!
일용님 생각은 어떠신가요?

2024-05-23 14:56 UTC, Hyeon9mak commented on README.md
> +| 메뉴 노출 정책 | MenuExposurePolicy | 메뉴 노출 정책은 메뉴가 올바르게 노출되었는지 검증하는 정책이다. |
비속어의 경우 다른 곳에서도 활용되지 않을까요? 😉 
이런 용어는 공용으로 분리해보아도 좋을거 같아요!

2024-05-23 14:56 UTC, Hyeon9mak commented on README.md
> +| 조리 완료       | OrderServed                 | 조리 완료는 주문을 조리 완료하는 것을 나타낸다.                |
포장주문/매장주문/배달주문 이 하나의 주문으로 묶여있어
서로 인지할 필요가 없는 정보(배달 플랫폼, 배달 주소, 배달중 등)에 노출되어 있는데요,
각각의 주문을 완전히 서로 다른 영역으로 분리하여
서로가 필요한 정보만 명확히 갖고 있도록 분리해보는 건 어떨까요?

이 경계를 저희는 바운디드 컨텍스트라 부르는 것 같아요 😄 👍

2024-05-23 14:56 UTC, Hyeon9mak commented on README.md
> +| 주문 테이블       | OrderTable               | 주문 테이블은 주문을 받는 테이블이다.                            |
주문 테이블은 별도로 관리해볼 수도, 매장 주문에 엮어볼 수도 있을텐데요,
일용님께서 생각하시기엔 어떠한가요? 별도로 관리하는게 더 나을까요, 매장 주문에 엮는게 더 나을까요?
(정답은 없고 일용님의 의견을 여쭙는 코멘트입니다!)

2024-05-23 14:56 UTC, Hyeon9mak commented on README.md
> +| 배달 완료 정책    | DeliveryCompletionPolicy    | 배달 완료 정책은 주문이 올바르게 배달 완료되었는지 검증하는 정책이다.    |
배달을 받는 배달 대행사 혹은 라이더 관련 용어도 정리해보는 건 어떨까요? 😉

2024-05-24 05:08 UTC, dlfdyd96 commented on README.md
> +| 메뉴 노출 정책 | MenuExposurePolicy | 메뉴 노출 정책은 메뉴가 올바르게 노출되었는지 검증하는 정책이다. |
아하 그럼 정책(Policy)이라는건, 용어사전으로 정의는 하지 않고 요구사항으로만 정리해줘도 괜찮을까요? 
특히 '생성 정책' 은 없어도 괜찮을 것 같다는 생각입니다! 다만, `상품 가격 변경 정책` 과 같은 부분은 비즈니스상 보편언어로 명시하는게 좋을 것 같아요!

2024-05-24 05:12 UTC, dlfdyd96 commented on README.md
> +| 조리 완료       | OrderServed                 | 조리 완료는 주문을 조리 완료하는 것을 나타낸다.                |
요 부분도 페어분과 논의하다가 분리하고자 하는 욕심이 있었습니다..! 😄 
코드로 부터 요구사항을 정의하다보니 말씀하신 것 처럼 바운디드 컨텍스트로 분리해도 좋을 것 같더라구요
그런데 요구사항/용어사전을 분리하여 관리하다보면 기존 코드와 차이가 발생할 것 같아 이부분은 리펙토링에서 챙겨야하지 않을까? 라는 생각이었습니다.

2024-05-24 05:13 UTC, dlfdyd96 commented on README.md
> +| 주문 테이블       | OrderTable               | 주문 테이블은 주문을 받는 테이블이다.                            |
현재 주문테이블은 '매장 주문' 도메인을 위한 '지원 서브도메인'일 것 같아요! 그래서 제 생각엔 엮어가도 좋을 것 같아요

2024-05-25 00:38 UTC, Hyeon9mak approved these changes
안녕하세요 일용님! 피드백 잘 반영해주셨습니다!
용어 사전이 훨씬 가벼워지고, 정말 집중해야할 용어에만 집중할 수 있게 되었네요.
아주 간단한 추가 코멘트 하나 더 남겼으니, 다음 단계 진행과 함께 확인해주세요!
다음 단계에서 뵙겠습니다!

2024-05-25 00:38 UTC, Hyeon9mak commented on README.md
> +| 주문 항목 가격 | OrderLineItemPrice | 주문 항목 가격은 주문 항목의 가격이다.       |
`주문 배달중`, `주문 배달 완료` 같은 경우 포장 주문, 매장 주문에는 불필요한 정보죠 😄 
때문에 이런 주문 상태들도 각각 나누어 정리해보는 것도 좋을거 같습니다!

2024-05-25 00:38 UTC, Hyeon9mak commented on README.md
> +| 노출 메뉴    | ExposedMenu     | 노출 메뉴는 노출되는 메뉴이다.                 |
용어사전이 훨씬 간결해졌군요!!

> 상품 가격 변경 정책 과 같은 부분은 비즈니스상 보편언어로 명시하는게 좋을 것 같아요!

👍 👍

2024-05-25 00:38 UTC, merged