🚀 2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #394
Opened 2024-05-23 08:15 UTC by writer0713

안녕하세요. 리뷰어님.
`🚀 2단계 - 모델링 하기` 관련 pr 드립니다.

아직 감이 잘 오지 않아서 다른분들이 `속성` 과 `행위` 에 대해 정리한것 참고하여 진행했습니다.
사실 아직까지는 `요구사항` 과 `모델링` 의 차이점이 명확히 와닿지 않는것 같습니다.

2024-05-23 15:44 UTC, HackSung requested changes
모델링을 꼼꼼하게 잘 작성하신 것 같습니다. 👍 
피드백 남겨 드렸으니 확인 부탁드릴께요. 🙏

2024-05-23 15:44 UTC, HackSung commented on README.md
> +  - 서빙된(`Served`) 상태의 포장주문(`Takeout Order`) 만 완료(`Complete`) 할 수 있다.
용어사전에는 설명에는 서빙('Serve')이 상태라고 정의 되어 있는데 모델링에서는 서빙된('Served')으로 상태가 새로 나왔네요? 🤔 
만약 `Serve`가 상태가 아닌 행위라면 용어사전 설명을 수정하고 `Served` 상태를 용어사전에 추가하는 게 맞을 것 같은데 어떻게 생각하세요?

2024-05-23 15:44 UTC, HackSung commented on README.md
> +  - 메뉴의 가격(`Price`) 은 0원 이상이어야 한다.
모델링 문장을 읽다 보면 숫자 뒤에 단위가 붙는 경우와 붙지 않는 경우가 혼재 하는데 
문서의 일관성을 위해 모두 다 찾아서 단위를 붙여보는 건 어떨까요?
```suggestion
  - 구성상품 (`Menu Products`) 의 수량은 0개 이상이어야 한다. 
  - 메뉴의 가격(`Price`) 은 0원 이상이어야 한다.
```

2024-05-23 15:44 UTC, HackSung commented on README.md
> +  - 배달주문(`Delivery Order`) 을 접수하면 배달 대행사를 호출(`Call Delivery`) 한다.
배달 대행사를 호출할 때 어떤 정보들을 넘겨줘야 하는지에 대해서도 기술하면 더 명확해 질 것 같은데 어떻게 생각하시나요? 🤔

2024-05-23 15:44 UTC, HackSung commented on README.md
> +
필수는 아니지만 속성과 행위 외에도 도메인 이벤트에 대한 정의를 시도해 보는 건 어떠세요?
도메인 이벤트는 다른 도메인과의 상호작용을 위해 사용될 수 있는데요.
예를 들어 "상품 가격이 변경되었다"는 이벤트가 발생하면 
이를 감지하는 다른 도메인이 이에 반응하여 추가적인 작업을 수행할 수 있습니다.
이해를 돕기 위해 예시를 자세히 적어봐드릴께요. 😄 

```
### 도메인 이벤트

- 이벤트 이름: 상품 가격 변경에 따른 메뉴 숨김
- 발생 조건: 상품의 가격이 변경되었을 때
- 액션: 
  - 변경된 상품을 포함하는 모든 메뉴를 찾는다.
  - 각 메뉴에 대해, 메뉴의 가격과 메뉴 구성상품(`Menu Products`)의 금액 합을 비교한다.
  - 만약 메뉴의 가격이 메뉴 구성상품의 금액 합보다 크다면, 해당 메뉴를 숨긴다.
```

2024-05-23 15:44 UTC, HackSung commented on README.md
> +| 이름    | Name             | 상품의 이름을 의미한다.                             |
중복단어 제거, 지속적인 용어사전 관리 아주 좋습니다. 👍 👍

2024-05-23 15:44 UTC, HackSung commented on README.md
>  ## 모델링
> 요구사항 과 모델링 의 차이점이 명확히 와닿지 않는것 같습니다.

제가 생각하는 요구사항과 모델링의 차이점은 다음과 같습니다.
요구사항은 `무엇`에 초점을 맞추고 모델링은 `어떻게`에 초점을 맞춥니다. 
즉, 요구사항은 시스템이 무엇을 해야 하는지를 정의하고, 
모델링은 시스템이 어떻게 그 작업을 수행할 것인지를 정의합니다.
요구사항은 사용자의 관점에서 시스템을 바라보며 
모델링은 개발자의 관점에서 시스템을 바라봅니다. 
이는 요구사항이 사용자의 문제를 해결하는 방법을 찾는 데 초점을 맞추는 반면 
모델링은 그 해결책을 구현하는 방법을 찾는 데 초점을 맞춥니다.

쉽게 얘기해 모델링은 개발자가 코드를 구현하기 위해 참조하는 문서라고 이해하시면 될 것 같습니다.
참고로 [도메인 주도 설계 기본 요소]미션에서는 모델링에 따라 코드가 구현되었는가를 주로 리뷰하게 됩니다.

2024-05-23 15:44 UTC, HackSung commented on README.md
> +  - 메뉴(`Menu`) 는 특정 메뉴 그룹(`Menu Group`) 에 속해야 한다.
사소하지만 용어사전에는 메뉴 그룹 영문명이 띄어쓰기 없이 `MenuGroup`으로 정의 되어 있는데
일관된 단어로 수정하면 좋을 것 같아요.

2024-05-23 15:44 UTC, HackSung commented on README.md
> +    - 가격은 0원 이상이어야 등록 가능하다.
행위마다 행위에 따른 연관 정책들을 잘 정리해 주셨네요 👍 
참고로 정책을 행위와 같은 레벨로 분리하는 방법도 있습니다.

2024-05-25 05:49 UTC, writer0713 commented on README.md
> +  - 메뉴의 가격(`Price`) 은 0원 이상이어야 한다.
모두 단위 붙이겠습니다 :)

2024-05-25 05:51 UTC, writer0713 commented on README.md
> +  - 메뉴(`Menu`) 는 특정 메뉴 그룹(`Menu Group`) 에 속해야 한다.
전체적으로 일관성 있도록 수정하겠습니다!

2024-05-25 05:52 UTC, writer0713 commented on README.md
> +    - 가격은 0원 이상이어야 등록 가능하다.
@HackSung 
아래와 같이 정책을 빼내는걸 말씀하시는걸까요? 
- 행위
  - 행위 1
  - 행위 2
- 정책
  - 행위1 에 대한 정책1
  - 행위1 에 대한 정책 2

2024-05-25 07:13 UTC, writer0713 commented on README.md
> +  - 서빙된(`Served`) 상태의 포장주문(`Takeout Order`) 만 완료(`Complete`) 할 수 있다.
용어사전에서 `서빙 상태(Serve)`로 변경하고 모델링에서도 `서빙상태(Serve)` 를 사용하겠습니다 :)

2024-05-25 07:17 UTC, writer0713 commented on README.md
> +
@HackSung 
궁금한점이 있습니다.
해당 이벤트의 발생은 `상품` 도메인에서 발생하고 `메뉴` 도메인에서 해당 이벤트를 감지하여 메뉴를 숨겨야 할것 같은데요.
그럼 말씀하신것처럼 `도메인 이벤트` 를 따로 정의할 경우에는 어느쪽에 적어야하는지가 궁금합니다.
- 상품 도메인에 적는다.
- 상품, 메뉴 도메인 양쪽에 모두 적는다.

2024-05-25 07:23 UTC, writer0713 commented on README.md
> +  - 배달주문(`Delivery Order`) 을 접수하면 배달 대행사를 호출(`Call Delivery`) 한다.
어떤 정보들을 넘겨줘야 하는지 기술하면 추후 논의할때 좀 더 도움이 될것 같습니다.
히스토리 측면에서도 도움이 될것 같구요.

2024-05-25 07:28 UTC, writer0713 commented
@HackSung 
피드백 주신 부분들 적용했습니다.
추가로 궁금한 부분들 질문 남겼습니다 :) 
`Mermaid` 의 경우, 아직 `모델링` 이 확정되지 않은 상태라고 생각되어 확정된 이후에 `Mermaid` 를 사용하여 도식화 할 생각입니다.

꼼꼼한 리뷰 감사합니다!

2024-05-25 13:32 UTC, HackSung approved these changes
피드백 잘 반영해 주셔서 갈수록 모델링의 완성도가 높아 지는 것 같습니다. 👍 
나중에 코드 구현할 때 변수명 작명에도 도움을 받을 수 있을 것 같구요.
주신 질문에 답변도 남겼으니 확인하시고 다음 미션으로 넘어가시면 되겠습니다. 🚀

2024-05-25 13:32 UTC, HackSung commented on README.md
> +  - 서빙된(`Served`) 상태의 포장주문(`Takeout Order`) 만 완료(`Complete`) 할 수 있다.
아직 모델링에서 Served 영문명이 몇개 남아 있네요? 😄

2024-05-25 13:32 UTC, HackSung commented on README.md
> +
> 도메인 이벤트 를 따로 정의할 경우에는 어느쪽에 적어야하는지가 궁금합니다.

도메인 이벤트는 일반적으로 이벤트가 발생하는 도메인에서 정의합니다.
상품 도메인 부분에 상품 가격 변경 이벤트의 발생 조건과 이벤트를 정의하고
메뉴 도메인 부분에는 이 이벤트를 감지하고 처리하는 로직을 설명하는 것이 좋을 것 같습니다.

2024-05-25 13:32 UTC, HackSung commented on README.md
> +    - 가격은 0원 이상이어야 등록 가능하다.
네네 맞습니다. 😄 
정환님이 현재 정리한 패턴은 행위와 그에 대한 정책이 가까이 있어 특정 행위에 대한 정책을 쉽게 찾을 수 있는 장점이 있고
제가 알려드린 패턴은 행위와 정책을 명확하게 분리해 각각의 섹션을 별도로 살펴볼 수 있고 
중복되는 정책을 여러번 적지 않아도 되는 장점이 있습니다.
두가지 패턴 중 어느 것을 선택할지는 프로젝트의 요구사항이나 선호도에 따라 달라지는 것이니
정환님 편하신 대로 작성하시면 됩니다. 😃

2024-05-25 13:38 UTC, merged