Step3 : 기능 우선 패키지 구성하기
next-step/ddd-strategic-design pull request #414
Opened 2024-05-26 14:04 UTC by MaroKim

안녕하세요 노웅래 리뷰어님 

김성태 입니다. 

패키지 분리 및 step2 이전 내용 리뷰요청 드립니다.

맞습니다... 그때는 제거 했다 싶었는데.. 그래도 메뉴가 남더라구요...
그래서 어떻게 해야 잘 분리가 될지 고민을 많이 했는데...

결론부터 말씀드리면 메뉴를 분리 했습니다. 기존 메뉴의 속성중에 메뉴 이름만 남기고 
가격과 관련된 속성은 '메뉴상세'라는 용어로 분리를 했습니다. 
메뉴 상세에는 가격과, 메뉴상품, 메뉴 상태가 속성으로 정의 되어 있는데 
메뉴의 기능을 보면 생성을 제외하면 가격 변경, 상태 변경이 있습니다
하지만 상태변경도 결국 상품 가격에 영향을 받기 때문에 가격에 영향을 받는 메뉴 속성을 따로 분리하는게 좋지 않을까 싶었습니다. 

이렇게 변경하고 상품에서 가격이 변경되면 해당 상품의 id를 바탕으로 메뉴상세 쪽에 상태 업데이트 요청만 보내면 될것 같다는 생각입니다.

제가 잘못 생각하고 있다면 힌트를 부탁드리겠습니다 ㅠ 

그리고 이번 과제는 바운디드 컨텍스트를 기반으로 패키지를 단순 분리인지 변경된 용어사전 및 모델링에 맞춰 코드도 일부 수정을 해야하는 건지 감이 잡히지 않아.. 일단 도메인을 기반으로 패키지를 분리하였습니다. 

말씀해주시면 다시 열심히 해보겠습니다. 

감사합니다. :)

2024-05-26 15:27 UTC, wlroh commented
성태님 안녕하세요 😄 

핑퐁이 길어질 것 같아서 게더에서 말씀드리긴했는데, 우선 현재 README.md 를 보면 각각의 하위도메인 단위로 모델링이 되어 보여요 😢 
README.md 에서도 바운디드 컨텍스트 단위로 나눈 뒤에 모델링을 해보는 것은 어떨까요?

용어사전과 모델링은 바운디드컨텍스트 안에 있어야 진정한 힘을 발휘할 수 있다고 생각해요!

상품의 상품과 메뉴의 상품이 다르다고 느끼셨다면, 그것은 각각의 문맥에 따라 관심사가 다른 것을 나타내는 단서라고 생각해요.
즉, 컨텍스트 단위로 나눈 뒤 바운디드 컨텍스트 안에서 모델링과 용어사전을 다시 한번 업데이트 해보면 좋을 것 같아요!

> 그리고 이번 과제는 바운디드 컨텍스트를 기반으로 패키지를 단순 분리인지 변경된 용어사전 및 모델링에 맞춰 코드도 일부 수정을 해야하는 건지 감이 잡히지 않아.. 일단 도메인을 기반으로 패키지를 분리하였습니다.

이번 과제는 바운디드 컨텍스트 기반으로 패키지를 단순 분리하는 것이 맞아요! 
즉, 바운디드 컨텍스트 기반으로 용어사전과 모델링을 다시한번 수정해보시고 패키지만 수정해보시면 되요!

용어사전과 모델링에 맞춰 코드도 일부 수정하는 것은 다음 미션에서 진행하시면 됩니다!

추가로 더 궁금하신점이 있으면 편하게 연락주세요!

2024-05-26 15:27 UTC, wlroh requested changes
성태님 안녕하세요 😄 
미션 고생하셨습니다 👍 
코멘트 드린것이 있는데 확인부탁드려요!

2024-05-27 12:31 UTC, MaroKim commented
안녕하세요 노웅래 리뷰어님 

김성태 입니다. 

어제 늦은밤에 게더로 알려주셔서 감사합니다 ㅠ
말씀해주신데로 바운디드 컨텍스트로 구분해서 작성해보고자 했습니다.

상품, 메뉴, 주문 이렇게 바운디드 기준으로 생각해 보니 뭔가 도메인에 대해 더 명확해 지는 느낌인거 같습니다 

상품에서는 상품 관리만, 메뉴에서는 메뉴 관리만이라고 하셨던 부분이 좀 정리가 되는 거 같습니다. 
그리고 주문 같은 경우 하위 컨텍스트로 나누어서 작성을 해봤는데 모델링이 좀더 쉽게 느껴지고 잘 보이는 느낌입니다 ㅎㅎ 


몇가지 고민이 있었던것은 

1. 메뉴그룹과 메뉴를 하나로 정리를 해야했을지 입니다.
예시) 현재는 ###메뉴그룹, ###메뉴 이렇게 나누었는데 ###메뉴 안에서 다 정리를 해야하는건지 
메뉴라는 바운디드 컨텍스트에 해당되고 서로 연관성이 있는 부분이라 그렇게 했어야 할지 고민입니다.

2. 주문을 하위 컨텍스트로 나누다 보니 기존 ###주문에 대해 정의하고 모델링하는게 뭔가 중복적이고.. 그렇다고 
3가지 주문(포장, 배달, 매장)을 포함하기도 어려운거 같아서 ###포장 주문, ###배달 주문, ###매장 주문 
이렇게 3가지 하위 컨텍스트로 정리 했었는데 ###주문에 대해서도 내용을 따로 정리하는게 나은건지 고민입니다.


어제 말씀 잘해주셔서 이해가 되었는데 혹시 제가 작성한거에 아쉬운 점이 있다면 
과감하게 말씀해주시면 더 이해가 잘 될것 같습니다. 

부족한 저때문에 고생하시는것은 아닌지 ㅠㅠ 

말씀해주시면 또 열심히 고민해보고 과제가 끝난 뒤에도 한번 좋은 이야기를 서로간에 할 수 있도록 노력하겠습니다. 

감사합니다. :)

2024-05-28 12:47 UTC, wlroh commented
> 메뉴그룹과 메뉴를 하나로 정리를 해야했을지 입니다.
예시) 현재는 ###메뉴그룹, ###메뉴 이렇게 나누었는데 ###메뉴 안에서 다 정리를 해야하는건지
메뉴라는 바운디드 컨텍스트에 해당되고 서로 연관성이 있는 부분이라 그렇게 했어야 할지 고민입니다.

각각의 도메인의 생명주기와 어떤 관계인지 어떤 흐름으로 흘러가는지에 따라 달라질 것 같은데요!
현재 메뉴 바운디드컨텍스트안에서는 각각 분리해주신 모델링이 더 자연스러운 것 같아요

> 주문을 하위 컨텍스트로 나누다 보니 기존 ###주문에 대해 정의하고 모델링하는게 뭔가 중복적이고.. 그렇다고
3가지 주문(포장, 배달, 매장)을 포함하기도 어려운거 같아서 ###포장 주문, ###배달 주문, ###매장 주문
이렇게 3가지 하위 컨텍스트로 정리 했었는데 ###주문에 대해서도 내용을 따로 정리하는게 나은건지 고민입니다.

현재 모델링해주신것과 패키지 분리해주신것과 싱크가 안맞는 것 같아요. 
패키지로 구분해주신 것을 보았을 때 주문 바운디드 컨텍스트 안에 주문테이블 모델과 주문 모델로 구성되어보여요.
코멘트에도 달기는했는데, 각각의 주문마다 개별 바운디드 컨텍스트로 분리해보면 어떨까 생각이 들어요.
주문이 모두 같은 주문으로 보여지기는 않고 주문이 핵심도메인이기 때문에 좀더 각각의 바운디드 컨텍스트로 나눠서 관심사에 집중해보면 어떨까요?

2024-05-28 12:48 UTC, wlroh requested changes
성태님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
고민하신 부분과 리뷰하면서 코멘트 추가한 것이 있는데 확인부탁드려요!

2024-05-28 12:48 UTC, wlroh commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +package kitchenpos.menu.domain;
메뉴 바운디드 컨텍스트에 메뉴와 메뉴그룹으로 잘 구성해주셨어요 👍 👍

2024-05-28 12:48 UTC, wlroh commented on src/main/java/kitchenpos/order/domain/OrderRepository.java
> +package kitchenpos.order.domain;
현재 매장주문, 포장주문, 배달주문 모두 주문 바운디드 컨텍스트에 위치하고 있는데요!
같은 주문으로 보기에는 각 주문마다 다른점들이 있어서 각각의 바운디드 컨텍스트로 분리해보면 어떨까요?

2024-06-02 14:49 UTC, MaroKim commented
안녕하세요 노웅래 리뷰어님 

김성태 입니다. 

반영하는데 제가 좀 늦었네요 ㅠ

말씀해주신데로 주문에 대한 바운디드 컨텍스트를 나눠서 작업을 했습니다.

다만 바운디드 컨텍스트를 나누는데 있어서 

실제로는 주문이라는 하나의 테이블에서 주문 타입에 따라서 주문이 진행되고 처리되는 과정이 다름에 따라 

주문 엔티티에서 

@Inheritance(strategy = InheritanceType.SINGLE_TABLE) 를 적용해서 작업했습니다.

이렇게 나누다 보니 기존 테스트 코드 쪽에서도 원할하게 작동되지 않아서 테스트 코드 또한 반영하여 작업하였습니다.

나누어 작업하다가 기존 OrderLineItem, OrderType, OrderStatus, Order Entity는 

배달 주문, 매장 주문, 포장 주문 모두 공통으로 적용되는 클래스라서 Order 패키지에 남겨두었습니다.

피드백 주시면 남은시간 동안 최대한 많은걸 할수 있도록 노력하겠습니다.

감사합니다 :)

2024-06-03 15:54 UTC, wlroh commented
성태님 안녕하세요 😄 
작업해주신 커밋에서 코멘트를 달기에 범위가 커서 여기에 코멘트를 달았어요 😢 
아무래도 글로써 전달하다보니 전달이 잘 안될 수도 있어서 이해가 잘 안되시거나 궁금하신 점이 있으시면 편하게 연락주세요!

> 다만 바운디드 컨텍스트를 나누는데 있어서
실제로는 주문이라는 하나의 테이블에서 주문 타입에 따라서 주문이 진행되고 처리되는 과정이 다름에 따라
주문 엔티티에서
`@Inheritance(strategy = InheritanceType.SINGLE_TABLE)` 를 적용해서 작업했습니다.

하나의 테이블을 이용하는 것도 괜찮다고 생각해요. 다만, `기존 테이블이 하나의 테이블이였기 때문에` 이라는 이유때문에 바운디드컨텍스트에서 Order 라는 공통 도메인모델을 만드는 것은 지양해야한다고 생각해요

매장, 포장, 배달 각각의 도메인모델을 구성할 수도 있고, 공통도메인모델과 각각의 유형별로 도메인모델을 나눌수도 있지만 이것에 대한 결정은 DB 테이블구조보다는 도메인의 방향성이 더 중요하다고 생각해요!

> 나누어 작업하다가 기존 OrderLineItem, OrderType, OrderStatus, Order Entity는
배달 주문, 매장 주문, 포장 주문 모두 공통으로 적용되는 클래스라서 Order 패키지에 남겨두었습니다.

지금과 같은 방향으로 진행한다면 저는 개인적으로 orders 바운디드 컨텍스트 안으로 각각의 유형별로 패키지를 나누고 common/domain 에 OrderLineItem, OrderType, OrderStatus, Order Entity 구성하는 것을 선호해요.
다만, 이런 케이스일 경우 주문 컨텍스트 내에서는 POJO 로 도메인모델을 구현하고, infra 계층에 JPA Entity 를 구성하는 방법도 있어요!
현재 미션은 모델링이기 때문에 반영하실것까지는 없어요! 이런 방향도 있다? 로 말씀드리고자했어요 😄 

다만, 현재 구성해주신 방향으로 모델링만 수정해주시면 좋을 것 같아요!

---

추가로, common 에 대해서는 한번 고민해보시면 좋을 것 같아요 😄 
또한, 성태님이 생각하시는 중복은 무엇일까도 같이 고민해보면 좋을 것 같아요!

2024-06-03 16:00 UTC, wlroh requested changes
성태님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
코멘트 작성한 것이 있는데 확인부탁드리고, 글로써 전달하다보니 코멘트가 길어졌는데요
혹시 이해가 잘 안되시거나 궁금하신 점이 있으면 편하게 연락주세요!

2024-06-03 16:00 UTC, wlroh commented on README.md
> +## 주문
모델링 수정 잘 해주셨어요! 👍 
다만, 현재 구성해주신 코드와 모델링의 싱크가 안맞아서 모델링을 리팩터링한 코드에 맞게 수정부탁드릴게요!
이번 단계에서는 모델링을 하는 것이고 다음 미션에서 모델링을 코드로 구현하는 것이다보니 모델링을 최종적으로 성태님이 구성하시는 것으로 완성되었으면 좋을 것 같아요!

2024-06-09 13:38 UTC, MaroKim commented
안녕하세요 노웅래 리뷰어님 

김성태 입니다.

모델링 수정하여 리뷰 요청 드립니다.

웅래님 리뷰를 보고 다시 찾아보고 공부하고 느낀건, 제가 몇가지 실수를 했다고 느꼈습니다


1. 레거시에 얽매인 생각 및 개념
-> 사실 웅래님 말씀대로 기존 테이블이 하나의 테이블이었기 때문에 Order라는 공통 도메인을 만들게 된게 맞습니다.
리팩토링의 개념을 '과거의 레거시를 개선하자' 정도로만 자꾸 생각하고 있었던게 문제 같습니다.

2. 도메인 모델 == 엔티티
->  도메인 모델과 엔티티를 같은 개념으로 생각하고 있었습니다. 
지금 생각하는 도메인 모델은 특정 도메인의 비즈니스 규칙과 논리, 속성등을 표현한 모델이고
엔티티는 이러한 도메인 모델에서 식별자를 가지는 객체임을 이해했습니다.
사실 이부분을 잘못 생각해서 1번에서도 공통도메인이라는 생각을 한것 같습니다.


3. 공통 도메인의 필요성
-> 결론부터 말씀드리면 common에 대해 전부 삭제를 했습니다.
기존 OrderStatus, OrderType, OrderLineItem을 공통으로 표현하는게 '맞는가'?로 생각을 하다가
공통으로 표현 '할 수 있는가'? 로 생각을 바꿔봤습니다. 표현하기 어렵다고 생각했습니다.
OrderStatus는 사실 주문도메인 모델마다 다르고 이 프로세스는 언제든지 바뀔 수 있다고 생각이 들었습니다.
OrderType은 이미 도메인을 나눈 시점에서 필요할까 싶었습니다( 그래서 각 주문 엔티티에서는 type을 삭제했습니다)
OrderLineItem에서 사실 고민이 많았는데.. 지금 레거시상에서는 같은 항목이라고 생각되지만
저희가 실제로 가게를 가서 주문할때 배달용과 매장식사 용이 따로 있고 포장주문용은 가격이 더 저렴하게 책정되는등
여러가지 변수가 많이 생길것이라 생각이 되어 이것도 따로 분리를 하는게 맞다 
이러한 종합적인 이유로 공통 도메인은 필요가 없을 것 같다고 결론을 지었습니다.


요청을 늦게 드리게 되었습니다 ㅠ 

확인 부탁드리고 수정할게 있으면 남은 기간내에 최선을 다 해보겠습니다.

감사합니다~!

2024-06-09 16:47 UTC, wlroh commented
성태님 안녕하세요 😄 
> 공통 도메인의 필요성
-> 결론부터 말씀드리면 common에 대해 전부 삭제를 했습니다.
기존 OrderStatus, OrderType, OrderLineItem을 공통으로 표현하는게 '맞는가'?로 생각을 하다가
공통으로 표현 '할 수 있는가'? 로 생각을 바꿔봤습니다. 표현하기 어렵다고 생각했습니다.
OrderStatus는 사실 주문도메인 모델마다 다르고 이 프로세스는 언제든지 바뀔 수 있다고 생각이 들었습니다.
OrderType은 이미 도메인을 나눈 시점에서 필요할까 싶었습니다( 그래서 각 주문 엔티티에서는 type을 삭제했습니다)
OrderLineItem에서 사실 고민이 많았는데.. 지금 레거시상에서는 같은 항목이라고 생각되지만
저희가 실제로 가게를 가서 주문할때 배달용과 매장식사 용이 따로 있고 포장주문용은 가격이 더 저렴하게 책정되는등
여러가지 변수가 많이 생길것이라 생각이 되어 이것도 따로 분리를 하는게 맞다
이러한 종합적인 이유로 공통 도메인은 필요가 없을 것 같다고 결론을 지었습니다.

👍 👍 많은 고민과 다시한번 모델링 관련해서 정리해보신 시간이였던 것 같아서 좋네요 😄 
말씀주신대로 현재 도메인 전문가가 없기 때문에 더 고민되셨던 것 같아요!
이해관계자 모두가 동의하고 공감하는 모델링을 만드는 과정이 중요한 것 같아요
현재 이해관계자는 저와 성태님이라고 생각하고 말씀주신 방향에 대해서 너무 동의하고요!

추가로 성태님이 말씀하신 것이 결국 매장, 포장, 배달 주문이 중복이라 생각하셨다가 중복이 아닌 것으로 생각이 바뀌면서 모델링을 수정해주신 것으로 보여져요!
저는 중복이란 단순히 코드가 동일하다 혹은 현재시점의 행위가 똑같다고 중복이라고 보지 않아요!
변경이 이뤄졌을 때 동일하게 변경이 이뤄지는 것이 중복이라고 생각해요. 
성태님이 작성해주신 내용을 보니 성태님도 고민하시면서 변경이 이뤄졌을 때 동일하게 변경이 안되는 것이라고 생각하시면서 중복이 아니라 판단하신 것 같아보이네요 😄 👍 

---

이번 미션의 경우 모델링 과정이 핵심이 최종적으로 나온 모델링의 결과를 바탕으로 다음 미션에서 전술적설계를 통해 코드로 만든다고 보는대요!
현재 작성해주신 모델링도 수정 부탁드릴게요!

주문이라는 하나의 바운디드 컨텍스트 안에서 도메인모델을 구성하신 것으로 보여지네요 😢 

그리고, 미션이 거의 끝나감에 따라 다음 리뷰 요청주시면 머지할 수 있을 것 같은데요! 혹시 궁금하신점이 있으시면 리뷰요청 주시면서 같이 말씀부탁드려요!

마지막으로, 메타인지를 위해 성태님의 언어로 표현해보는 것을 정말 추천하는데요! 잡담채널에 재성님이 올려주신 글을 보면서 성태님의 언어로 표현해보시길 추천드릴게요!
댓글로 작성하기 부담스럽다면 개인적으로라도 꼭 정리해보시길 추천드려요!


2024-06-09 16:50 UTC, wlroh requested changes
성태님 안녕하세요 😄 
고민 많으셨던 것 같았는데 잘 반영해주셨습니다 👍 
고민의 결과가 모델링에 반영이 안된 것 같아요 😢 
확인부탁드려요!

2024-06-10 13:48 UTC, MaroKim commented
안녕하세요 노웅래 리뷰어님, 김성태 입니다~!

죄송합니다 ㅠ 도메인 모델을 수정하면서 미처 챙기지 못했습니다.

모델링을 수정하였습니다. 주문에서 벗어난 배달주문, 포장주문, 매장주문 3가지의 주문 형태로 수정하고 
OrderType은 불필요하여 삭제하고 주문테이블은 매장주문과 같이 있는것이 좋을 것 같아 위치를 수정하였습니다.

```
중복이란 단순히 코드가 동일하다 혹은 현재시점의 행위가 똑같다고 중복이라고 보지 않아요!
변경이 이뤄졌을 때 동일하게 변경이 이뤄지는 것이 중복이라고 생각해요.
```
저는 이 말씀에서 중복이라는게 어떤거다라는게 확 와닿는 말씀이었습니다. 너무 감사드립니다. 👍 

저번에 리뷰주신 부분에 관련해서 몇가지 여쭤보고 싶은 사항이 있습니다. 

1. 중복에 대한 심화(?)
3번째 과제를 진행하면서 저는 매장주문 도메인에서 상태를 변경하는 메소드를 작성했습니다.
accept, served, complete등의 상태를 변경할 수 있는 코드를 작성했는데 
사실 이 상태 변경 프로세스는 변경하기전에 이전 상태를 가지고 있는지 확인하고 요청한대로 상태를 변경하는 코드 입니다. 흐름만 봤을때는 비슷한 조건 체크와 비슷한 기능을 하는 코드라서 어떻게든 중복을 제거한 코드를 만들고 싶었지만 명확하고 이해하기 쉬운 코드를 위해 메소드를 분리했습니다. 노웅래님께서는 어떻게 생각하시는지 궁금합니다.

2. 주문 테이블에 대한
도메인 모델링에 대해서는 이해했습니다 다만, 실제 구현된 테이블 구조에 대해서는 이렇게 하는게 맞나 궁금합니다.
주문이라는 테이블은 식별자와, 타입 정도의 컬럼을 가지고 배달주문, 포장주문, 매장주문이라는 각각의 테이블이 주문 테이블의 식별자를 참조하는 구조를 생각했습니다. 실례지만 간단하게만이라도 의견을 여쭙고 싶습니다.


제가 DDD에 대해 이해가 느려서 웅래님을 힘들게 한건 아닌가 싶습니다 ㅠ 
저는 웅래님과 같이 거의 한달정도 핑퐁(?) 했던 시간이 기억에도 많이 남고 좋은 공부가 되었던 것 같습니다.
저번 리뷰에서 말씀하신것 처럼 메타인지를 위한 표현도 이번주내로 정리하면서 꼭 해보도록 하겠습니다.

감사합니다 :)

2024-06-10 15:26 UTC, wlroh commented
> 3번째 과제를 진행하면서 저는 매장주문 도메인에서 상태를 변경하는 메소드를 작성했습니다.
accept, served, complete등의 상태를 변경할 수 있는 코드를 작성했는데
사실 이 상태 변경 프로세스는 변경하기전에 이전 상태를 가지고 있는지 확인하고 요청한대로 상태를 변경하는 코드 입니다. 흐름만 봤을때는 비슷한 조건 체크와 비슷한 기능을 하는 코드라서 어떻게든 중복을 제거한 코드를 만들고 싶었지만 명확하고 이해하기 쉬운 코드를 위해 메소드를 분리했습니다. 노웅래님께서는 어떻게 생각하시는지 궁금합니다.

이부분에 대해서는 담당리뷰어분과 이야기해보시면 좋을 것 같아요 😄
미션을 진행하시면서 관련한 문맥에 대한 이해도가 없어서 말씀드리기 조심스럽네요 ㅎㅎ

> 주문 테이블에 대한
도메인 모델링에 대해서는 이해했습니다 다만, 실제 구현된 테이블 구조에 대해서는 이렇게 하는게 맞나 궁금합니다.
주문이라는 테이블은 식별자와, 타입 정도의 컬럼을 가지고 배달주문, 포장주문, 매장주문이라는 각각의 테이블이 주문 테이블의 식별자를 참조하는 구조를 생각했습니다. 실례지만 간단하게만이라도 의견을 여쭙고 싶습니다.

DB 테이블을 어떻게 가져가는지에 대해서는 정답이 없다고 생각해요. 또한 너무 많은 방법이 있어서 우선 상황을 봐야할 것 같아요
엔티티와 테이블을 동일하게 가져갈지, 다르게 가져갈지 그렇게 했을 때 장단점이 무엇이 있을지
그리고 DB 마이그레이션이 가능한 상황인 것인지? 안된다면 기존데이터와 신규 데이터 포맷을 다르게 가져갈 수 있는지

즉, 현재 상황에서 어떤 방향들이 있고 트레이드오프 영역이 무엇인지 확인해서 결정하는 것이 최선의 방법이지 않을까해요

2024-06-10 15:32 UTC, wlroh requested changes
성태님 안녕하세요 😄 
피드백 반영해주신 것 확인했는데요!
궁금한 부분이 있어서 코멘트 작성했어요 
확인부탁드려요!

2024-06-10 15:32 UTC, wlroh commented on README.md
> +  - `NumberOfGuests`를 변경 시, 0명이상이 필요하다.
성태님이 최종적으로 생각하는 모델링이 어떻게 되는 것일까요?
패키지구조로 보게되면 매장주문 컨텍스트 안에 `매장주문`과 `주문테이블` 도메인모델을 보고계신것으로 보여져요.
하지만 모델링에서는 각각 따로 정리되어 있어서요 😢

2024-06-11 13:45 UTC, MaroKim commented
안녕하세요 노웅래 리뷰어님, 김성태 입니다.

말씀해주셧던 부분에 대해 수정했습니다 ( 주문테이블은 매장주문 도메인 모델에 포함시키기 )


수정을 하면서 음.. 메뉴에 대해서도 메뉴그룹과 메뉴를 포함하여 모델링 했기 때문에 

해당 부분에 대해서도 포함해서 작업을 했고 요구사항에 대해서도 기존에 주문 하나로만 작성이 되어 있었는데

모델링을 나눈것처럼 표시하면 더 이해가 잘 되지 않을까 하는 마음에 나누어서 작성했습니다.

DM으로도 말씀드렸지만 마지막까지 꼼꼼히 봐주셔서 정말 감사합니다 :)

2024-06-12 19:37 UTC, wlroh commented
성태님 안녕하세요 😄 
미션 진행하시느라 정말 고생많았습니다! 👍 👍 

최종적으로 수정해주신 모델링보았는데 제가 잘못이해한 것일 수 있지만 하나의 컨텍스트 별로 꼭 하나의 모데인모델일 필요는 없다고 생각해요!

성태님 수정해주신 것을 보았을 때 매장주문의 경우 크게 `매장주문(EatInOrder)` 도메인모델과 `주문테이블(OrderTable)` 도메인 모델이 있고
세부적인 도메인 모델들이 보여져요.

그렇다면 가독성을 위해 `매장주문(EatInOrder)`  과 `주문테이블(OrderTable)` 로 다시한번 분리해주어도 가독성 측면에서는 좋을 것 같다는 생각이 들었어요!

모델링에는 정답이 없어서 제 개인적인 의견이였고, 이해관계자 모두 쉽게 이해하고 가독성이 좋아지도록 각각의 컨텍스트 안에서도 도메인모델을 분리해볼 수 있다고 생각해요

모델링 미션 정말 고생많으셨고 실무에서도 이번에 학습한 내용 바탕으로 잘 적용하시길 응원하겠습니다!

2024-06-12 19:41 UTC, wlroh approved these changes
성태님 안녕하세요 😄 
피드백 잘 반영해주셨습니다 👍 
끝까지 미션 정말 고생많으셨어요! 
아직 진행중이신 미션이 있다면 응원할게요 🔥

2024-06-12 19:42 UTC, merged