feat(modelling) : 도메인 모델링
next-step/ddd-strategic-design pull request #419
Opened 2024-05-28 07:48 UTC by xxxx-jeung

안녕하세요 현수님!

두번째 과제 도메인 모델링 제출합니다!
너무 늦어서 죄송합니다!!

2024-05-29 15:24 UTC, hyunssooo requested changes
안녕하세요. 
많이 늦어 죄송합니다. 
몇 가지 코멘트 남겼는데요. 함께 고민해 보면 좋을 것 같아요!

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +### 상품
이번 step 도 용어 사전과 마찬가지로 저와 함께 프로덕트를 만들어 가는 관점으로 봐주시면 좋을 것 같습니다! :slightly_smiling_face:
그래서 코멘트 반영보다는 제웅님의 의견을 적극적으로 표현해 주시고 저와 의견 교환으로 모델링을 만들어 간다는 관점으로 봐주시면 좋을 것 같아요!

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +- `product` 행동
속성과 행동으로 잘 나눠 주셨습니다. :)

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +    - `product name`가 비어있으면 등록할 수 없다.
행동 별로 나눠서 표현해 보는 것은 어떨까요? 

- 행동
  - 등록할 수 있다.
    - // 제약 조건 등등
  - 가격을 변경할 수 있다.
    - // 제약 조건 등등

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +    - `menu status`는 상황에 따라 `available menu`, `unavailable menu` 설정 된다.
메뉴가 처음에 등록될 경우 `available menu` 인가요? 코드 상에서는 요청 값에 따라 다를 것 같아서요!

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +
수량의 대한 제약 조건을 조금 더 명확하게 나타내는 것은 어떨까요? 

```java
        for (final MenuProduct menuProductRequest : menuProductRequests) {
            final long quantity = menuProductRequest.getQuantity();
            if (quantity < 0) {
                throw new IllegalArgumentException();
            }
          ..
        }
```

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +- `order table` 행동
속성에 가지고 있다는 것은 order은 orderTable에 속한다는 의미일까요? 🤔

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +  - `quantity`과 `price`가 있다.
order menu 도출 👍

2024-05-29 15:24 UTC, hyunssooo commented on README.md
> +
주문은 각각 `DELIVERY`,`TAKEOUT`,`EAT_IN` 별로 나눠 보는 것은 어떨까요? 
각각 다른 BC에 속할 수 도 있지 않을까요? 
이 부분에 대해서는 어떻게 생각하실까요?

2024-05-30 15:36 UTC, xxxx-jeung commented on README.md
> +
음 저도 이걸 나누는게 더 명확하게 보일 것 같습니다.
그런데 BC에 속할 수 있다는 말씀이 어떤 의미일까요?
B2B, B2C를 말씀하시는걸까요??

2024-05-30 16:22 UTC, xxxx-jeung commented on README.md
> +    - `menu status`는 상황에 따라 `available menu`, `unavailable menu` 설정 된다.
넵 맞습니다 해당 부분은 삭제하고 요청 값에 따라 다르게 했습니다!

2024-05-30 16:23 UTC, xxxx-jeung commented on README.md
> +- `order table` 행동
이것도 잘못돼서 다시 수정했습니다!

2024-05-30 16:24 UTC, xxxx-jeung commented
>행동 별로 나눠서 표현해 보는 것은 어떨까요? 행동 등록할 수 있다. // 제약 조건 등등 가격을 변경할 수 있다. // 제약 조건 등등

전체적으로 수정했습니다..!

2024-05-30 16:29 UTC, hyunssooo commented on README.md
> +
앗 bounded context 입니당..!

2024-05-31 02:24 UTC, xxxx-jeung commented on README.md
> +
으으음.. 다시 생각해보니까 나누면 명확해 보일뿐 나눠야 할 마땅한 이유를 찾기가 어렵네요
주문 영역에 포함되는 부분이고, 주문을 하기 위해 타입에 맞게 배달, 가져가기, 먹고가기가 존재합니다

주문 엔티티에서 전부 관리할 수 있는데, 만약 분리하게 된다면 어떤 이점이 보일까요?
제가 생각하는 이점은
- 주문과 배달 영역이 나뉘면서 주문 엔티티에 대한 의존도가 낮아진다(?)
- 코드가 간결해져서 가독성이 좋아진다.

단점은
- 배달 영역을 확인하는데 한번 더 들어간다.

음.. BC를 이해한거같지만 뭔가 애매하게 이해한거같네요.... 음.. 어떻게 해야 잘 보일 수 있을까요?

2024-05-31 16:16 UTC, hyunssooo approved these changes
안녕하세요. 
모델링 미션 잘 진행해 주셨습니다. :) 
말씀주신 부분에 궁금한 부분 코멘트로 남겼는데 확인 부탁드릴게요!
다음 step 진행도 부탁드립니다!

2024-05-31 16:16 UTC, hyunssooo commented on README.md
> +
네, 정답은 없다고 생각합니다. :) 
제가 생각한 장점은 DELIVERY,TAKEOUT,EAT_IN 별로 필요 없는 부분은 접근 조차 가능하지 않다는 점이에요! 
orderTable, delivery, order status
그리고 type 에 따른 분기는 없겠죠! 

말씀하신 단점은 제가 조금 이해가 안되는데 조금 더 설명 가능하실까요? 

> 어떻게 해야 잘 보일 수 있을까요?

이 부분은 view를 말씀하실까요?

2024-05-31 16:17 UTC, merged

2024-06-01 02:31 UTC, xxxx-jeung commented on README.md
> +
> 배달 영역을 확인하는데 한번 더 들어간다.
넵 이건 주문 도메인을 들어가면 배달 영역이 같이 있어서 한번에 확인이 가능한데
주문 도메인과 배달 도메인을 따로 나뉘게 된다면, 배달 부분을 확인하고 싶으면, 바로 확인이 가능하지만, 어떤 주문인지를 모른다고 이해를 했습니다!

그래서 주문 도메인을 먼저 확인하고 배달 도메인을 확인해야지 주문과 배달을 확인할 수 있다고 이해하는거죠!
그래서 배달 영역을 확인하는데 한번 더 들어간다라는 의미는, 자세히 확인하고 싶다면 주문도 같이 확인해야 한다는 부분에서 그렇게 표현했습니다!

제가 설명을 상세히 하지 못했네요! 
@hyunssooo

2024-06-01 02:42 UTC, xxxx-jeung commented on README.md
> +
> 이 부분은 view를 말씀하실까요?

제가 포괄적으로 질문을 드린 것 같네요!!
드리고 싶은 질문은 이렀습니다.

현수님은 바운더리 컨텍스트를 나눌 때 자신만의 기준은 무엇인지, 컨텍스트를 잘 나눌 수 있는 요령, 방법은 무엇인지 궁금합니다!
다른 분들은 컨텍스트를 어떤 기준, 방법으로 나누는지 알아보고 저와 어떻게 다른지를 비교해보려고 합니다!

이렇게 인터뷰를 하는식으로 얘기하면 공부가 더 잘 되더라구요..!

@hyunssooo