step2 : 모델링 하기
next-step/ddd-strategic-design pull request #421
Opened 2024-05-29 22:25 UTC by wsdf25867

안녕하세요

step 2 모델링하기 미션 리뷰 요청드립니다!

모델링이 처음이라 많이 어색하네요

잘 부탁 드립니다

2024-05-30 09:07 UTC, sah3122 requested changes
모델링 작성 잘해주셨습니다 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드려요 😄

2024-05-30 09:07 UTC, sah3122 commented on README.md
> +- `Name`에 비속어를 사용할 수 없다.
```suggestion
- `Name`은 `Profanity Client`을 통하여 `Profanity`를 검증하고 비속어는 사용할 수 없다.
```
요구사항 문서와 모델링 문서의 다른점은 조금더 명확한 표현을 남기는것도 포함된다고 생각합니다 😄 
이 과정에서 용어사전에 정의한 용어들을 활용하여 모든 이해관계자가 이해할수 있게 표현하는것도 중요합니다. 
현재 비속어는 용어사전에 포함되어 있지만 비속어를 검사하는 시스템에 대해서는 용어사전에 빠져있어요. 
모델링을 진행하며 새롭게 발견된 용어를 추가하고, 모델링 문서를 다듬어 보세요 !

2024-05-30 09:07 UTC, sah3122 commented on README.md
> +- `Menu` 는 비노출 할 수 있다.
용어 사전에 정의한 용어로 표기해보세요 😄

2024-05-30 09:07 UTC, sah3122 commented on README.md
> +- `MenuGroup` 등록 정책
해당 모델링은 어떤것을 의미할까요 ?

2024-05-30 09:07 UTC, sah3122 commented on README.md
> +```
flowchart 를 활용하여 주문 상태의 흐름을 정의해주신것 좋네요 👍 
조금더 나아가 상태를 변경하는 행위도 모델링 문서에 작성해보세요. 
프로젝트에 처음 참여하는 사람들도 모델링 문서를 통해 어떤 기능을 제공하는지 한눈에 알수 있으면 좋을것 같습니다 💯

2024-05-30 09:07 UTC, sah3122 commented on README.md
> +- `OrderTable` 은 주문이 모두 완료되고 손님이 없으면 빈 테이블이 된다.
```suggestion
- `OrderTable` 을 빈 테이블로 설정할수 있다.
    - `OrderTable` 은 주문이 모두 완료되고 손님이 없어야 한다. 
```
개인적으론 모델링 문서를 위와 같이 정의하여 요구사항과 제약조건을 한눈에 알수 있게 표현하는것을 좋아하는데 😄 
위와 같은 모델링 작성법에 대해 지우님의 의견이 궁금합니다 !

2024-05-30 10:11 UTC, wsdf25867 commented on README.md
> +- `MenuGroup` 등록 정책
모델링을 지우고 쓰고 하다보니 미처 못지운 부분이 남아있었네요

2024-05-30 10:20 UTC, wsdf25867 commented on README.md
> +- `OrderTable` 은 주문이 모두 완료되고 손님이 없으면 빈 테이블이 된다.
제약조건이 한개정도나 한줄로 표현가능한 정도라면 한번에 표현하는 것도 괜찮다고 생각합니다

빈 테이블로 설정하는 요구사항의 경우 제약 조건이 2가지가 있기에 나눠서 쓰는 방법 또한 좋아보입니다!

2024-05-30 10:40 UTC, wsdf25867 commented on README.md
> +- `Name`에 비속어를 사용할 수 없다.
모델링 문서에서 명확한 표현을 남기는 것도 포함된다는 말씀은 동의합니다

그런데  Client 라는 말이 Server & Client 의 개념에서 사용되는 개발자의 언어로 봐야할지,

아니면 Server & Client 개념은 너무 유명하고, 모르는 사람이 없다고 봐야할지 모든 이해관계자가 이해할 수 있는

언어를 사용하는게 쉽지 않은 것 같습니다!

2024-05-30 10:56 UTC, wsdf25867 commented
리뷰내용 반영해서 재 요청 드립니다!

2024-05-30 10:56 UTC, wsdf25867 commented on README.md
> +```
행위도 작성하면 확실히 조금 더 명확하게 표현이 가능할거 같습니다

2024-05-31 05:55 UTC, sah3122 commented on README.md
> +- `Name`에 비속어를 사용할 수 없다.
예시로는 `Profanity Client`을 사용하였지만 말씀 주신것처럼 모든 이해관계자가 알수 있는 용어로 변경하여 작성하는것이 좋을것 같습니다 😄 `Profanity System`과 같이 정의하여 용어사전에 등록하는건 어떨까요 ?

2024-05-31 05:57 UTC, sah3122 commented
저희팀에서는 프로젝트 초기에 모델링을 작성하는 편입니다. 
초기에 작성한 문서가 잘 관리되고 있다고는 이야기 드리기 힘들것 같아요 🙏 
이전에 경험한 프로젝트에서는 모든 이해관계자가 모여 모델링, 용어사전 정리, 이벤트 스토밍을 진행하였습니다 !

2024-05-31 05:58 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
질문에 대한 답변 남겨두었는데 확인 부탁드리며 다음 미션도 화이팅 해주세요 !

2024-05-31 05:58 UTC, sah3122 commented on README.md
> +    - 손님이 없어야 한다.
다른 모델링도 요구사항과 제약조건을 나누어 작성해보는것도 좋을것 같아요 👍

2024-05-31 05:58 UTC, merged