🚀 2단계: 모델링 하기
next-step/ddd-strategic-design pull request #425
Opened 2024-06-01 09:09 UTC by dev-yoonjung

안녕하세요, 리뷰어님!
늦었지만 PR 올립니다. 잘 부탁드립니다. :) 

아, 그리고 저번 미션에서 용어사전을 요구 사항이 아닌 소스 코드를 보고 작성했어서 리뷰어님이 남겨주신 코멘트와 함꼐 다시 작성해보았습니다.

# 요구 사항

- [x] 키친포스의 요구 사항과 용어 사전을 기반으로 README.md에 모델링을 한다.

2024-06-01 16:25 UTC, liquidjoo requested changes
안녕하세요 윤정님 :)
2단계 모델링 잘해주셨어요 
몇 가지 코멘트 남겼습니다~
확인하고 다시 요청해 주세요 🙇

2024-06-01 16:25 UTC, liquidjoo commented on README.md
> +  - 상품 가격
요구사항과 모델링은 어떤 차이가 있을까요?

2024-06-01 16:25 UTC, liquidjoo commented on README.md
> +- 메뉴의 가격이 메뉴에 속한 상품 금액의 합보다 높을 경우 메뉴를 노출할 수 없다.
용어사전의 용어를 활용해보면 더욱 좋을 것 같아요 :)
> 모델링을 조금 더 자세히 표현해 보면 어떨까요?
> `Menu` 는 사용자들이 식별할 수 있는 `MenuName` 을 가진다

2024-06-01 16:25 UTC, liquidjoo commented on README.md
> +### 매장 주문(Eat-in Order)
주문 영역 또한 위의 코멘트를 참고해서 변경해 보면 좋을 것 같아요~

2024-06-02 04:01 UTC, dev-yoonjung commented on README.md
> +  - 상품 가격
아직 DDD에 대해서 깊은 공부를 한 것은 아니지만

**개인적인 생각**으로는 
요구사항정의서는 해결해야하는 문제라고 생각하고 
문제를 쉽게 해결하기 위해서 `Bounded Context`와 `Domain`을 나눈다고 생각하기 떄문에 
세부적인 내용은 다른 것이 없다라고 생각이 듭니다.

2024-06-02 04:02 UTC, dev-yoonjung commented
안녕하세요, 리뷰어님.

코멘트 남겨주신 대로
> `Menu`는 사용자들이 식별할 수 있는 `MenuName` 을 가진다
이렇게는 너무 힘들더라구요....

그리고 이전에는 도메인의 속성과 속성에 대한 정책으로만 작성했던 것 같아 
내용을 추가했습니다.

2024-06-03 03:00 UTC, liquidjoo commented on README.md
> +  - 상품 가격
모델링을 통해 개발을 진행할 때 모든 팀원이 같은 코드로 이해할 수 있어야 한다고 생각이 드는데요 :)
그럴 때 일 수록 변수명, 클래스명 등 명확히 표현해주면 모델링의 의미가 커질 것 이라고 생각이 듭니다

2024-06-03 05:54 UTC, liquidjoo requested changes
안녕하세요 윤정님 :)
2단계 피드백 반영 잘해주셨어요
조금 더 고민해볼만한 코멘트 남겼습니다
확인하고 다시 요청해 주세요 🙇

2024-06-03 05:54 UTC, liquidjoo commented on README.md
> +| 포장 주문 항목 가격 | takeout order line item price         | 포장 주문 항목에 대한 가격                            |
👍

2024-06-03 05:54 UTC, liquidjoo commented on README.md
> +  - `products`를 조회한다.
https://nextstep-members.slack.com/archives/C05MEQV4695/p1716892333772839

위의 글을 한번 읽어보고 모델링을 조금 더 자연스럽게 변경해 보면 어떨까요?

2024-06-03 05:54 UTC, liquidjoo commented on README.md
> +  - `menuGroups`를 조회한다.
코멘트 주신 것 처럼 모델링이 생각보다 힘든 작업이며 시간을 많이 사용하는 미션 중 하나 입니다
전략적 설계의 일부분인 만큼 모델링에 대해 고민을 더 해보시면 좋을 것 같아요

2024-06-06 06:01 UTC, dev-yoonjung commented
안녕하세요, 리뷰어님. 
모델링 수정했습니다.

2024-06-06 18:55 UTC, liquidjoo approved these changes
안녕하세요 윤정님 :)
피드백 반영 잘해주셨어요 👍 
다음 단계 진행해 주세요 🙇

2024-06-06 18:55 UTC, liquidjoo commented on README.md
> +- `Menu`를 고객이 볼 수 없도록 숨길 수 있다.
피드백 반영 👍 
꼼꼼하게 모델링 해주신 점 너무 좋습니다!

2024-06-06 18:55 UTC, liquidjoo commented on README.md
> +- `DeliveryOrder`은 `WAITING` ▶︎ `ACCEPTED` ▶︎ `SERVED` ▶︎ `DELIVERING` ▶︎ `DELIVERED` ▶︎ `COMPLETED`의 순서로 주문이 진행된다.
모델링을 함에 따라 오히려 편하게 읽을 수 있게된 것 같아서 더욱 좋네요

2024-06-06 18:55 UTC, liquidjoo commented on README.md
> +- `TakeoutOrder`은 `WAITING` ▶︎ `ACCEPTED` ▶︎ `SERVED` ▶︎ `COMPLETED`의 순서로 주문이 진행된다.
요구사항, 용어 정리를 통해서 모델링을 만들었을 때 
모델링이 갖는 의미가 어떤 것인지 조금씩 알아가는 과정이라 생각이 드네요!
그 과정을 잘 따라 주셔서 감사합니다

2024-06-06 18:55 UTC, merged