docs(README.md): 모델링 추가
next-step/ddd-strategic-design pull request #43
Opened 2020-02-23 07:21 UTC by withalice

모델링 추가하였습니다.
최대한 간결하게 핵심만 넣으려 했는데 어렵네욥..ㅎ
리뷰 부탁드리겠습니다!

2020-02-23 08:55 UTC, sihoony requested changes
코멘트를 남겼습니다.^^
궁금하신점이 있으시면 슬랙이나 코멘트 남겨주세요.^^

2020-02-23 08:55 UTC, sihoony commented on README.md
>  ## 모델링
제 생각의 모델링은 구현의 전단계이며 모델링만으로 개발이 가능해야 된다고 생각합니다.
그만큼 Context의 속성, 연관관계, 책임과 역활을 분명하게 나타내야합니다.
요구사항을 기반으로 용어사전을 사용하여 작성해보시면 좋을것 같습니다.^^

2020-02-23 08:55 UTC, sihoony commented on README.md
> +- 단체 해지는 OrderStatusCondition에 따라 변경한다.
OrderStatusCondition 용어는 등록되지 않는것 같아요.
용어를 사용하기 보다는 조건은 풀어서 작성해보는건 어떨까요?

2020-02-23 08:55 UTC, sihoony commented on README.md
> +- Menu는 MenuGroup과, MenuProduct, Name, Price를 가진다.
MenuGroup으로 포함될수 있는 조건이 있을 것 같아요.
추가로 menu와 menugroup의 연관관계도 명시해보는건 어떨까요?

2020-02-23 08:55 UTC, sihoony commented on README.md
> +- 주문 테이블은 손님수(NumberOfGuest)와 주문 테이블의 상태(OrderTableStatus)를 가진다.
NumberOfGuest는 등록되여 있지 않은것 같아요~
Guest의 수라고 작성해보는건 어떨까요?
용어사전에 등록된 용어를 활용해보세요.^^

2020-02-23 08:55 UTC, sihoony commented on README.md
> +- OrderStatus는 OrderStatusCondition에 따라 변경한다.
어떤 조건이 있는지 명확하지가 않습니다.^^ 명확하게 작성해 보세요

2020-02-28 15:00 UTC, withalice commented on README.md
>  ## 모델링
피드백 감사합니다!
말씀하신것처럼 "모델링만으로 개발이 가능해야 된다" 를 생각하며 작성해보았는데...많은 연습이 필요하겠다 싶숩니다. 
수정을 해보았는데 아직도 많이 미흡한것같네여..
다시 피드백 부탁드리겠숩니다! 
감사합니다!

2020-03-02 01:54 UTC, sihoony requested changes
고생하셨습니다.
몇가지 코멘트를 남겼으며 생각해보시면 좋을것 같습니다.
궁금하신점은 슬랙이나 코멘트 남겨주세요~^^

2020-03-02 01:54 UTC, sihoony commented on README.md
> +    - 상품 가격은 0원 이상이다.
상품의 기능은 무엇이 있을까요~?
저장과 조회 기능도 명시해보는건 어떨까요~^^

2020-03-02 01:54 UTC, sihoony commented on README.md
> +    - MenuProduct의 목록의 상품금액의 합이 Price 보다 크거나 같다.
menu가 무엇을 하는지 작성해 보는건 어떨까요~^^

2020-03-02 01:54 UTC, sihoony commented on README.md
> +    - OrderTable의 수가 2개 이상이다.
TableGroup과 OrderTable이 어떤것으로 연관관계가 묶여있는지 명시해보는건 어떨까요??^^

2020-03-02 01:55 UTC, sihoony commented on README.md
>  ## 모델링
지속적으로 피드백 드리겠습니다~^^
단계별로 피드백을 드릴 예정이며 궁금하신점은 슬랙이나 코멘트 남겨주세요.

2020-03-02 13:58 UTC, withalice commented on README.md
>  ## 모델링
네넵 감사합니다!
궁금한게 있는데욥 수정이나 등록시에 조건들은 별도의 정책으로 다 빼는게 더 좋을까요? 
우선 공석 변경 조건에 대해 정책으로 빼보았는데 이런식으로 하면 간결해질것같다는 생각이 듭니다!

2020-03-03 22:10 UTC, sihoony approved these changes
피드백 잘 반영해 주셨습니다.
궁금하신 점에 대해서 코멘트 남겼으며 여러 번의 피드백을 반영하는데 힘드셨을 텐데 고생하셨습니다.^^
다음 미션을 위해서 Merge 하겠습니다.

2020-03-03 22:10 UTC, merged