2단계 모델링 하기
next-step/ddd-strategic-design pull request #435
Opened 2024-06-05 12:13 UTC by gutenLEE

속성과 속성에 관련된 정책으로 분리했는데
작업하면서 행위도 정책에 포함 시키는게 맞을지 좀 헷갈렸습니다!

2024-06-06 13:39 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드려요.

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +- 매장 주문 정책
주문의 도메인 모델링에 내용이 많아 조금 복잡하게 느껴지네요.

배달 주문, 포장 주문, 매장 주문에 대한 도메인을 나누고 각각의 속성이나 행위, 이에 대한 정책들을 별도로 정리하는건 어떨까요?

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +  - `Product`의 `목록`을 조회할 수 있다
> 속성과 속성에 관련된 정책으로 분리했는데
> 작업하면서 행위도 정책에 포함 시키는게 맞을지 좀 헷갈렸습니다!

단순히 등록하거나 목록을 조회하는것까지 정책의 하위로 분류되는게 조금 어색한 것 같아요.

명확하게 속성과 행위를 분리하고 속성과 행위 하위에 각각의 정책적인 부분을 적는건 어떨까요?

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +- 매장 주문 정책
그리고 배달 주문, 매장 주문 별로 아래와 같이 주문 상태 변경 흐름을 한 눈에 알 수 있도록 표현하는것도 좋을 것 같습니다.

- 배달 주문
  - 접수 대기 -> 접수 -> 서빙 -> 배달 시작 -> 배달 완료 -> 완료 순서로 상태가 변경되어야 한다.

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +  - `OrderLineItem`은 `Menu`, `price`, `quantity`를 가진다
OrderLineItem 도메인에 대한 한글명이 정의되면 좋을 것 같네요.

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +  - `OrderLineItem`은 `Menu`, `price`, `quantity`를 가진다
OrderLineItem은 `List<OrderLineItem>`으로 정의되어야 합니다. 모델링의 내용만 보면 1개만 가지는 것으로 착각할 수 있어보이네요.

모델링 단계이므로 Order와 OrderLineItem간의 관계가 1 : N인지 어떤지 등에 대해 정리하는것도 좋을 것 같아요.

그리고 OrderLineItem의 수량(quantity)에 대한 정책은 잘 정리해주셨는데 이 부분 이외에 OrderLineItem이 1개 이상 존재해야 한다는 부분도 정리되면 좋을 것 같아요.

2024-06-06 13:39 UTC, kyucumber commented on README.md
> +## 주문
다소 복잡한데 필요에 따라 클래스 다이어그램 등을 통해 관계를 표현해볼 수 있을 것 같네요.

마크다운에서는 머메이드 등을 통해 나타낼 수 있습니다.

2024-06-10 12:47 UTC, gutenLEE commented
피드백 반영하면서 변경한 내용입니다
- 행위를 따로 정의 / 행위에 관련된 정책을 해당 행위 하위에 나열
- 속성에 관련된 정책을 속성 해당 하위에 나열

2024-06-11 14:04 UTC, kyucumber approved these changes
모델링 잘 마무리 해주셨네요.

간단한 코멘트 하나 남겨두었어요. 고생 많으셨습니다.

2024-06-11 14:04 UTC, kyucumber commented on README.md
> +- `포장 주문`이 생성한다
문장이 어색하네요.

다른 곳과 동일하게 포장 주문을 생성한다가 적절해보여요.

2024-06-11 14:04 UTC, merged