🚀 3단계: 기능 우선 패키지 구성하기
next-step/ddd-strategic-design pull request #438
Opened 2024-06-08 22:21 UTC by dev-yoonjung

안녕하세요, 리뷰어님! 
3단계 미션을 수행해 PR 올립니다.

미션을 수행하면서 한가지 궁금한 점이 있었는데요! 

현재 `Order`를 `EatInOrder`, `DeliveryOrder`, `TakeoutOrder`로 분리하면서 테이블도 분리했는데요.

요구사항정의서에 있는 `주문 목록을 조회할 수 있다.`를 생각하면 `Order`로 테이블을 하나로 두는 것이 조회했을 때 더 유리하겠다 싶더라구요. 
이 경우에 `Order`라는 영속성 엔티티와 서비스, 컨트롤러를 만들어야 하는데 order 하위에 common에다가 두어야 할까요..?

2024-06-09 02:14 UTC, liquidjoo requested changes
안녕하세요 윤정님 :)
3단계 미션 잘해주셨어요 👍 
질문 주신 내용에 대해 코멘트 하나 남겼습니다!
확인하고 다시 요청해 주세요 🙇

2024-06-09 02:14 UTC, liquidjoo commented on src/main/java/kitchenpos/order/delivery/application/DeliveryOrderService.java
> +    }
질문 주신 부분에 있어서 여러 방법이 있을 것 같은데요 :)
제 기준엔 두 가지가 방안이 있을 것 같아요
- 추상화를 통해 진행해 본다.
- CQRS 를 통해 조회는 별도의 쿼리 or 조합을 통해 별도로 둔다

이렇게 나누어 볼 수 있을 것 같아요! 어떤 방법을 선호하시든 다 좋습니다

2024-06-11 02:08 UTC, dev-yoonjung commented on src/main/java/kitchenpos/order/delivery/application/DeliveryOrderService.java
> +    }
안녕하세요, 리뷰어님! 
저도 추상화 클래스인 order를 생각했는데요!
이 order를 어디에다가 둘 지에 대한 고민이 있어 리뷰어님의 의견을 듣고 싶었습니다!😭
변수명 짓기같은 흔히하는 고민이었어요ㅎㅎ

2024-06-11 23:54 UTC, liquidjoo commented on src/main/java/kitchenpos/order/delivery/application/DeliveryOrderService.java
> +    }
음 현재 상황에서 저라면 ! order 패키지 하위에 domain 패키지를 만들거나 order 패키지 하위에 일단 AbstractOrder 와 같이 만들어 놓을 것 같아요 :)
이유는 AbstractOrder 를 바로 사용하는 일이 없고 구현체를 통해서만 구현해야하기 때문이라고 생각이 드네요 !

2024-06-12 00:00 UTC, liquidjoo approved these changes
안녕하세요 윤정님 :)
3단계 피드백 잘해주셨어요 👍 
저와 함께 했던 리뷰들이 도움이 되었길 빌며 마무리하겠습니다
수고하셨습니다 🙇

2024-06-12 00:00 UTC, merged