2단계 - 모델링 하기
next-step/ddd-strategic-design pull request #71
Opened 2021-08-17 13:08 UTC by y2o2u2n

리뷰 잘 부탁드리겠습니다 :)

> 기존 용어 사전도 다시보면서 코드에서 쓰는 것처럼 타입, 클래스, 메서드의 이름처럼 변경해봤습니다.
괜찮은 방법인지는 잘 모르겠네요 ㅎㅎ;

2021-08-18 16:03 UTC, liquidjoo requested changes
모델링 하기 미션 잘해주셨어요 👍 
몇가지 코멘트 남겼어요. 확인하고 리뷰 요청 주세요~

2021-08-18 16:03 UTC, liquidjoo commented on README.md
> +    - `accept` 되면 `OrderStatus` 가 `ACCEPTED` 이 된다.
현재의 모델링으로 개발을 한다면 조금 헷갈릴 수 있는 부분인 것 같아요.
ex)
- 주문을 어떠어떠한 경우에 accept 한다.

2021-08-19 15:22 UTC, y2o2u2n commented on README.md
> +    - `accept` 되면 `OrderStatus` 가 `ACCEPTED` 이 된다.
`OrderStatus` 가 `WAITING` 인 경우, `Order` 를 `accept` 할 수 있다.

=>

`OrderStatus` 가 `WAITING` 인 경우, `Order` 를 `accept` 한다.

위와 같이 바뀌는 걸 말씀하시는 걸까요?

2021-08-21 14:41 UTC, y2o2u2n commented
메세지로 자세하게 설명해주셔서 이해가 갔습니다 :)

수행 조건이나 자세한 수행 내용을 한 뎁스 아래로 내려서 좀 더 읽기 쉽게 변경했습니다.

감사합니다!

2021-08-22 07:34 UTC, liquidjoo approved these changes
모델링 하기 잘해주셨어요 👍 
DM으로 소통하면서 의견을 나누고 저의 요구사항을 잘 이해해주셔서 감사해요 🙇 
다음 단계를 위해 Merge 할게요

2021-08-22 07:35 UTC, merged