2단계 - 모델링
next-step/ddd-strategic-design pull request #73
Opened 2021-08-18 06:57 UTC by loop-study

안녕하세요 박현철입니다.
모델링이란 용어에 ERD 다이어그램을 생각했지만
힌트를 보니 생각했던거와 전혀달라서 원하는 방향으로 진행했는지 가물가물합니다.
확인 부탁드리겠습니다.
감사합니다! 🙈

2021-08-19 03:32 UTC, sah3122 commented
모델링 과정이 익숙하지 않아서 미션 진행이 쉽지 않으실거 같아요. 
제가 생각하는 팁을 드리자면, 요구 사항에 정리한 것들을 모델링 결과물을 참고하여 코드로 나타 낼수 있을 정도가 되면 좋을것 같아요.
이 과정에서 기술적인 내용이 포함될 수 있는데, 그러한 내용들이 용어사전에 등록되어 있다면 프로젝트에 참여하는 이해 관계자 분들도 
어렵지 않게 이해할 수 있을거에요.
이러한 내용을 참고하여 반영 부탁드릴게요 🙏

2021-08-19 03:33 UTC, sah3122 requested changes
미션 구현 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드립니다 😄

2021-08-19 03:33 UTC, sah3122 commented on README.md
>  ## 모델링
나눠주신 바운디드 컨텍스트를 명시해보는것이 어떨까요 ㅎㅎ 
앞서 진행해주신 용어사전과 더불어 모델링 결과도 바운디드 컨텍스트 안에서 힘을 발휘 한답니다 😄

2021-08-19 03:33 UTC, sah3122 commented on README.md
> +`Order`는 주문 정보(`OrderType`, `OrderStatus`, `OrderLineItem`, `OrderTable`, 주문 시각, 배송지)를 가진다.
컨텍스트가 다를 경우 직접 참조 보다는 ID 를 통한 간접 참조를 명시해보는것이 어떨까요 ? 
Order가 생성되는 시점에 어떤 상태를 가지는지도 정의하면 좋을것 같네요 😄

2021-08-19 03:33 UTC, sah3122 commented on README.md
> +`OrderStatus`는 주문 상태 `WAITING`, `ACCEPTED`, `SERVED`, `DELIVERING`, `DELIVERED`, `COMPLETED` 로 구분한다.
주문 상태의 변화도 기술해보세요 !

2021-08-19 03:33 UTC, sah3122 commented on README.md
> +`ProductService`에서 `Product`를 만들고 관리한다.
상품을 만드는 과정이 단순하게 일어나지는 않을것 같아요. 
조금더 상세하게 모델링 해보면 어떨까요 ?

2021-08-19 03:33 UTC, sah3122 commented on README.md
> +`OrderService`은 `Order`를 만들고 관리한다.
만들고 관리한다고 서술하기 보다는 상세하게 구분지어 볼수 있을까요 > ?
모델링 된 결과물로 코드를 직접 작성할 수 있을정도면 좋을것 같아요 😄

2021-08-19 03:33 UTC, sah3122 commented on README.md
> +`PurgomalumClient`는 다양한 비속어를 확인한다.
```suggestion
`ProductService`는 `PurgomalumClient`을 통해 비속어를 필터링한다. 
```
이처럼 모델링 한다면 모델링 결과물을 코드로 나타내기 편하실거에요 😄

2021-08-20 09:13 UTC, loop-study commented on README.md
> +`OrderService`은 `Order`를 만들고 관리한다.
상세하게 분리했습니다!

2021-08-20 09:13 UTC, loop-study commented on README.md
> +`PurgomalumClient`는 다양한 비속어를 확인한다.
참고하겠습니다!

2021-08-20 09:14 UTC, loop-study commented on README.md
> +`ProductService`에서 `Product`를 만들고 관리한다.
상세하게 해보곘습니다!

2021-08-20 09:14 UTC, loop-study commented on README.md
> +`OrderStatus`는 주문 상태 `WAITING`, `ACCEPTED`, `SERVED`, `DELIVERING`, `DELIVERED`, `COMPLETED` 로 구분한다.
상태에 따른 변화 기술하겠습니다!

2021-08-20 09:14 UTC, loop-study commented on README.md
> +`Order`는 주문 정보(`OrderType`, `OrderStatus`, `OrderLineItem`, `OrderTable`, 주문 시각, 배송지)를 가진다.
디폴트값 명시하곘습니다.

2021-08-20 09:14 UTC, loop-study commented on README.md
>  ## 모델링
컨텍스트 분리하겠습니다.

2021-08-20 09:15 UTC, loop-study commented
안녕하세요 박현철입니다.
피드백 반영하여 대폭 수정했습니다. 📃
확인 부탁드리겠습니다! 👀

2021-08-21 03:42 UTC, sah3122 requested changes
피드백 반영 잘해주셨네요 👍 
몇가지 코멘트를 남겨두었는데 확인 부탁드려요 😄

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +    - 그룹명은 반드시 입력해야한다.
비속어가 입력될 수 없는 것도 모델링에 포함시켜 보는게 어떠세요 ?

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +  - 가격 : 상품 가격이다.
일반적으로 모델링 과정도 개인이 아닌 프로젝트에 참여하는 사람들과 진행합니다 ㅎㅎ
변수명도 모델링에 포함시켜 보세요 😄 
도메인에서 중요한 의미를 가지면 용어사전에도 추가하는것을 권장 드립니다 👍

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +    - 상품 가격은 0원 이상 입력한다.
```suggestion
    - 상품 가격(Price)은 0원 이상 입력한다.   
```
영문명도 표기해보면 좋을것 같아요.

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +  - `menuProducts` : 메뉴에 판매될 상품들이다.
자연스러운 문장이 되도록 변경해보는건 어떨까요 ? 
```suggestion
  - 외부에 노출되는 메뉴 명(Name)을 가진다. 
  - 판매 금액(Price)을 가진다.  
  - 고객에게 제공하거나 제공하지 않을수 있도록 관리하는 공개여부(Display)를 가진다. 
  ...
```

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +    - 메뉴 가격이 `menuProducts`의 가격보다 높으면 안된다.
자연스러운 문장이 되도록 다듬어 보는건 어떨까요 ㅎㅎ
몇몇 문장들이 자연스럽지아 않네요 !

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +  - `OrderTable`를 정리한다.
```suggestion
  - `OrderTable`를 정리(Clear)한다.
```
모든 상황에서 정리할수 있는건 아닐것 같아요 !

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +    - 주문 시각은 LocalDateTime.now()로 가져온다.
```suggestion
    - 주문 시각은 현재시각으로 등록한다.
```
LocalDateTime.now() 와 같이 개발자에게 특화된 언어는 사용하지 않는것이 좋아보여요.

2021-08-21 03:42 UTC, sah3122 commented on README.md
> +    - `OrderStatus.WAITING` 상태만 `OrderStatus.ACCEPTED` 변경이 가능하다.
```suggestion
    - `WAITING` 상태만 `ACCEPTED` 변경이 가능하다.
```
WAITING, ACCEPTED가 용어 사전에 등록되어 있으니 OrderStatus는 생략해도 될거 같습니다 ㅎㅎ

2021-08-21 03:43 UTC, loop-study commented on README.md
> +### 메뉴그룹
명시하곘습니다!

2021-08-21 03:43 UTC, loop-study commented on README.md
> +  - 가격 : 상품 가격이다.
알겠습니다!

2021-08-21 03:48 UTC, loop-study commented on README.md
> +  - `OrderTable`를 정리한다.
확인하겠습니다!

2021-08-21 03:48 UTC, loop-study commented on README.md
> +    - 주문 시각은 LocalDateTime.now()로 가져온다.
알겠습니다!

2021-08-21 03:48 UTC, loop-study commented on README.md
> +    - `OrderStatus.WAITING` 상태만 `OrderStatus.ACCEPTED` 변경이 가능하다.
넵!

2021-08-21 04:38 UTC, loop-study commented on README.md
> +    - 그룹명은 반드시 입력해야한다.
이름은 모두 비속어 필터링 해야겠네요.

2021-08-21 04:46 UTC, loop-study commented on README.md
> +  - `menuProducts` : 메뉴에 판매될 상품들이다.
전체적으로 수정하겠습니다.

2021-08-21 07:31 UTC, loop-study commented
안녕하세요 박현철입니다.
피드백 내용을 바탕으로 모델링을 부드럽게 수정했습니다.
확인 부탁드리겠습니다.
감사합니다! 👍

2021-08-22 07:42 UTC, sah3122 approved these changes
모델링 정말 잘해주셨네요 👍 
모델링한 결과 값을 바탕으로 패키지 분리 부탁드려요 😄

2021-08-22 07:42 UTC, merged