Step2: 모델링 하기
next-step/ddd-strategic-design pull request #75
Opened 2021-08-19 00:38 UTC by ghojeong

용어 사전을 기반으로 모델링을 작성해보았습니다.
용어 사전에 있는 용어들의 Context 를 나누고, 해당 Context 의 속성과 기능/조건을 분석할 수 있도록 모델링했습니다.

Context 를 나누다 보니 Service 를 나눈 것과 비슷하게 나누어졌는데,
원래 Service 와 Context 가 1대1 대응 되는 것이 자주 일어나는 일인지 여쭈어봅니다.

2021-08-19 16:44 UTC, sah3122 commented
질문에 대한 제 생각 남겨드릴게요 😄 

정리하자면 Context를 나누는 기준에 따라 다를것 같아요.
현재 나누어주신 컨텍스트는 상품 / 메뉴 / 메뉴 그룹 / 주문 / 주문 테이블 으로 분리 해주셨는데, 이처럼 분리하는 경우는 가장 작은 단위를 하나의 컨텍스트로 분리해주신 경우에요. 다음 시간에 배우게 되는 개념인 에그리게잇을 기준으로 컨텍스트를 구분지어 주신것과 같아요. 
다른 관점에서는 상품, 메뉴, 메뉴 그룹 세가지 컨텍스트를 하나의 큰 상품 컨텍스트로 분류하고, 주문과 주문 테이블을 주문 컨텍스트로 분류할수도 있을것 같아요. 
상품 컨텍스트에서는 상품을 등록하고, 관리하는 역할을 하고 주문 컨텍스트에서는 주문과 관련된 시스템을 제공하는거죠. 
현재 어플리케이션이 더 많은 기능을 제공하고 컨텍스트의 크기가 커진다면 Service가 여러개 생길수도 있을거에요. 
일반적으로는 컨텍스트는 하나의 핵심 도메인을 지원하는것이 이상적이라고 알고 있습니다. 

여담이지만 컨텍스트를 어떻게 나누냐에 따라서 시스템의 설계방향이 크게 좌우됩니다. 
현업에서는 도메인 전문가와 함께 컨텍스트를 정의하는것이 이상적인 과정일것이고 개발자와 도메인 전문가는 서로 의견을 주고 받으며 도메인을 설계 하게 될것입니다. 😄 
도메인 전문가는 비 도메인 전문가들이 설계를 올바른 방향으로 할수 있도록 가이드 하고 개발자는 도메인 전문가의 의견을 기술적인 측면에서 검토하는 과정을 거치게 되죠 ㅎㅎ

2021-08-19 16:45 UTC, sah3122 requested changes
모델링 정말 잘해주셨네요 👍 
간단한 생각거리 남겨두었는데 확인 부탁드립니다 😄

2021-08-19 16:45 UTC, sah3122 commented on README.md
> +- 주문의 배달을 시작할 수 있다.
배달 대행사도 모델링에 포함시켜 보세요 ~

2021-08-19 16:45 UTC, sah3122 commented on README.md
>  ## 모델링
Context 기준으로 속성, 기능, 조건을 잘 분리 해주셨네요 👍

2021-08-19 16:45 UTC, sah3122 commented on README.md
> +- 빈 테이블로 설정할 수 있다.
빈 테이블로 설정하지 못하는 조건도 포함시켜보는게 어떨까요 ?

2021-08-20 05:28 UTC, ghojeong commented on README.md
> +- 빈 테이블로 설정할 수 있다.
앗! 모델링의 내용이 방대하다보니 빼먹었군요!
역시 이런걸 점검 받기 위해서라도 모델링은 혼자서 하기 보다는 여러 동료들에게 피드백을 받아야겠네요.

2021-08-20 05:28 UTC, ghojeong commented on README.md
> +- 주문의 배달을 시작할 수 있다.
주문의 배달을 시작한 후, 배달을 해주는 주체가 배달 대행사가 될수 있도록 명시하겠습니다.

2021-08-20 05:30 UTC, ghojeong commented on README.md
> +    - `product` 의 `name` 은 비속어(`profanity`)가 포함될 수 없다.
비속어를 필터링할 때 PurgomalumClient 라는 외부 클라이언트를 이용하는 과정을 모델링에 포함시키겠습니다.
이런 것도 모델리에 포함시켜야 나중에 비속어 필터가 오작동시에, 다른 부서끼리 서로 소통하기 편하겠네요.

개발자 혼자만의 잘못이 아니라는 것을 명시하기 위해서라도,
이런 것은 꼭 빼먹지 않도록 하는게 확실히 좋겠습니다.
업무상으로 꿀팁하나 알아가는 군요 ㅎㅎ

2021-08-20 05:36 UTC, ghojeong commented
> 다음 시간에 배우게 되는 개념인 에그리게잇을 기준으로 컨텍스트를 구분지어 주신것과 같아요.

아하 그렇군요. 아직 에그리게잇이 정확히 무엇인지 잘 모르는데, 다음 수업이 기대가 되네요.

> 일반적으로는 컨텍스트는 하나의 핵심 도메인을 지원하는것이 이상적이라고 알고 있습니다.

이런걸 root 에그리게잇이라고 부르나요?

> 여담이지만 컨텍스트를 어떻게 나누냐에 따라서 시스템의 설계방향이 크게 좌우됩니다.

[콘웨이의 법칙](https://johngrib.github.io/wiki/Conway-s-law/) 이 떠오르는군요.
도메인 전문가와 어떻게 소통했냐에 따라, 컨텍스트와 시스템의 설계 방향이 좌지우지 될것 같다는 생각이 드네요.

> 현업에서는 도메인 전문가와 함께 컨텍스트를 정의하는것이 이상적인 과정일것이고 개발자와 도메인 전문가는 서로 의견을 주고 받으며 도메인을 설계 하게 될것입니다. 😄
> 도메인 전문가는 비 도메인 전문가들이 설계를 올바른 방향으로 할수 있도록 가이드 하고 개발자는 도메인 전문가의 의견을 기술적인 측면에서 검토하는 과정을 거치게 되죠 ㅎㅎ

도메인 전문가와, 비도메인 기술자들이 서로 활발하게 소통할 수 있는 직장 문화에서 일해보고 싶네요 ㅎㅎ
기업 규모가 아주 작은게 아니면, 부서가 나뉘어서 서로 얼굴과 이름도 모르는 경우가 많은 것 같아서요 흑흑

2021-08-21 02:55 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
미션 구현을 잘해주셔서 다음 미션 진행하도록 할게요 💯 
좋은 주말 보내세요 😄

2021-08-21 02:55 UTC, merged