[Step2] 모델링하기
next-step/ddd-strategic-design pull request #76
Opened 2021-08-19 12:12 UTC by blossun

안녕하세요 :)
아직 2단계를 끝내지 못하였는데 맞게하고 있는지 몰라서 중간 리뷰요청드립니다. 🙂

모델링을 UML로만 해보아서 막상 글로 작성하려고 해보니 어느 정도로 적어야하는지 어려웠습니다.ㅎㅎ 
몇가지 질문 사항이 있습니다.
* 말로 적은 수도코드를 코드로 바로 옮겨 적을 수 있는 것처럼 모델링도 바로 코드로 옮겨 적을 수 있을 정도로 작성하는건가요?
  예를 들어 메서드명, 변수명도 이 단계에서 지어주는건지 궁금합니다.
* 모델링을 하다보니 비속어 필터링 부분이 반복적으로 나오는데 이부분을 어떻게 개선해야할지 고민하게 되었습니다.
도메인에 들어가는 값을 검사하는 로직이다보니 도메인에서 체크하도록 하고싶었는데, DB 테이블의 컬럼과 상관없는 PrugomalumClient 필드가 생길 것 같아서 적절하지 않을 것 같은데 그냥 서비스에서 체크하는 것이 맞을까요?
값에 대한 검증을 응용 서비스에서 하면 보통 도메인에서는 하지 않나요?

이후 코드도 피드백 반영해서 진행하겠습니다! 감사합니다!

2021-08-20 12:45 UTC, sah3122 commented
질문에 대한 제 생각 남겨 드릴게요 !

* 말로 적은 수도코드를 코드로 바로 옮겨 적을 수 있는 것처럼 모델링도 바로 코드로 옮겨 적을 수 있을 정도로 작성하는건가요?
예를 들어 메서드명, 변수명도 이 단계에서 지어주는건지 궁금합니다.

> 다른 코멘트에서도 남겨두었듯이 저는 메서드명까지는 모델링에 포함시키는 편은 아니에요. 
변수명과 같은 경우는 모델링 과정에 포함하여 엔티티 설계를  진행하곤 합니다. 😄 

* 모델링을 하다보니 비속어 필터링 부분이 반복적으로 나오는데 이부분을 어떻게 개선해야할지 고민하게 되었습니다.
도메인에 들어가는 값을 검사하는 로직이다보니 도메인에서 체크하도록 하고싶었는데, DB 테이블의 컬럼과 상관없는 PrugomalumClient 필드가 생길 것 같아서 적절하지 않을 것 같은데 그냥 서비스에서 체크하는 것이 맞을까요?
값에 대한 검증을 응용 서비스에서 하면 보통 도메인에서는 하지 않나요?

> 도메인이 특정 서비스 또는 외부 API에 크게 의존하는건 지향하지 않아요. 도메인의 값을 검증한다는것은 다르게 이야기 할 경우 유효성 검사를 진행한다고 할수 있어요. 유효성 검사로직을 도메인에서 구현하는것이 아닌, 외부 클래스에 위임할수 있을것 같아요. 

```java
#Product.class
...

public void validateName(PrugomalumClient prugomalumClient) {
    prugomalumClient.validate(this.name);
}

...
```

위처럼 구현할 수 있다면 도메인은 이름 값을 검사할수 있고 PrugomalumClient 필드는  생기지 않을거에요. 
단순한 예시지만, 다른 방법으로도 구현할 수 있을거에요 😄

2021-08-20 12:45 UTC, sah3122 requested changes
모델링 너무 잘해주셨네요 👍 
도움이 되실만한 코멘트 남겨두었는데 확인 부탁드려요 🙏

2021-08-20 12:45 UTC, sah3122 commented on README.md
> +* `Product`는 `isValidPrice()`로 유효한 가격("0원 이상")인지 알려준다.
```suggestion
* `Product`는  0원 이상의 가격을 가진다.
```
정도면 될거 같아요 ㅎㅎ 
`isValidPrice`를 모델링에 포함 시키고 싶으시다면 해당 언어가 용어 사전에 등록 되어 있어야 한다고 생각해요. 
그렇지 않으면 `isValidPrice`는 부족지식에 해당하기 때문에 특정 직군에 있는 사람들만 이해 할 수 있을거에요 .

2021-08-20 12:45 UTC, sah3122 commented on README.md
> +* `ProductService`에서 다음 기능을 제공한다.
`ProductService`가 제공하는 기능보다는 Product 도메인에서 제공하는 기능으로 모델링 해보면 어떨까요 ?
Product 도메인에서 ProductService와 같은 서비스(어플리케이션 서비스 또는 도메인 서비스)를 이용하는 모델링이면 좋을것 같아요 😄

2021-08-20 12:45 UTC, sah3122 commented on README.md
> +* `Menu`는 메뉴 이름(`name`), 가격(`price`), 메뉴가 속한 메뉴 그룹(`MenuGroup`), 메뉴 노출 여부(`displayed`), 메뉴에 속한 상품 목록(`List<MenuProduct>`)을 가진다.
`MenuProduct`의 속성도 정의해보시겠어요 ? 
`MenuGroup`과 같은 연관관계 정보는 직접 참조로 구현되는지 간접 참조로 구현되는지도 모델링에 포함 시켜보세요. 
모델링 결과를 바탕으로 클래스 설계를 할수 있을거에요 😄

2021-08-20 12:45 UTC, sah3122 commented on README.md
> +        * 메뉴가 속하려는 `MenuGroup`을 `MenuGroupRepository`에서 조회한다. 없으면 `NoSuchElementException` 처리한다.
```suggestion
        * 메뉴는 특정 `MenuGroup`에 속해야 한다.
```
다른 코멘트에서 남겨드린것 처럼 개발자만 알수 있는 언어는 모델링에 포함시키지 않는것이 좋아요. 
도메인에서 중요한 언어라면 용어사전에 등록하고, 모델링에 포함시키는것을 권장드립니다 !

2021-08-20 12:45 UTC, sah3122 commented on README.md
> +### 상품
상품을 하나의 컨텍스트로 구분지어 주신거라면 모델링 작성시 속성과 기능, 조건 등을 구분 시켜 정리해본다면 작성하기 편해질것 같아요 😄

2021-08-23 09:00 UTC, blossun commented
리뷰어님 코드리뷰 감사드립니다 :)
피드백 주신 부분 반영해서 수정하고, 내용 추가하였습니다. 

연관관계 관련해서 궁금한 부분이 있어 질문드립니다.
ID를 이용한 참조일 경우에 가져갈 수 있는 장점들을 알아보았는데, DDD에서는 무조건 ID 참조 방식이 좋은 건가요?
"ID를 참조한다"는 것은 엔티티를 테이블처럼 생각하고 구현하는 느낌이 듭니다..ㅎㅎ
그리고, 이전에 잘 모르고 DDD를 적용해보려고 했을 때, ID 참조 방식이 불편하다고 느껴졌는데 도메인의 복잡도(?)가 낮아서 ID 참조가 주는 장점을 못느낀 것인지... 도메인이 크고 서비스가 작게 나뉘어진다면 그 불편함을 감수하고 더 큰 장점을 가져갈 수 있는 것인지 궁금했습니다.

JPA를 써서 가져갈 수 있는 편리함이 필드 참조라고 생각하는데 이 편리함을 버릴만큼 지켜지면 좋은 구현방식인지 아니면 선택의 영역인지 궁금합니다.

2021-08-24 10:47 UTC, sah3122 commented
안녕하세요 😄 
좋은 질문 주셨네요 👍 
저도 많이 고민 해보았던 문제들인데 제 생각을 남겨드릴게요. 

우선 무조건 ID를 이용한 간접 참조 방식이 좋은것은 아니라 생각해요. 특정 상황에서 직접 참조 보단 간접 참조를 이용하는것이 효과적일수 있어요. 
혹시 Aggregate, Aggregate Root에 관해서 알고 계실지 모르겠지만 하나의 Aggregate에 포함되는 관계는 직접 참조를 이용하기도 해요. 
두 Aggregate의 라이프 사이클이 동일하고 도메인이 서로 연관 되어 있어 Aggregate Root 에서 모든 요청을 받을수 있도록 설계하여 도메인을 더욱 깔끔하게 정제 할수 있습니다.
반대로 서로 다른 Aggregate으로 묶인다면 직접 참조보다는 간접 참조를 사용하는것이 효과적이라고 생각합니다. 만약 Aggregate이 분리되어 있는 상황에서 직접 참조를 사용하게 된다면 불필요한 결합이 생긴다고 생각해요. DDD를 코드에 녹여 얻는 장점 중 하나가 낮은 결합도와 높은 응집도라고 생각합니다. Aggregate이 분리되어 있다면 서로의 라이프 사이클 조차도 분리되어 있죠. 

그렇다 해서 반드시 동일한 Aggregate에서 직접 참조르 사용해야 하는것도 아니라고 생각해요. ORM 프레임워크를 사용하여 연관 관계를 가지는 엔티티를 편리하게 영속화 시켜 사용할 수 있지만 반대로 너무 편리한 나머지 불필요한 경우에서도 엔티티를 로드 하는 실수를 유발하기도 하죠. 
ID를 사용한 간접 참조를 사용했더라면 발생하지 않을 문제라고 생각해요 😄 

이처럼 서로 다른 Aggregate에서는 반드시 ID를 이용한 간접 참조를 사용하고 동일한 Aggregate에 속할 경우 직접 참조를 선택적으로 사용하면 좋을것 같습니다. 

추가적으로 Context가 분리되어 있는 경우에는 반드시 ID를 이용한 간접 참조를 사용해주시는것이 좋을것 같아요. 
전략적 설계를 통하여 Context를 잘 분리 해주셨다면 서비스, 기능이 완전히 분리되어 있을거에요. 각 컨텍스트들은 특정한 이해 관계를 통하여 서로 통신을 하게 될것이고 컨텍스트의 크기가 커지는 경우 하나의 마이크로 서비스로 분리될수 있기 때문이죠. 
만약 서로 다른 Context에서 직접 참조로 구현한 경우 어마어마한 대가를 치르게 될거에요 ..!

2021-08-24 10:50 UTC, sah3122 requested changes
피드백 반영 너무 잘해주셨네요 👍 
간단한 생각거리와 질문에 대한 답변 남겨두었으니 확인 해주시고 재 리뷰 요청 주시면 머지하도록 할게요 🙏 
질문은 언제나 환영이니 편하게 DM 주세요 😄

2021-08-24 10:50 UTC, sah3122 commented on README.md
> +### 상품(Product) Context
컨텍스트를 가장 작은 단위로 나뉘어 주셨는데 적절한 분리 였는지 고민 해보시면 좋을것 같아요. 
글로 표현만 하는것이 아닌 그림으로도 표현해보시면 더욱 좋을것 같고요 😄

2021-08-24 10:50 UTC, sah3122 commented on README.md
> +- 주문 목록을 조회할 수 있다.
모델링을 꼼꼼하게 잘해주셨네요 👍

2021-08-25 16:50 UTC, blossun commented on README.md
> +### 상품(Product) Context
컨텍스트 단위를 고민해보다 질문드립니다. 용어정리 구분 항목과 생명주기를 기준으로 컨텍스트를 나눴었습니다.

그런데 컨텍스트는 도메인을 표현하는 용어의 의미가 달라질 수 있는 경계인데, `상품 / 메뉴 / 메뉴 그룹 / 주문 / 주문 테이블` 로 나누었을 때, 메뉴의 상품과 상품에서의 상품은 같은 의미를 가지는 것 아닌지... 마찬가지로 메뉴 그룹의 메뉴는 메뉴(컨텍스트)의 메뉴와 같은 의미를 갖는 것 같은데 이렇게 5가지로 컨텍스트를 나눠도 괜찮은 것인가 의문이 들었습니다. 의미가 같다고 느껴지는 컨텍스트를 묶어서 나눠야하는 것인가 다시 고민이되었습니다.

Bounded Context를 나누는 기준이 어려운 것 같습니다.ㅠㅠ

그냥 애그리거트 루트 → Bounded Context 기준 이렇게 봐도 괜찮은 것인가요? 애그리거트 루트 내에서 용어의 의미가 달라진다고 볼 수 있나요?

2021-08-26 11:39 UTC, sah3122 approved these changes
모델링 잘해주셨습니다 👍 
질문에 대한 답변 남겨두었으니 확인 부탁드리고 더 궁금한 부분이 있다면 편하게 DM 주세요 😄

2021-08-26 11:39 UTC, merged